In [4]:
from komle.bindings.v1411.read import witsml
from komle import utils as ku
import pandas as pd # Not part of komle setup
from lxml import etree
tree=etree.parse(r'Dataset\Norway-Statoil-NO 15_$47$_9-F-9\1\log\1\2\1\00001.xml')

for not_witsml in tree.xpath("//*[starts-with(name(), 'priv_')]"):
    not_witsml.getparent().remove(not_witsml)
for not_witsml in tree.xpath("//*[starts-with(name(), 'feed')]"):
    not_witsml.getparent().remove(not_witsml)
for not_witsml in tree.xpath("//*[starts-with(name(), 'advantage')]"):
    not_witsml.getparent().remove(not_witsml)

logs = witsml.CreateFromDocument(etree.tostring(tree))
# Print the witsml documentation for logs
print(logs._element().documentation())

# Print the schema location for logCurveInfo, nice to have for reference
print(logs.log[0].logCurveInfo[0]._element().xsdLocation().locationBase)

print([l.name for l in logs.log])

# Convert logdata to a dict
log = logs.log[0]

data_dict = ku.logdata_dict(log)

# Create a dataframe, if you have installed pandas
df_data = pd.DataFrame(data_dict)

# Do the same for the plural logCurveInfo element
df_curve = pd.DataFrame(ku.plural_dict(log.logCurveInfo))

The WITSML API mandated plural root element which allows multiple singular objects to be sent. The plural name is formed by adding an "s" to the
         singular name.
http://w3.energistics.org/schema/WITSML_v1.4.1.1_Data_Schema/witsml_v1.4.1.1_data/generated_read_schemas/grp_log.xsd
['GwdTime']

In [5]:
df_curve

,typeLogData,curveDescription,maxDateTimeIndex,minDateTimeIndex,mnemAlias,unit,classWitsml,mnemonic
0,double,Total Gas,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,TOTGAS,Euc,gasAv,TOTGAS
1,double,Weight On Bit,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,WOB,N,wobAv,WOB
2,double,Chrom 1 Iso Pentane,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,CHR1IC5,Euc,ipentane,CHR1IC5
3,double,Pump 3 Cumulative Strokes,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,STROKES3,unitless,strokes,STROKES3
4,long,RawData[0],2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,EditFlag,unitless,None,EditFlag
5,double,Chrom 1 Normal Butane,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,CHR1NC4,Euc,nbutane,CHR1NC4
6,double,Mud Flow In,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,FLOWIN,m3/s,flowInAv,FLOWIN
7,double,Chrom 1 Methane,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,CHR1C1,Euc,methane,CHR1C1
8,double,Chrom 1 Ethane,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,CHR1C2,Euc,ethane,CHR1C2
9,double,Pump 1 Cumulative Strokes,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,STROKES1,unitless,strokes,STROKES1
10,double,Hole Depth,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,MDEPTH,m,None,MDEPTH
11,double,Trip Volume - PVT Group,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,TRIPPVT,m3,None,TRIPPVT
12,double,Chrom 1 Normal Pentane,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,CHR1NC5,Euc,npentane,CHR1NC5
13,double,Lagged Mud Returns Depth,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,MUDRETDEPTH,m,None,MUDRETDEPTH
14,date time,The mnemonic of the index curve,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,Time,unitless,None,Time
15,double,Hookload,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,HKLD,N,None,HKLD
16,double,Surface RPM,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,SURF_RPM,c/s,rpmAv,SURF_RPM
17,double,Mud Flow Out,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,FLOWOUT,m3/s,flowOutAv,FLOWOUT
18,double,Bit Measured Depth,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,BITDEP,m,None,BITDEP
19,double,The mnemonic of the Hole depth,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,Depth,m,None,Depth
20,double,Pump 2 Cumulative Strokes,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,STROKES2,unitless,strokes,STROKES2
21,long,NoMonitor[0] Drilling[1] Reaming[2] OffBottom[...,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,RigActivityCode,unitless,None,RigActivityCode
22,double,Mud Weight Out,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,MWOUT,kg/m3,wtMudOutAv,MWOUT
23,double,Bit RPM - Total RPM,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,BIT_RPM,c/s,None,BIT_RPM
24,double,Surface Torque Average,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,TORQUE,N.m,tqAv,TORQUE
25,double,Chrom 1 Iso Butane,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,CHR1IC4,Euc,ibutane,CHR1IC4
26,double,Trip Volume - PVT 2 Group,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,TRIPPVT2,m3,None,TRIPPVT2
27,double,Mud Weight In,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,MWIN,kg/m3,wtMudInAv,MWIN
28,double,Depth Averaged ROP,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,ROP_AVG,m/s,None,ROP_AVG
29,double,Chrom 1 Propane,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,CHR1C3,Euc,propane,CHR1C3
30,double,Pump Pressure - Stand Pipe,2016-09-30 09:46:45+00:00,2016-09-29 00:06:28+00:00,PUMP,Pa,presPumpAv,PUMP

In [6]:
df_data = pd.DataFrame(data_dict)
df_data

,Time,TOTGAS,WOB,CHR1IC5,STROKES3,EditFlag,CHR1NC4,FLOWIN,CHR1C1,CHR1C2,...,RigActivityCode,MWOUT,BIT_RPM,TORQUE,CHR1IC4,TRIPPVT2,MWIN,ROP_AVG,CHR1C3,PUMP
0,2016-09-29 00:06:28+00:00,0.0,27164.3900,0.0,0.00000,0,0.0,0.0,0.0,0.0,...,0,0.0,0.000000,7.242647,0.0,0.0,0.0,0.0,0.0,172983.08
1,2016-09-29 00:06:30+00:00,0.0,27117.0140,0.0,0.00000,0,0.0,0.0,0.0,0.0,...,0,0.0,0.000000,7.242647,0.0,0.0,0.0,0.0,0.0,172488.87
2,2016-09-29 00:06:45+00:00,0.0,26941.7230,0.0,0.00000,0,0.0,0.0,0.0,0.0,...,0,0.0,0.000000,7.242647,0.0,0.0,0.0,0.0,0.0,169703.19
3,2016-09-29 00:07:00+00:00,0.0,27343.1370,0.0,0.00000,0,0.0,0.0,0.0,0.0,...,0,0.0,0.000000,7.242647,0.0,0.0,0.0,0.0,0.0,170231.81
4,2016-09-29 00:07:15+00:00,0.0,27028.3030,0.0,0.00000,0,0.0,0.0,0.0,0.0,...,0,0.0,0.000000,7.242647,0.0,0.0,0.0,0.0,0.0,170291.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8079,2016-09-30 09:45:45+00:00,0.0,1326.9423,0.0,690.61997,0,0.0,0.0,0.0,0.0,...,114,0.0,0.004129,6.480159,0.0,0.0,0.0,0.0,0.0,124736.62
8080,2016-09-30 09:46:00+00:00,0.0,25423.3840,0.0,690.61997,0,0.0,0.0,0.0,0.0,...,114,0.0,0.004129,6.480159,0.0,0.0,0.0,0.0,0.0,124915.66
8081,2016-09-30 09:46:15+00:00,0.0,1931.1059,0.0,690.61997,0,0.0,0.0,0.0,0.0,...,114,0.0,0.004129,6.480159,0.0,0.0,0.0,0.0,0.0,124474.50
8082,2016-09-30 09:46:30+00:00,0.0,7763.5700,0.0,690.61997,0,0.0,0.0,0.0,0.0,...,114,0.0,0.004129,6.480159,0.0,0.0,0.0,0.0,0.0,124278.19
8083,2016-09-30 09:46:45+00:00,0.0,38748.7910,0.0,690.61997,0,0.0,0.0,0.0,0.0,...,114,0.0,0.004129,6.480159,0.0,0.0,0.0,0.0,0.0,123410.27