In [8]:
from komle.bindings.v1411.read import witsml
from komle import utils as ku
import pandas as pd # Not part of komle setup
from lxml import etree
tree=etree.parse(r'Norway-Statoil-NO 15_$47$_9-F-9\1\log\1\2\1\00001.xml')

for not_witsml in tree.xpath("//*[starts-with(name(), 'priv_')]"):
    not_witsml.getparent().remove(not_witsml)

logs = witsml.CreateFromDocument(etree.tostring(tree))
# with open(r'Norway-Statoil-NO 15_$47$_9-F-9\1\trajectory\1.xml', 'r') as log_file:
#     # logs is a regular python object according to the witsml schema
#     logs = witsml.CreateFromDocument(log_file.read())

# Print the witsml documentation for logs
print(logs._element().documentation())

# Print the schema location for logCurveInfo, nice to have for reference
print(logs.log[0].logCurveInfo[0]._element().xsdLocation().locationBase)

print([l.name for l in logs.log])

# Convert logdata to a dict
log = logs.log[0]

data_dict = ku.logdata_dict(log)

# Create a dataframe, if you have installed pandas
df_data = pd.DataFrame(data_dict)

# Do the same for the plural logCurveInfo element
df_curve = pd.DataFrame(ku.plural_dict(log.logCurveInfo))

Unable to convert DOM node {http://www.witsml.org/schemas/1series}feed at <unknown>[1:1403791] to binding
Unable to convert DOM node {http://www.witsml.org/schemas/1series}advantage at <unknown>[1:1403814] to binding

The WITSML API mandated plural root element which allows multiple singular objects to be sent. The plural name is formed by adding an "s" to the
         singular name.
http://w3.energistics.org/schema/WITSML_v1.4.1.1_Data_Schema/witsml_v1.4.1.1_data/generated_read_schemas/grp_log.xsd
['GwdTime']

In [6]:
df_curve

,typeLogData,curveDescription,maxDateTimeIndex,minDateTimeIndex,mnemAlias,unit,mnemonic,classWitsml
0,double,Drill Pit Group Cumulative Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT_DRILL,m3,PIT_DRILL,None
1,double,Pit 14 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT14,m3,PIT14,tvol
2,double,Pit 5 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT5,m3,PIT5,tvol
3,double,Pit 6 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT6,m3,PIT6,tvol
4,double,Total Pit Gain/Loss Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,GAINLOSSTOT,m3,GAINLOSSTOT,None
5,double,Pit 17 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT17,m3,PIT17,tvol
6,double,Pit 29 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT29,m3,PIT29,tvol
7,double,Pit 7 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT7,m3,PIT7,tvol
8,double,Pit 28 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT28,m3,PIT28,tvol
9,double,Pit Volume - Trip Out Group,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT_TRIPOUT,m3,PIT_TRIPOUT,None
10,double,Circulating Volume - (Pipe Capacity + annular ...,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,CIRCVOL,m3,CIRCVOL,None
11,double,Pit Volume Reset Depth,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT_RESET_DEPTH,m,PIT_RESET_DEPTH,None
12,double,Pit 25 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT25,m3,PIT25,tvol
13,double,Pit 15 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT15,m3,PIT15,tvol
14,double,The mnemonic of the Hole depth,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,Depth,m,Depth,None
15,double,Pit 1 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT1,m3,PIT1,tvol
16,date time,The mnemonic of the index curve,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,Time,unitless,Time,None
17,double,Pit 26 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT26,m3,PIT26,tvol
18,double,Pipe Displacement Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,DISPVOL,m3,DISPVOL,None
19,double,Pit 22 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT22,m3,PIT22,tvol
20,double,Pit 27 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT27,m3,PIT27,tvol
21,double,Total Pit Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PITTOT,m3,PITTOT,tvol
22,double,Pit 20 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT20,m3,PIT20,tvol
23,double,Pit 2 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT2,m3,PIT2,tvol
24,long,NoMonitor[0] Drilling[1] Reaming[2] OffBottom[...,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,RigActivityCode,unitless,RigActivityCode,None
25,double,Pit 10 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT10,m3,PIT10,tvol
26,double,Pit 18 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT18,m3,PIT18,tvol
27,double,Drill Pit Group Gain/Loss,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,GL_DRILL,m3,GL_DRILL,None
28,double,Pit 24 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT24,m3,PIT24,tvol
29,double,Pipe Capacity,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,DOWNVOL,m3,DOWNVOL,None
30,long,RawData[0],2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,EditFlag,unitless,EditFlag,None
31,double,Pit 16 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT16,m3,PIT16,tvol
32,double,Pit 11 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT11,m3,PIT11,tvol
33,double,Pit 4 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT4,m3,PIT4,tvol
34,double,Pit 3 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT3,m3,PIT3,tvol
35,double,Pit 30 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT30,m3,PIT30,tvol
36,double,Pit 8 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT8,m3,PIT8,tvol
37,double,Pit Volume - Trip In Group,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT_TRIPIN,m3,PIT_TRIPIN,None
38,double,Annulus Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,LAGVOL,m3,LAGVOL,None
39,double,Pit 9 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT9,m3,PIT9,tvol
40,double,Pit 13 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT13,m3,PIT13,tvol
41,date time,Pit Volume Reset Time,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT_RESET_TIME,unitless,PIT_RESET_TIME,None
42,double,Pit 19 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT19,m3,PIT19,tvol
43,double,Pit 21 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT21,m3,PIT21,tvol
44,double,Pit 23 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT23,m3,PIT23,tvol
45,double,Pit 12 Volume,2016-09-30 09:46:30+00:00,2016-09-29 00:06:28+00:00,PIT12,m3,PIT12,tvol

In [12]:
df_data = pd.DataFrame(data_dict)
df_data

,Time,TOTGAS,WOB,CHR1IC5,STROKES3,EditFlag,CHR1NC4,FLOWIN,CHR1C1,CHR1C2,...,RigActivityCode,MWOUT,BIT_RPM,TORQUE,CHR1IC4,TRIPPVT2,MWIN,ROP_AVG,CHR1C3,PUMP
0,2016-09-29 00:06:28+00:00,0.0,27164.3900,0.0,0.00000,0,0.0,0.0,0.0,0.0,...,0,0.0,0.000000,7.242647,0.0,0.0,0.0,0.0,0.0,172983.08
1,2016-09-29 00:06:30+00:00,0.0,27117.0140,0.0,0.00000,0,0.0,0.0,0.0,0.0,...,0,0.0,0.000000,7.242647,0.0,0.0,0.0,0.0,0.0,172488.87
2,2016-09-29 00:06:45+00:00,0.0,26941.7230,0.0,0.00000,0,0.0,0.0,0.0,0.0,...,0,0.0,0.000000,7.242647,0.0,0.0,0.0,0.0,0.0,169703.19
3,2016-09-29 00:07:00+00:00,0.0,27343.1370,0.0,0.00000,0,0.0,0.0,0.0,0.0,...,0,0.0,0.000000,7.242647,0.0,0.0,0.0,0.0,0.0,170231.81
4,2016-09-29 00:07:15+00:00,0.0,27028.3030,0.0,0.00000,0,0.0,0.0,0.0,0.0,...,0,0.0,0.000000,7.242647,0.0,0.0,0.0,0.0,0.0,170291.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8079,2016-09-30 09:45:45+00:00,0.0,1326.9423,0.0,690.61997,0,0.0,0.0,0.0,0.0,...,114,0.0,0.004129,6.480159,0.0,0.0,0.0,0.0,0.0,124736.62
8080,2016-09-30 09:46:00+00:00,0.0,25423.3840,0.0,690.61997,0,0.0,0.0,0.0,0.0,...,114,0.0,0.004129,6.480159,0.0,0.0,0.0,0.0,0.0,124915.66
8081,2016-09-30 09:46:15+00:00,0.0,1931.1059,0.0,690.61997,0,0.0,0.0,0.0,0.0,...,114,0.0,0.004129,6.480159,0.0,0.0,0.0,0.0,0.0,124474.50
8082,2016-09-30 09:46:30+00:00,0.0,7763.5700,0.0,690.61997,0,0.0,0.0,0.0,0.0,...,114,0.0,0.004129,6.480159,0.0,0.0,0.0,0.0,0.0,124278.19
8083,2016-09-30 09:46:45+00:00,0.0,38748.7910,0.0,690.61997,0,0.0,0.0,0.0,0.0,...,114,0.0,0.004129,6.480159,0.0,0.0,0.0,0.0,0.0,123410.27