In [6]:
import pandas as pd
from IPython.display import display as display_DF

In [27]:
fileRealtime = "RealTime_Test\\AAE-03_RealtimeSimulation.csv"

RealTime_DB = pd.read_csv(fileRealtime).iloc[:,2:]

RealTime_DB['dt'] = pd.to_datetime(RealTime_DB['dt'])
print(RealTime_DB.dtypes)
RealTime_DB

dt                          datetime64[ns]
date                                object
time                                object
bitdepth                           float64
md                                 float64
blockpos                           float64
rop                                float64
hklda                              float64
woba                               float64
torqa                              float64
rpm                                float64
stppress                           float64
mudflowin                          float64
LABEL_ConnectionActivity            object
LABEL_SubActivity                   object
LABEL_Activity                      object
dtype: object

,dt,date,time,bitdepth,md,blockpos,rop,hklda,woba,torqa,rpm,stppress,mudflowin,LABEL_ConnectionActivity,LABEL_SubActivity,LABEL_Activity
0,2021-05-11 03:10:03,2021-05-11,03:10:03,0.00,343.85,9.65,0.0,29.75,0.0,0.0,0.0,0.0,0.0,NO DATA,WAIT ON CEMENT,WAIT ON CEMENT
1,2021-05-11 03:10:08,2021-05-11,03:10:08,0.00,343.85,9.65,0.0,29.75,0.0,0.0,0.0,0.0,0.0,NO DATA,WAIT ON CEMENT,WAIT ON CEMENT
2,2021-05-11 03:10:13,2021-05-11,03:10:13,0.00,343.85,9.65,0.0,29.75,0.0,0.0,0.0,0.0,0.0,NO DATA,WAIT ON CEMENT,WAIT ON CEMENT
3,2021-05-11 03:10:18,2021-05-11,03:10:18,0.00,343.85,9.65,0.0,29.75,0.0,0.0,0.0,0.0,0.0,NO DATA,WAIT ON CEMENT,WAIT ON CEMENT
4,2021-05-11 03:10:23,2021-05-11,03:10:23,0.00,343.85,9.65,0.0,29.75,0.0,0.0,0.0,0.0,0.0,NO DATA,WAIT ON CEMENT,WAIT ON CEMENT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35196,2021-05-13 05:24:01,2021-05-13,05:24:01,1084.25,1163.32,6.39,0.0,140.81,0.0,0.0,0.0,0.0,0.0,NO DATA,STATIONARY,STATIONARY
35197,2021-05-13 05:24:06,2021-05-13,05:24:06,1084.25,1163.32,6.39,0.0,140.81,0.0,0.0,0.0,0.0,0.0,NO DATA,STATIONARY,STATIONARY
35198,2021-05-13 05:24:11,2021-05-13,05:24:11,1084.25,1163.32,6.39,0.0,140.81,0.0,0.0,0.0,0.0,0.0,NO DATA,STATIONARY,STATIONARY
35199,2021-05-13 05:24:16,2021-05-13,05:24:16,1084.25,1163.32,6.39,0.0,140.88,0.0,0.0,0.0,0.0,0.0,NO DATA,STATIONARY,STATIONARY
35200,2021-05-13 05:24:21,2021-05-13,05:24:21,1084.25,1163.32,6.39,0.0,141.07,0.0,0.0,0.0,0.0,0.0,NO DATA,STATIONARY,STATIONARY

In [29]:
RealTime_DB["LABEL_All"] =RealTime_DB['LABEL_ConnectionActivity'].astype(str) + '--' +RealTime_DB['LABEL_SubActivity']+'--'+RealTime_DB['LABEL_Activity']

display_DF(RealTime_DB.head(5))
display_DF(RealTime_DB.tail(5))

,dt,date,time,bitdepth,md,blockpos,rop,hklda,woba,torqa,rpm,stppress,mudflowin,LABEL_ConnectionActivity,LABEL_SubActivity,LABEL_Activity,LABEL_All
0,2021-05-11 03:10:03,2021-05-11,03:10:03,0.0,343.85,9.65,0.0,29.75,0.0,0.0,0.0,0.0,0.0,NO DATA,WAIT ON CEMENT,WAIT ON CEMENT,NO DATA--WAIT ON CEMENT--WAIT ON CEMENT
1,2021-05-11 03:10:08,2021-05-11,03:10:08,0.0,343.85,9.65,0.0,29.75,0.0,0.0,0.0,0.0,0.0,NO DATA,WAIT ON CEMENT,WAIT ON CEMENT,NO DATA--WAIT ON CEMENT--WAIT ON CEMENT
2,2021-05-11 03:10:13,2021-05-11,03:10:13,0.0,343.85,9.65,0.0,29.75,0.0,0.0,0.0,0.0,0.0,NO DATA,WAIT ON CEMENT,WAIT ON CEMENT,NO DATA--WAIT ON CEMENT--WAIT ON CEMENT
3,2021-05-11 03:10:18,2021-05-11,03:10:18,0.0,343.85,9.65,0.0,29.75,0.0,0.0,0.0,0.0,0.0,NO DATA,WAIT ON CEMENT,WAIT ON CEMENT,NO DATA--WAIT ON CEMENT--WAIT ON CEMENT
4,2021-05-11 03:10:23,2021-05-11,03:10:23,0.0,343.85,9.65,0.0,29.75,0.0,0.0,0.0,0.0,0.0,NO DATA,WAIT ON CEMENT,WAIT ON CEMENT,NO DATA--WAIT ON CEMENT--WAIT ON CEMENT

,dt,date,time,bitdepth,md,blockpos,rop,hklda,woba,torqa,rpm,stppress,mudflowin,LABEL_ConnectionActivity,LABEL_SubActivity,LABEL_Activity,LABEL_All
35196,2021-05-13 05:24:01,2021-05-13,05:24:01,1084.25,1163.32,6.39,0.0,140.81,0.0,0.0,0.0,0.0,0.0,NO DATA,STATIONARY,STATIONARY,NO DATA--STATIONARY--STATIONARY
35197,2021-05-13 05:24:06,2021-05-13,05:24:06,1084.25,1163.32,6.39,0.0,140.81,0.0,0.0,0.0,0.0,0.0,NO DATA,STATIONARY,STATIONARY,NO DATA--STATIONARY--STATIONARY
35198,2021-05-13 05:24:11,2021-05-13,05:24:11,1084.25,1163.32,6.39,0.0,140.81,0.0,0.0,0.0,0.0,0.0,NO DATA,STATIONARY,STATIONARY,NO DATA--STATIONARY--STATIONARY
35199,2021-05-13 05:24:16,2021-05-13,05:24:16,1084.25,1163.32,6.39,0.0,140.88,0.0,0.0,0.0,0.0,0.0,NO DATA,STATIONARY,STATIONARY,NO DATA--STATIONARY--STATIONARY
35200,2021-05-13 05:24:21,2021-05-13,05:24:21,1084.25,1163.32,6.39,0.0,141.07,0.0,0.0,0.0,0.0,0.0,NO DATA,STATIONARY,STATIONARY,NO DATA--STATIONARY--STATIONARY

In [34]:
Duration_DB = pd.DataFrame(
    columns=[
        'date',
        'Time_start',
        'Time_end',
        'date_time',
        'Duration(minutes)',
        'Hole Depth(max)',
        'Bit Depth(mean)',
        "Meterage(m)(Drilling)",
        'RotateDrilling',
        'Slide Drilling',
        'ReamingTime',
        'ConnectionTime',
        'On Bottom Hours',
        'Stand Duration',
        "LABEL_ConnectionActivity", 'LABEL_SubActivity', "LABEL_Activity"
        ]
    )

for k,DF_Temp in RealTime_DB.groupby((RealTime_DB['LABEL_All'].shift() != RealTime_DB['LABEL_All']).cumsum()):

    if not(("Hole_Depth" in locals()) or ("Hole_Depth" in globals())):
        Hole_Depth = 0

    list_temp = []

    date = DF_Temp.head(1)['date'].values[0]
    Time_start = DF_Temp.head(1)['time'].values[0]
    Time_end = DF_Temp.tail(1)['time'].values[0]
    date_time = DF_Temp.head(1)['dt'].values[0]
    LABEL_ConnectionActivity = DF_Temp.head(1)['LABEL_ConnectionActivity'].values[0]
    LABEL_SubActivity = DF_Temp.head(1)['LABEL_SubActivity'].values[0]
    LABEL_Activity = DF_Temp.head(1)['LABEL_Activity'].values[0]

    Duration = round(((DF_Temp['dt'].max()-DF_Temp['dt'].min()).total_seconds())/60,2)
    Hole_Depth_Temp = DF_Temp['md'].max()

    if Hole_Depth_Temp>= Hole_Depth:
        Hole_Depth = Hole_Depth_Temp
    
    # Bit_Depth = DF_Temp['md'].max()
    Bit_Depth = DF_Temp['bitdepth'].mean()
    # date = DF_Temp.head(1)['t'].values
    list_Out = [date, Time_start,Time_end, date_time, Duration, Hole_Depth, Bit_Depth, "", "", "", "", "", "", "",LABEL_ConnectionActivity, LABEL_SubActivity, LABEL_Activity]
    Duration_DB.loc[len(Duration_DB)] = list_Out
    
    # if k >20:
    #     break
Duration_DB

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127

,date,Time_start,Time_end,date_time,Duration(minutes),Hole Depth(max),Bit Depth(mean),Meterage(m)(Drilling),RotateDrilling,Slide Drilling,ReamingTime,ConnectionTime,On Bottom Hours,Stand Duration,LABEL_ConnectionActivity,LABEL_SubActivity,LABEL_Activity
0,2021-05-11,03:10:03,09:30:00,2021-05-11 03:10:03,379.95,343.85,0.000000,,,,,,,,NO DATA,WAIT ON CEMENT,WAIT ON CEMENT
1,2021-05-11,09:30:05,16:10:00,2021-05-11 09:30:05,399.92,343.85,0.405436,,,,,,,,NO DATA,OTHER,OTHER
2,2021-05-11,16:10:05,18:20:57,2021-05-11 16:10:05,130.87,343.85,16.891414,,,,,,,,NO DATA,MAKE UP BHA,MAKE UP BHA
3,2021-05-11,18:21:02,18:26:07,2021-05-11 18:21:02,5.08,343.85,33.460645,,,,,,,,NO DATA,MOVING,TRIP IN
4,2021-05-11,18:26:12,18:51:52,2021-05-11 18:26:12,25.67,343.85,41.699676,,,,,,,,NO DATA,CONNECTION,TRIP IN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,2021-05-13,04:28:31,04:33:36,2021-05-13 04:28:31,5.08,1163.32,1131.346935,,,,,,,,NO DATA,MOVING,TRIP OUT
123,2021-05-13,04:33:41,04:43:41,2021-05-13 04:33:41,10.00,1163.32,1116.291736,,,,,,,,NO DATA,CONNECTION,TRIP OUT
124,2021-05-13,04:43:46,04:55:51,2021-05-13 04:43:46,12.08,1163.32,1100.023836,,,,,,,,NO DATA,MOVING,TRIP OUT
125,2021-05-13,04:55:56,05:03:31,2021-05-13 04:55:56,7.58,1163.32,1088.289130,,,,,,,,NO DATA,CONNECTION,TRIP OUT
126,2021-05-13,05:03:36,05:24:21,2021-05-13 05:03:36,20.75,1163.32,1085.171600,,,,,,,,NO DATA,STATIONARY,STATIONARY

0       2021-05-11 03:10:03
1       2021-05-11 03:10:08
2       2021-05-11 03:10:13
3       2021-05-11 03:10:18
4       2021-05-11 03:10:23
                ...
35196   2021-05-13 05:24:01
35197   2021-05-13 05:24:06
35198   2021-05-13 05:24:11
35199   2021-05-13 05:24:16
35200   2021-05-13 05:24:21
Name: dt, Length: 35201, dtype: datetime64[ns]

## Test Function

In [37]:

def GenerateDuration_DF(RealTime_DB):
    RealTime_DB['dt'] = pd.to_datetime(RealTime_DB['dt'])
    RealTime_DB["LABEL_All"] =RealTime_DB['LABEL_ConnectionActivity'].astype(str) + '--' +RealTime_DB['LABEL_SubActivity']+'--'+RealTime_DB['LABEL_Activity']

    Duration_DB = pd.DataFrame(
        columns=[
            'date',
            'Time_start',
            'Time_end',
            'date_time',
            'Duration(minutes)',
            'Hole Depth(max)',
            'Bit Depth(mean)',
            "Meterage(m)(Drilling)",
            'RotateDrilling',
            'Slide Drilling',
            'ReamingTime',
            'ConnectionTime',
            'On Bottom Hours',
            'Stand Duration',
            "LABEL_ConnectionActivity", 'LABEL_SubActivity', "LABEL_Activity"
            ]
        )

    for k,DF_Temp in RealTime_DB.groupby((RealTime_DB['LABEL_All'].shift() != RealTime_DB['LABEL_All']).cumsum()):

        if (("Hole_Depth" in locals()) or ("Hole_Depth" in globals())):
            Hole_Depth = 0

        list_temp = []

        date = DF_Temp.head(1)['date'].values[0]
        Time_start = DF_Temp.head(1)['time'].values[0]
        Time_end = DF_Temp.tail(1)['time'].values[0]
        date_time = DF_Temp.head(1)['dt'].values[0]
        LABEL_ConnectionActivity = DF_Temp.head(1)['LABEL_ConnectionActivity'].values[0]
        LABEL_SubActivity = DF_Temp.head(1)['LABEL_SubActivity'].values[0]
        LABEL_Activity = DF_Temp.head(1)['LABEL_Activity'].values[0]

        Duration = round(((DF_Temp['dt'].max()-DF_Temp['dt'].min()).total_seconds())/60,2)
        Hole_Depth_Temp = DF_Temp['md'].max()

        if Hole_Depth_Temp>= Hole_Depth:
            Hole_Depth = Hole_Depth_Temp
        

        Bit_Depth = DF_Temp['bitdepth'].mean()

        list_Out = [date, Time_start,Time_end, date_time, Duration, Hole_Depth, Bit_Depth, "", "", "", "", "", "", "",LABEL_ConnectionActivity, LABEL_SubActivity, LABEL_Activity]
        Duration_DB.loc[len(Duration_DB)] = list_Out

        
    # SubActivityOutput.loc[SubActivityOutput['SubActivity'] == 'Rotary Drilling', 'RotateDrilling'] = SubActivityOutput.loc[SubActivityOutput['SubActivity'] == 'Rotary Drilling', 'Duration']
    # SubActivityOutput.loc[SubActivityOutput['SubActivity'] == 'Slide Drilling', 'Slide Drilling'] = SubActivityOutput.loc[SubActivityOutput['SubActivity'] == 'Slide Drilling', 'Duration']
    # SubActivityOutput.loc[SubActivityOutput['SubActivity'] == 'Reaming', 'ReamingTime'] = SubActivityOutput.loc[SubActivityOutput['SubActivity'] == 'Reaming', 'Duration']
    # SubActivityOutput.loc[SubActivityOutput['SubActivity'] == 'Connection', 'ConnectionTime'] = SubActivityOutput.loc[SubActivityOutput['SubActivity'] == 'Connection', 'Duration']
    return Duration_DB

In [38]:
fileRealtime = "RealTime_Test\\AAE-03_RealtimeSimulation.csv"

RealTime_DBx = pd.read_csv(fileRealtime)
Out = GenerateDuration_DF(RealTime_DBx)

# New Function

In [24]:
import numpy as np 
# import matplotlib.pyplot as plt 
import pandas as pd 
pd.set_option("display.max_rows", 100)

In [25]:
MasterReport_DF = pd.read_excel('Data\\Master_Report\\MasterReportTest.xlsx')
MasterReport_DF

,Date,Time,Date/Time,Duration,Hole Depth,Bit Depth,Meterage (m) (Drilling),Rotate Drilling Time (hrs),Slide Drilling Time (hrs),Reaming Time (hrs),Connection Time (hrs),On Bottom Hours,Stand Duration (hrs),Stand Group,Connection Activity,Sub Activity,Activity
0,44614,0.291678,44614.291678,8.333333e-01,1109.33,1109.33,,,,0.000579,,NaN,NaN,NaN,NaN,Reaming,Drilling Formation
1,44614,0.292257,44614.292257,2.416667e+01,1124.00,1124.00,14.67,0.016782,,,,NaN,NaN,NaN,NaN,Rotary Drilling,Drilling Formation
2,44614,0.309039,44614.309039,1.575000e+01,1124.01,1124.01,,,,0.010938,,NaN,NaN,NaN,NaN,Reaming,Drilling Formation
3,44614,0.319977,44614.319977,4.710000e+01,1132.00,1131.64,7.99,0.032708,,,,NaN,NaN,NaN,NaN,Rotary Drilling,Drilling Formation
4,44614,0.352685,44614.352685,5.085000e+01,1132.01,1108.53,,,,0.035312,,NaN,NaN,NaN,NaN,Reaming,Drilling Formation
5,44614,0.387998,44614.387998,5.166667e+00,1132.01,1108.67,,,,,0.003588,NaN,NaN,NaN,NaN,Connection,Drilling Formation
6,44614,0.391586,44614.391586,5.128333e+01,1132.01,1108.91,,,,,,NaN,NaN,NaN,NaN,Stationary,Drilling Formation
7,44614,0.427199,44614.427199,6.368333e+01,1132.01,1108.91,,,,,0.044225,NaN,NaN,NaN,NaN,Connection,Drilling Formation
8,44614,0.471424,44614.471424,5.083333e+00,1132.43,1132.43,,,,0.00353,,NaN,NaN,1.0,NaN,Reaming,Drilling Formation
9,44614,0.474954,44614.474954,4.923333e+01,1138.42,1138.28,5.99,0.03419,,,,NaN,NaN,1.0,NaN,Rotary Drilling,Drilling Formation
10,44614,0.509144,44614.509144,1.175000e+01,1138.42,1138.35,,,,0.00816,,NaN,NaN,1.0,Pre Connection,Reaming,Drilling Formation
11,44614,0.517303,44614.517303,1.916667e+00,1138.42,1138.35,6,,,,0.001331,0.034190,0.047211,1.0,Connection,Connection,Drilling Formation
12,44614,0.518634,44614.518634,6.833333e+00,1138.42,1138.42,,,,0.004745,,NaN,NaN,2.0,Post Connection,Reaming,Drilling Formation
13,44614,0.523380,44614.523380,4.791667e+01,1145.78,1144.93,7.36,0.033275,,,,NaN,NaN,2.0,NaN,Rotary Drilling,Drilling Formation
14,44614,0.556655,44614.556655,1.091667e+01,1145.92,1145.92,,,,0.007581,,NaN,NaN,2.0,NaN,Reaming,Drilling Formation
15,44614,0.564236,44614.564236,1.315167e+02,1168.22,1168.08,22.3,0.091331,,,,NaN,NaN,2.0,NaN,Rotary Drilling,Drilling Formation
16,44614,0.655567,44614.655567,2.341667e+01,1168.22,1168.10,,,,0.016262,,NaN,NaN,2.0,Pre Connection,Reaming,Drilling Formation
17,44614,0.671829,44614.671829,3.500000e+00,1168.22,1167.74,29.66,,,,0.002431,0.124606,0.155625,2.0,Connection,Connection,Drilling Formation
18,44614,0.674259,44614.674259,2.583333e+00,1168.26,1168.26,,,,0.001794,,NaN,NaN,3.0,Post Connection,Reaming,Drilling Formation
19,44614,0.676053,44614.676053,1.275667e+02,1198.03,1197.83,29.77,0.088588,,,,NaN,NaN,3.0,NaN,Rotary Drilling,Drilling Formation
20,44614,0.764641,44614.764641,1.808333e+01,1198.03,1197.88,,,,0.012558,,NaN,NaN,3.0,Pre Connection,Reaming,Drilling Formation
21,44614,0.777199,44614.777199,3.083333e+00,1198.03,1197.38,29.77,,,,0.002141,0.088588,0.105081,3.0,Connection,Connection,Drilling Formation
22,44614,0.779340,44614.779340,6.916667e+00,1198.03,1198.03,,,,0.004803,,NaN,NaN,4.0,Post Connection,Reaming,Drilling Formation
23,44614,0.784144,44614.784144,1.296667e+02,1227.64,1226.77,29.61,0.090046,,,,NaN,NaN,4.0,NaN,Rotary Drilling,Drilling Formation
24,44614,0.874190,44614.874190,2.516667e+01,1227.64,1224.35,,,,0.017477,,NaN,NaN,4.0,Pre Connection,Reaming,Drilling Formation
25,44614,0.891667,44614.891667,2.916667e+00,1227.64,1227.01,29.61,,,,0.002025,0.090046,0.114352,4.0,Connection,Connection,Drilling Formation
26,44614,0.893692,44614.893692,1.941667e+01,1227.64,1227.64,,,,0.013484,,NaN,NaN,5.0,Post Connection,Reaming,Drilling Formation
27,44614,0.907176,44614.907176,1.691667e+01,1230.48,1230.14,2.84,0.011748,,,,NaN,NaN,5.0,NaN,Rotary Drilling,Drilling Formation
28,44614,0.918924,44614.918924,7.500000e-01,1230.49,1230.49,,,,0.000521,,NaN,NaN,5.0,NaN,Reaming,Drilling Formation
29,44614,0.919444,44614.919444,1.473333e+02,1257.24,1257.24,26.75,0.102315,,,,NaN,NaN,5.0,NaN,Rotary Drilling,Drilling Formation
30,44615,0.021759,44615.021759,2.558333e+01,1257.24,1257.24,,,,0.017766,,NaN,NaN,5.0,Pre Connection,Reaming,Drilling Formation
31,44615,0.039525,44615.039525,2.833333e+00,1257.24,1257.24,29.59,NaN,,NaN,0.001968,0.114063,0.147801,5.0,Connection,Connection,Drilling Formation
32,44615,0.041493,44615.041493,1.258333e+01,1257.24,1257.24,,,,0.008738,,NaN,NaN,6.0,Post Connection,Reaming,Drilling Formation
33,44615,0.050231,44615.050231,1.485000e+01,1258.29,1257.91,1.05,0.010313,,,,NaN,NaN,6.0,NaN,Rotary Drilling,Drilling Formation
34,44615,0.060544,44615.060544,6.666667e-01,1258.30,1258.30,,,,0.000463,,NaN,NaN,6.0,NaN,Reaming,Drilling Formation
35,44615,0.061007,44615.061007,2.064000e+02,1286.74,1286.72,28.44,0.143333,,,,NaN,NaN,6.0,NaN,Rotary Drilling,Drilling Formation
36,44615,0.204340,44615.204340,1.650000e+01,1286.74,1282.35,,,,0.011458,,NaN,NaN,6.0,NaN,Reaming,Drilling Formation
37,44615,0.215799,44615.215799,2.500000e+00,1286.74,1286.48,,,,,,NaN,NaN,6.0,Pre Connection,Wash Up/Down,Drilling Formation
38,44615,0.217535,44615.217535,2.916667e+00,1286.74,1285.90,29.49,,,,0.002025,0.153646,0.176331,6.0,Connection,Connection,Drilling Formation
39,44615,0.219560,44615.219560,3.916667e+00,1286.74,1285.90,,,,,,NaN,NaN,7.0,Post Connection,Wash Up/Down,Drilling Formation
40,44615,0.222280,44615.222280,1.166667e+00,1286.76,1286.76,,,,0.00081,,NaN,NaN,7.0,NaN,Reaming,Drilling Formation
41,44615,0.223090,44615.223090,2.833333e+00,1287.09,1286.84,0.33,0.001968,,,,NaN,NaN,7.0,NaN,Rotary Drilling,Drilling Formation
42,44615,0.225058,44615.225058,3.416667e+00,1287.09,1287.08,,,,0.002373,,NaN,NaN,7.0,NaN,Reaming,Drilling Formation
43,44615,0.227431,44615.227431,1.583333e+01,1289.01,1288.53,1.92,0.010995,,,,NaN,NaN,7.0,NaN,Rotary Drilling,Drilling Formation
44,44615,0.238426,44615.238426,6.666667e-01,1289.01,1286.20,,,,0.000463,,NaN,NaN,7.0,NaN,Reaming,Drilling Formation
45,44615,0.238889,44615.238889,1.300000e+01,1289.09,1289.09,,,,,,NaN,NaN,7.0,NaN,Wash Up/Down,Drilling Formation
46,44615,0.247917,44615.247917,5.406667e+01,1296.00,1295.67,6.91,,0.037546,,,NaN,NaN,7.0,NaN,Slide Drilling,Drilling Formation
47,44615,0.285463,44615.285463,2.666667e+00,1296.00,1294.70,,,,,,NaN,NaN,7.0,NaN,Wash Up/Down,Drilling Formation
48,44615,0.287315,44615.287315,2.750000e+00,1296.01,1296.01,,,,0.00191,,NaN,NaN,7.0,NaN,Reaming,Drilling Formation
49,44615,0.289225,44615.289225,1.251667e+02,1316.30,1316.12,20.29,0.086921,,,,NaN,NaN,7.0,NaN,Rotary Drilling,Drilling Formation
50,44615,0.376146,44615.376146,2.200000e+01,1316.30,1309.68,,,,0.015278,,NaN,NaN,7.0,NaN,Reaming,Drilling Formation
51,44615,0.391424,44615.391424,6.916667e+00,1316.30,1316.03,,,,,,NaN,NaN,7.0,Pre Connection,Wash Up/Down,Drilling Formation
52,44615,0.396227,44615.396227,6.000000e+00,1316.30,1315.65,29.45,,,,0.004167,0.137431,0.162431,7.0,Connection,Connection,Drilling Formation
53,44615,0.400394,44615.400394,6.666667e+00,1316.27,1316.27,,,,0.00463,,NaN,NaN,8.0,Post Connection,Reaming,Drilling Formation
54,44615,0.405023,44615.405023,4.616667e+01,1322.79,1322.24,6.52,0.03206,,,,NaN,NaN,8.0,NaN,Rotary Drilling,Drilling Formation
55,44615,0.437083,44615.437083,3.083333e+00,1322.79,1322.79,,,,0.002141,,NaN,NaN,8.0,NaN,Reaming,Drilling Formation
56,44615,0.439225,44615.439225,2.441667e+01,1326.44,1316.58,3.65,0.016956,,,,NaN,NaN,8.0,NaN,Rotary Drilling,Drilling Formation
57,44615,0.456181,44615.456181,5.666667e+00,1326.44,1326.44,,,,0.003935,,NaN,NaN,8.0,NaN,Reaming,Drilling Formation
58,44615,0.460116,44615.460116,4.666667e+00,1327.28,1325.25,0.84,0.003241,,,,NaN,NaN,8.0,NaN,Rotary Drilling,Drilling Formation
59,44615,0.463356,44615.463356,6.166667e+00,1327.29,1327.29,,,,0.004282,,NaN,NaN,8.0,NaN,Reaming,Drilling Formation
60,44615,0.467639,44615.467639,1.035833e+02,1345.79,1345.57,18.5,0.071933,,,,NaN,NaN,8.0,NaN,Rotary Drilling,Drilling Formation
61,44615,0.539572,44615.539572,1.383333e+01,1345.79,1342.70,,,,0.009606,,NaN,NaN,8.0,NaN,Reaming,Drilling Formation
62,44615,0.549178,44615.549178,7.500000e-01,1345.79,1345.72,,,,,,NaN,NaN,8.0,Pre Connection,Wash Up/Down,Drilling Formation
63,44615,0.549699,44615.549699,4.166667e+00,1345.79,1345.01,29.51,,,,0.002894,0.124190,0.151678,8.0,Connection,Connection,Drilling Formation
64,44615,0.552593,44615.552593,3.166667e+00,1345.78,1345.78,,,,0.002199,,NaN,NaN,9.0,Post Connection,Reaming,Drilling Formation
65,44615,0.554792,44615.554792,1.436833e+02,1366.33,1365.96,20.55,0.09978,,,,NaN,NaN,9.0,NaN,Rotary Drilling,Drilling Formation
66,44615,0.654572,44615.654572,8.833333e+00,1366.33,1366.33,,,,0.006134,,NaN,NaN,9.0,NaN,Reaming,Drilling Formation
67,44615,0.660706,44615.660706,5.650000e+01,1375.07,1374.70,8.74,0.039236,,,,NaN,NaN,9.0,NaN,Rotary Drilling,Drilling Formation
68,44615,0.699942,44615.699942,1.441667e+01,1375.07,1372.74,,,,0.010012,,NaN,NaN,9.0,NaN,Reaming,Drilling Formation
69,44615,0.709954,44615.709954,1.583333e+00,1375.07,1374.85,,,,,,NaN,NaN,9.0,Pre Connection,Wash Up/Down,Drilling Formation
70,44615,0.711053,44615.711053,2.083333e+00,1375.07,1374.66,29.29,,,,0.001447,0.139016,0.158808,9.0,Connection,Connection,Drilling Formation
71,44615,0.712500,44615.712500,2.166667e+00,1375.07,1374.38,,,,,,NaN,NaN,10.0,Post Connection,Wash Up/Down,Drilling Formation
72,44615,0.714005,44615.714005,2.333333e+00,1375.07,1375.07,,,,0.00162,,NaN,NaN,10.0,NaN,Reaming,Drilling Formation
73,44615,0.715625,44615.715625,2.333333e+01,1378.00,1376.40,2.93,0.016204,,,,NaN,NaN,10.0,NaN,Rotary Drilling,Drilling Formation
74,44615,0.731829,44615.731829,4.250000e+00,1378.00,1378.00,,,,,,NaN,NaN,10.0,NaN,Wash Up/Down,Drilling Formation
75,44615,0.734780,44615.734780,5.325000e+01,1386.14,1385.76,8.14,,0.036979,,,NaN,NaN,10.0,NaN,Slide Drilling,Drilling Formation
76,44615,0.771759,44615.771759,2.583333e+00,1386.14,1376.28,,,,,,NaN,NaN,10.0,NaN,Wash Up/Down,Drilling Formation
77,44615,0.773553,44615.773553,4.916667e+00,1386.14,1386.14,,,,0.003414,,NaN,NaN,10.0,NaN,Reaming,Drilling Formation
78,44615,0.776968,44615.776968,1.271000e+02,1404.59,1404.01,18.45,0.088264,,,,NaN,NaN,10.0,NaN,Rotary Drilling,Drilling Formation
79,44615,0.865231,44615.865231,1.283333e+01,1404.59,1403.37,,,,0.008912,,NaN,NaN,10.0,NaN,Reaming,Drilling Formation
80,44615,0.874144,44615.874144,5.083333e+00,1404.59,1403.22,,,,,,NaN,NaN,10.0,NaN,Wash Up/Down,Drilling Formation
81,44615,0.877674,44615.877674,5.991667e+01,1404.59,1376.32,,,,0.041609,,NaN,NaN,10.0,NaN,Reaming,Drilling Formation
82,44615,0.919282,44615.919282,2.583333e+00,1404.59,1374.43,,,,,,NaN,NaN,10.0,Pre Connection,Wash Up/Down,Drilling Formation
83,44615,0.921076,44615.921076,5.016667e+00,1404.59,1373.38,29.52,,,,0.003484,0.141447,0.200486,10.0,Connection,Connection,Drilling Formation
84,44615,0.924560,44615.924560,-6.424693e+07,NaN,NaN,,,,,,NaN,NaN,NaN,Post Connection,Moving,Drilling Formation

In [27]:
MasterReport_DF[(MasterReport_DF['Sub Activity']=='Connection') & (MasterReport_DF['Sub Activity'].shift(periods=-1)=='Reaming')]

,Date,Time,Date/Time,Duration,Hole Depth,Bit Depth,Meterage (m) (Drilling),Rotate Drilling Time (hrs),Slide Drilling Time (hrs),Reaming Time (hrs),Connection Time (hrs),On Bottom Hours,Stand Duration (hrs),Stand Group,Connection Activity,Sub Activity,Activity
7,44614,0.427199,44614.427199,63.683333,1132.01,1108.91,,,,,0.044225,NaN,NaN,NaN,NaN,Connection,Drilling Formation
11,44614,0.517303,44614.517303,1.916667,1138.42,1138.35,6,,,,0.001331,0.034190,0.047211,1.0,Connection,Connection,Drilling Formation
17,44614,0.671829,44614.671829,3.500000,1168.22,1167.74,29.66,,,,0.002431,0.124606,0.155625,2.0,Connection,Connection,Drilling Formation
21,44614,0.777199,44614.777199,3.083333,1198.03,1197.38,29.77,,,,0.002141,0.088588,0.105081,3.0,Connection,Connection,Drilling Formation
25,44614,0.891667,44614.891667,2.916667,1227.64,1227.01,29.61,,,,0.002025,0.090046,0.114352,4.0,Connection,Connection,Drilling Formation
31,44615,0.039525,44615.039525,2.833333,1257.24,1257.24,29.59,NaN,,NaN,0.001968,0.114063,0.147801,5.0,Connection,Connection,Drilling Formation
52,44615,0.396227,44615.396227,6.000000,1316.30,1315.65,29.45,,,,0.004167,0.137431,0.162431,7.0,Connection,Connection,Drilling Formation
63,44615,0.549699,44615.549699,4.166667,1345.79,1345.01,29.51,,,,0.002894,0.124190,0.151678,8.0,Connection,Connection,Drilling Formation

In [61]:
MasterReport_DF = pd.read_excel('Data\\Master_Report\\MasterReportTest.xlsx')
# print(MasterReport_DF.dtypes)
MasterReport_DF['Stand Meterage (m) (Drilling)'] = np.NaN
MasterReport_DF['Stand Stand Duration (hrs)'] = np.NaN
MasterReport_DF['Stand On Bottom Hours'] = np.NaN
MasterReport_DF = MasterReport_DF.astype(
        {
            'Duration':'float',
            'Hole Depth':'float',
            'Bit Depth':'float',
            "Meterage (m) (Drilling)":'float',
            "Stand Meterage (m) (Drilling)":'float',
            "Rotate Drilling Time (hrs)":'float',
            'Slide Drilling Time (hrs)':'float',
            'Reaming Time (hrs)':'float',
            'Connection Time (hrs)':'float',
            'On Bottom Hours':'float',
            'Stand On Bottom Hours':'float',
            'Stand Duration (hrs)':'float',
            'Stand Stand Duration (hrs)':'float',

        }
)
MasterReport_DF = MasterReport_DF.reset_index(drop=True).fillna(0)
# MasterReport_DF['Stand Meterage (m) (Drilling)'] = ""
ii = 0
for idx,row in MasterReport_DF[(MasterReport_DF['Sub Activity']=='Connection')].iterrows():
    print(idx)
    if ii==0:

        idx_start = idx + 1

    else:
        idx_end = idx - 1
    
        MasterReport_DF.loc[idx_start:idx_end, 'Stand Group_Pred'] = 'Stand Group - ' + str(ii)


        OnBottomHours =  MasterReport_DF.loc[idx_start:idx_end, 'Rotate Drilling Time (hrs)'].sum() + MasterReport_DF.loc[idx_start:idx_end, 'Slide Drilling Time (hrs)'].sum()
        StandDuration =  MasterReport_DF.loc[idx_start:idx_end+1, 'Duration'].sum()
        StandMeterageDrilling = MasterReport_DF.loc[idx_start:idx_end, 'Meterage (m) (Drilling)'].sum()


        MasterReport_DF.loc[idx, 'Stand On Bottom Hours'] = OnBottomHours
        MasterReport_DF.loc[idx, 'Stand Stand Duration (hrs)'] = StandDuration
        MasterReport_DF.loc[idx, "Stand Meterage (m) (Drilling)"] = StandMeterageDrilling

        print(str(idx_start) + " - " + str(idx_end))
        idx_start = idx + 1

    ii = ii + 1

MasterReport_DF.head(10)

5
7
6 - 6
11
8 - 10
17
12 - 16
21
18 - 20
25
22 - 24
31
26 - 30
38
32 - 37
52
39 - 51
63
53 - 62
70
64 - 69
83
71 - 82

,Date,Time,Date/Time,Duration,Hole Depth,Bit Depth,Meterage (m) (Drilling),Rotate Drilling Time (hrs),Slide Drilling Time (hrs),Reaming Time (hrs),...,On Bottom Hours,Stand Duration (hrs),Stand Group,Connection Activity,Sub Activity,Activity,Stand Meterage (m) (Drilling),Stand Stand Duration (hrs),Stand On Bottom Hours,Stand Group_Pred
0,44614,0.291678,44614.291678,0.833333,1109.33,1109.33,0.00,0.000000,0.0,0.000579,...,0.0,0.0,0.0,0,Reaming,Drilling Formation,0.0,0.000000,0.0,NaN
1,44614,0.292257,44614.292257,24.166667,1124.00,1124.00,14.67,0.016782,0.0,0.000000,...,0.0,0.0,0.0,0,Rotary Drilling,Drilling Formation,0.0,0.000000,0.0,NaN
2,44614,0.309039,44614.309039,15.750000,1124.01,1124.01,0.00,0.000000,0.0,0.010938,...,0.0,0.0,0.0,0,Reaming,Drilling Formation,0.0,0.000000,0.0,NaN
3,44614,0.319977,44614.319977,47.100000,1132.00,1131.64,7.99,0.032708,0.0,0.000000,...,0.0,0.0,0.0,0,Rotary Drilling,Drilling Formation,0.0,0.000000,0.0,NaN
4,44614,0.352685,44614.352685,50.850000,1132.01,1108.53,0.00,0.000000,0.0,0.035312,...,0.0,0.0,0.0,0,Reaming,Drilling Formation,0.0,0.000000,0.0,NaN
5,44614,0.387998,44614.387998,5.166667,1132.01,1108.67,0.00,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0,Connection,Drilling Formation,0.0,0.000000,0.0,NaN
6,44614,0.391586,44614.391586,51.283333,1132.01,1108.91,0.00,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0,Stationary,Drilling Formation,0.0,0.000000,0.0,Stand Group - 1
7,44614,0.427199,44614.427199,63.683333,1132.01,1108.91,0.00,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0,Connection,Drilling Formation,0.0,114.966667,0.0,NaN
8,44614,0.471424,44614.471424,5.083333,1132.43,1132.43,0.00,0.000000,0.0,0.003530,...,0.0,0.0,1.0,0,Reaming,Drilling Formation,0.0,0.000000,0.0,Stand Group - 2
9,44614,0.474954,44614.474954,49.233333,1138.42,1138.28,5.99,0.034190,0.0,0.000000,...,0.0,0.0,1.0,0,Rotary Drilling,Drilling Formation,0.0,0.000000,0.0,Stand Group - 2

In [23]:
MasterReport_DF[(MasterReport_DF['Sub Activity']=='Connection') & (MasterReport_DF['Sub Activity'].shift(periods=1)=='Reaming')]

,Date,Time,Date/Time,Duration,Hole Depth,Bit Depth,Meterage (m) (Drilling),Rotate Drilling Time (hrs),Slide Drilling Time (hrs),Reaming Time (hrs),Connection Time (hrs),On Bottom Hours,Stand Duration (hrs),Stand Group,Connection Activity,Sub Activity,Activity,Stand Group_Pred
5,44614,0.387998,44614.387998,5.166667,1132.01,1108.67,,,,,0.003588,NaN,NaN,NaN,NaN,Connection,Drilling Formation,Stand Group1
11,44614,0.517303,44614.517303,1.916667,1138.42,1138.35,6,,,,0.001331,0.034190,0.047211,1.0,Connection,Connection,Drilling Formation,Stand Group3
17,44614,0.671829,44614.671829,3.500000,1168.22,1167.74,29.66,,,,0.002431,0.124606,0.155625,2.0,Connection,Connection,Drilling Formation,Stand Group4
21,44614,0.777199,44614.777199,3.083333,1198.03,1197.38,29.77,,,,0.002141,0.088588,0.105081,3.0,Connection,Connection,Drilling Formation,Stand Group5
25,44614,0.891667,44614.891667,2.916667,1227.64,1227.01,29.61,,,,0.002025,0.090046,0.114352,4.0,Connection,Connection,Drilling Formation,Stand Group6
31,44615,0.039525,44615.039525,2.833333,1257.24,1257.24,29.59,NaN,,NaN,0.001968,0.114063,0.147801,5.0,Connection,Connection,Drilling Formation,Stand Group7

In [116]:
MasterReport_DF_Web = pd.read_csv("Data\\Master_Report\\KS ORKA_SMP AAE-08_ActivitySummary.csv", index_col=0)
MasterReport_DF_Web['MERGE_SubActivity-Activity'] = MasterReport_DF_Web['LABEL_Activity'] + "--"+MasterReport_DF_Web['LABEL_SubActivity']
MasterReport_DF_Web

,date,Time_start,Time_end,date_time,Duration(minutes),Hole Depth(max),Bit Depth(mean),Meterage(m)(Drilling),RotateDrilling,Slide Drilling,ReamingTime,ConnectionTime,On Bottom Hours,Stand Duration,LABEL_SubActivity,LABEL_Activity,MERGE_SubActivity-Activity
0,2022-02-14,00:00:00,11:59:58,2022-02-14 00:00:00,719.97,718.02,640.80,0.00,0.00,0.0,0.00,0.0,0.0,0.0,FALSE/Check,NaN,NaN
1,2022-02-14,12:00:03,14:59:56,2022-02-14 12:00:03,179.88,747.38,732.21,0.00,0.00,0.0,0.00,0.0,0.0,0.0,MAKE UP BHA,MAKE UP BHA,MAKE UP BHA--MAKE UP BHA
2,2022-02-14,15:00:01,15:09:06,2022-02-14 15:00:01,9.08,749.55,748.48,0.00,0.00,0.0,0.00,0.0,0.0,0.0,Wash Up/Down,TRIP IN,TRIP IN--Wash Up/Down
3,2022-02-14,15:09:11,15:09:11,2022-02-14 15:09:11,0.00,749.57,749.57,0.00,0.00,0.0,0.00,0.0,0.0,0.0,Circulation,TRIP IN,TRIP IN--Circulation
4,2022-02-14,15:09:16,15:09:16,2022-02-14 15:09:16,0.00,749.57,749.57,0.00,0.00,0.0,0.00,0.0,0.0,0.0,FALSE/Check,TRIP IN,TRIP IN--FALSE/Check
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,2022-02-14,23:03:01,23:06:56,2022-02-14 23:03:01,3.92,839.77,839.53,0.51,3.92,0.0,0.00,0.0,0.0,0.0,Rotary Drilling,DRILLING FORMATION,DRILLING FORMATION--Rotary Drilling
190,2022-02-14,23:07:01,23:08:01,2022-02-14 23:07:01,1.00,839.77,835.00,0.00,0.00,0.0,1.00,0.0,0.0,0.0,Reaming,DRILLING FORMATION,DRILLING FORMATION--Reaming
191,2022-02-14,23:08:06,23:08:41,2022-02-14 23:08:06,0.58,839.77,833.14,0.00,0.00,0.0,0.00,0.0,0.0,0.0,FALSE/Check,DRILLING FORMATION,DRILLING FORMATION--FALSE/Check
192,2022-02-14,23:08:46,23:12:26,2022-02-14 23:08:46,3.67,839.77,834.20,0.00,0.00,0.0,3.67,0.0,0.0,0.0,Reaming,DRILLING FORMATION,DRILLING FORMATION--Reaming
193,2022-02-14,23:12:31,23:59:56,2022-02-14 23:12:31,47.42,853.04,846.13,13.27,47.42,0.0,0.00,0.0,0.0,0.0,Rotary Drilling,DRILLING FORMATION,DRILLING FORMATION--Rotary Drilling

In [110]:



for idx, row in MasterReport_DF_Web[MasterReport_DF_Web['LABEL_SubActivity'].isin(["Look and define", "FALSE/Check"])].iterrows():
    if idx > 0:
        if MasterReport_DF_Web.loc[idx-1, 'LABEL_SubActivity'] == MasterReport_DF_Web.loc[idx+1, 'LABEL_SubActivity']:
            MasterReport_DF_Web.loc[idx, 'LABEL_SubActivity'] = MasterReport_DF_Web.loc[idx-1, 'LABEL_SubActivity']

In [125]:
pd.set_option("display.max_rows", 100)
idx_same = MasterReport_DF_Web.index[MasterReport_DF_Web['LABEL_SubActivity'].isin(["Look and define", "FALSE/Check"])]
idx_before = idx_same - 1
idx_same = idx_same[idx_before>0]
idx_before = idx_before[idx_before>0]

MasterReport_DF_Web.loc[idx_same, 'LABEL_SubActivity'] = MasterReport_DF_Web.loc[idx_before, 'LABEL_SubActivity'].values
MasterReport_DF_Web['MERGE_SubActivity-Activity'] = MasterReport_DF_Web['LABEL_Activity'] + "--"+MasterReport_DF_Web['LABEL_SubActivity']
MasterReport_DF_Web

Int64Index([182], dtype='int64')
Int64Index([181], dtype='int64')

,date,Time_start,Time_end,date_time,Duration(minutes),Hole Depth(max),Bit Depth(mean),Meterage(m)(Drilling),RotateDrilling,Slide Drilling,ReamingTime,ConnectionTime,On Bottom Hours,Stand Duration,LABEL_SubActivity,LABEL_Activity,MERGE_SubActivity-Activity
0,2022-02-14,00:00:00,11:59:58,2022-02-14 00:00:00,719.97,718.02,640.80,0.00,0.00,0.0,0.00,0.0,0.0,0.0,FALSE/Check,NaN,NaN
1,2022-02-14,12:00:03,14:59:56,2022-02-14 12:00:03,179.88,747.38,732.21,0.00,0.00,0.0,0.00,0.0,0.0,0.0,MAKE UP BHA,MAKE UP BHA,MAKE UP BHA--MAKE UP BHA
2,2022-02-14,15:00:01,15:09:06,2022-02-14 15:00:01,9.08,749.55,748.48,0.00,0.00,0.0,0.00,0.0,0.0,0.0,Wash Up/Down,TRIP IN,TRIP IN--Wash Up/Down
3,2022-02-14,15:09:11,15:09:11,2022-02-14 15:09:11,0.00,749.57,749.57,0.00,0.00,0.0,0.00,0.0,0.0,0.0,Circulation,TRIP IN,TRIP IN--Circulation
4,2022-02-14,15:09:16,15:09:16,2022-02-14 15:09:16,0.00,749.57,749.57,0.00,0.00,0.0,0.00,0.0,0.0,0.0,Circulation,TRIP IN,TRIP IN--Circulation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,2022-02-14,23:03:01,23:06:56,2022-02-14 23:03:01,3.92,839.77,839.53,0.51,3.92,0.0,0.00,0.0,0.0,0.0,Rotary Drilling,DRILLING FORMATION,DRILLING FORMATION--Rotary Drilling
190,2022-02-14,23:07:01,23:08:01,2022-02-14 23:07:01,1.00,839.77,835.00,0.00,0.00,0.0,1.00,0.0,0.0,0.0,Reaming,DRILLING FORMATION,DRILLING FORMATION--Reaming
191,2022-02-14,23:08:06,23:08:41,2022-02-14 23:08:06,0.58,839.77,833.14,0.00,0.00,0.0,0.00,0.0,0.0,0.0,Reaming,DRILLING FORMATION,DRILLING FORMATION--Reaming
192,2022-02-14,23:08:46,23:12:26,2022-02-14 23:08:46,3.67,839.77,834.20,0.00,0.00,0.0,3.67,0.0,0.0,0.0,Reaming,DRILLING FORMATION,DRILLING FORMATION--Reaming
193,2022-02-14,23:12:31,23:59:56,2022-02-14 23:12:31,47.42,853.04,846.13,13.27,47.42,0.0,0.00,0.0,0.0,0.0,Rotary Drilling,DRILLING FORMATION,DRILLING FORMATION--Rotary Drilling

In [133]:
MasterReport_DF_Web.groupby((MasterReport_DF_Web['MERGE_SubActivity-Activity'].shift() != MasterReport_DF_Web['MERGE_SubActivity-Activity']).cumsum(), as_index=False).agg(
    {
        'date':'max',
        'Time_start':'min',
        'Time_end':'max',
        'date_time':'min',
        'Duration(minutes)':'sum',
        'Hole Depth(max)':'max',
        'Bit Depth(mean)': 'mean',
        
        'Meterage(m)(Drilling)':'sum',
        'RotateDrilling':'sum',
        'Slide Drilling':'sum',
        'ReamingTime':'sum',
        'ConnectionTime':'sum',
        'On Bottom Hours':'sum',
        'Stand Duration':'sum',
        'LABEL_SubActivity':'first',
        'LABEL_Activity':'first',
        'MERGE_SubActivity-Activity':'first'
    }
)

,date,Time_start,Time_end,date_time,Duration(minutes),Hole Depth(max),Bit Depth(mean),Meterage(m)(Drilling),RotateDrilling,Slide Drilling,ReamingTime,ConnectionTime,On Bottom Hours,Stand Duration,LABEL_SubActivity,LABEL_Activity,MERGE_SubActivity-Activity
0,2022-02-14,00:00:00,11:59:58,2022-02-14 00:00:00,719.97,718.02,640.800000,0.00,0.00,0.0,0.00,0.0,0.0,0.0,FALSE/Check,None,None
1,2022-02-14,12:00:03,14:59:56,2022-02-14 12:00:03,179.88,747.38,732.210000,0.00,0.00,0.0,0.00,0.0,0.0,0.0,MAKE UP BHA,MAKE UP BHA,MAKE UP BHA--MAKE UP BHA
2,2022-02-14,15:00:01,15:09:06,2022-02-14 15:00:01,9.08,749.55,748.480000,0.00,0.00,0.0,0.00,0.0,0.0,0.0,Wash Up/Down,TRIP IN,TRIP IN--Wash Up/Down
3,2022-02-14,15:09:11,15:09:16,2022-02-14 15:09:11,0.00,749.57,749.570000,0.00,0.00,0.0,0.00,0.0,0.0,0.0,Circulation,TRIP IN,TRIP IN--Circulation
4,2022-02-14,15:09:21,15:09:31,2022-02-14 15:09:21,0.17,749.61,749.600000,0.00,0.00,0.0,0.00,0.0,0.0,0.0,Wash Up/Down,TRIP IN,TRIP IN--Wash Up/Down
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,2022-02-14,22:28:01,22:28:06,2022-02-14 22:28:01,0.08,833.44,833.040000,0.00,0.00,0.0,0.08,0.0,0.0,0.0,Reaming,CIRCULATE HOLE CLEANING,CIRCULATE HOLE CLEANING--Reaming
153,2022-02-14,22:28:11,23:02:56,2022-02-14 22:28:11,34.75,839.24,836.270000,5.80,34.75,0.0,0.00,0.0,0.0,0.0,Rotary Drilling,CIRCULATE HOLE CLEANING,CIRCULATE HOLE CLEANING--Rotary Drilling
154,2022-02-14,23:03:01,23:06:56,2022-02-14 23:03:01,3.92,839.77,839.530000,0.51,3.92,0.0,0.00,0.0,0.0,0.0,Rotary Drilling,DRILLING FORMATION,DRILLING FORMATION--Rotary Drilling
155,2022-02-14,23:07:01,23:12:26,2022-02-14 23:07:01,5.25,839.77,834.113333,0.00,0.00,0.0,4.67,0.0,0.0,0.0,Reaming,DRILLING FORMATION,DRILLING FORMATION--Reaming
156,2022-02-14,23:12:31,23:59:56,2022-02-14 23:12:31,47.42,853.04,846.130000,13.27,47.42,0.0,0.00,0.0,0.0,0.0,Rotary Drilling,DRILLING FORMATION,DRILLING FORMATION--Rotary Drilling

In [128]:
for i in MasterReport_DF_Web.columns:
    print(i)

date
Time_start
Time_end
date_time
Duration(minutes)
Hole Depth(max)
Bit Depth(mean)
Meterage(m)(Drilling)
RotateDrilling
Slide Drilling
ReamingTime
ConnectionTime
On Bottom Hours
Stand Duration
LABEL_SubActivity
LABEL_Activity
MERGE_SubActivity-Activity

In [185]:
def cleanFalseSensor(MasterReport_DF_Web):
    MasterReport_DF_Web = MasterReport_DF_Web.reset_index(drop=True)
    # while ("FALSE/Check" in MasterReport_DF_Web['LABEL_SubActivity'].values) or ("Look and define" in MasterReport_DF_Web['LABEL_SubActivity'].values):
    idx_same = MasterReport_DF_Web.index[MasterReport_DF_Web['LABEL_SubActivity']=="Look and define"]
    idx_before = idx_same - 1

    idx_same = idx_same[idx_before>0]
    idx_before = idx_before[idx_before>0]
    
    MasterReport_DF_Web.loc[idx_same, 'LABEL_SubActivity'] = MasterReport_DF_Web.loc[idx_before, 'LABEL_SubActivity'].values
    MasterReport_DF_Web['MERGE_SubActivity-Activity'] = MasterReport_DF_Web['LABEL_Activity'] + "--"+MasterReport_DF_Web['LABEL_SubActivity']

    idx_same = MasterReport_DF_Web.index[MasterReport_DF_Web['LABEL_SubActivity']=="FALSE/Check"]
    # print(idx_same)
    idx_before = idx_same - 1

    idx_same = idx_same[idx_before>0]
    # print(idx_same)
    idx_before = idx_before[idx_before>0]
    # print(idx_before)
    
    MasterReport_DF_Web.loc[idx_same, 'LABEL_SubActivity'] = MasterReport_DF_Web.loc[idx_before, 'LABEL_SubActivity'].values
    MasterReport_DF_Web['MERGE_SubActivity-Activity'] = MasterReport_DF_Web['LABEL_Activity'] + "--"+MasterReport_DF_Web['LABEL_SubActivity']


    idx_same = MasterReport_DF_Web.index[MasterReport_DF_Web['LABEL_SubActivity']=="FALSE/Check"]
    idx_before = idx_same - 1

    idx_same = idx_same[idx_before>0]
    idx_before = idx_before[idx_before>0]
    
    MasterReport_DF_Web.loc[idx_same, 'LABEL_SubActivity'] = MasterReport_DF_Web.loc[idx_before, 'LABEL_SubActivity'].values
    MasterReport_DF_Web['MERGE_SubActivity-Activity'] = MasterReport_DF_Web['LABEL_Activity'] + "--"+MasterReport_DF_Web['LABEL_SubActivity']

    idx_same = MasterReport_DF_Web.index[MasterReport_DF_Web['LABEL_SubActivity']=="Look and define"]
    # print(idx_same)
    idx_before = idx_same - 1

    idx_same = idx_same[idx_before>0]
    # print(idx_same)
    idx_before = idx_before[idx_before>0]
    # print(idx_before)
    
    MasterReport_DF_Web.loc[idx_same, 'LABEL_SubActivity'] = MasterReport_DF_Web.loc[idx_before, 'LABEL_SubActivity'].values
    MasterReport_DF_Web['MERGE_SubActivity-Activity'] = MasterReport_DF_Web['LABEL_Activity'] + "--"+MasterReport_DF_Web['LABEL_SubActivity']


    MasterReport_DF_Web = MasterReport_DF_Web.groupby((MasterReport_DF_Web['MERGE_SubActivity-Activity'].shift() != MasterReport_DF_Web['MERGE_SubActivity-Activity']).cumsum(), as_index=False).agg(
        {
            'date':'max',
            'Time_start':'min',
            'Time_end':'max',
            'date_time':'min',
            'Duration(minutes)':'sum',
            'Hole Depth(max)':'max',
            'Bit Depth(mean)': 'mean',

            'Meterage(m)(Drilling)':'sum',
            'RotateDrilling':'sum',
            'Slide Drilling':'sum',
            'ReamingTime':'sum',
            'ConnectionTime':'sum',
            'On Bottom Hours':'sum',
            'Stand Duration':'sum',
            'LABEL_SubActivity':'first',
            'LABEL_Activity':'first',
            'MERGE_SubActivity-Activity':'first'
        }
    )
    # list_col = [
    #         # 'Meterage(m)(Drilling)',
    #         'RotateDrilling',
    #         'Slide Drilling',
    #         'ReamingTime',
    #         # 'ConnectionTime',
    #         # 'On Bottom Hours',
    #         # 'Stand Duration'
    # ]
    # for ColName in list_col:
    idx_temp = MasterReport_DF_Web['LABEL_SubActivity']=='RotateDrilling'
    MasterReport_DF_Web.loc[idx_temp,'RotateDrilling'] = MasterReport_DF_Web.loc[idx_temp,'Duration(minutes)'].values 

    idx_temp = MasterReport_DF_Web['LABEL_SubActivity']=='Slide Drilling'
    MasterReport_DF_Web.loc[idx_temp,'Slide Drilling'] = MasterReport_DF_Web.loc[idx_temp,'Duration(minutes)'].values 

    idx_temp = MasterReport_DF_Web['LABEL_SubActivity']=='ReamingTime'
    MasterReport_DF_Web.loc[idx_temp,'ReamingTime'] = MasterReport_DF_Web.loc[idx_temp,'Duration(minutes)'].values 

    return MasterReport_DF_Web

def labelStand(MasterReport_DF):
    # date
    # Time_start
    # Time_end
    # date_time
    # Duration(minutes)
    # Hole Depth(max)
    # Bit Depth(mean)
    # Meterage(m)(Drilling)
    # RotateDrilling
    # Slide Drilling
    # ReamingTime
    # ConnectionTime
    # On Bottom Hours
    # Stand Duration
    # LABEL_SubActivity
    # LABEL_Activity
    # MasterReport_DF = pd.read_excel('Data\\Master_Report\\MasterReportTest.xlsx')
    # print(MasterReport_DF.dtypes)
    MasterReport_DF['Stand Meterage (m) (Drilling)'] = np.NaN
    MasterReport_DF['Stand Stand Duration (hrs)'] = np.NaN
    MasterReport_DF['Stand On Bottom Hours'] = np.NaN
    MasterReport_DF = MasterReport_DF.astype(
            {
                'Duration(minutes)':'float',
                'Hole Depth(max)':'float',
                'Bit Depth(mean)':'float',
                "Meterage(m)(Drilling)":'float',
                "Stand Meterage (m) (Drilling)":'float',
                "RotateDrilling":'float',
                'Slide Drilling':'float',
                'ReamingTime':'float',
                'ConnectionTime':'float',
                'On Bottom Hours':'float',
                'Stand On Bottom Hours':'float',
                'Stand Duration':'float',
                'Stand Stand Duration (hrs)':'float',

            }
    )
    MasterReport_DF = MasterReport_DF.reset_index(drop=True).fillna(0)

    ii = 0
    for idx,row in MasterReport_DF[(MasterReport_DF['LABEL_SubActivity']=='Connection')].iterrows():
        # print(idx)
        if ii==0:

            idx_start = idx + 1

        else:
            idx_end = idx - 1
        
            MasterReport_DF.loc[idx_start:idx_end, 'Stand Group_Pred'] = 'Stand Group - ' + str(ii)


            OnBottomHours =  MasterReport_DF.loc[idx_start:idx_end, 'RotateDrilling'].sum() + MasterReport_DF.loc[idx_start:idx_end, 'Slide Drilling'].sum()
            StandDuration =  MasterReport_DF.loc[idx_start:idx_end+1, 'Duration(minutes)'].sum()
            StandMeterageDrilling = MasterReport_DF.loc[idx_start:idx_end, 'Meterage(m)(Drilling)'].sum()


            MasterReport_DF.loc[idx, 'Stand On Bottom Hours'] = OnBottomHours
            MasterReport_DF.loc[idx, 'Stand Stand Duration (hrs)'] = StandDuration
            MasterReport_DF.loc[idx, "Stand Meterage (m) (Drilling)"] = StandMeterageDrilling

            # print(str(idx_start) + " - " + str(idx_end))
            idx_start = idx + 1

        ii = ii + 1
    return MasterReport_DF

In [186]:
MasterReport_DF = pd.read_excel('Data\\Master_Report\\MasterReportTest.xlsx')
# for i in MasterReport_DF.columns:
#     print(i)

# print('=======  WEB   ===========')



MasterReport_DF_Web = pd.read_csv("Data\\Master_Report\\KS ORKA_SMP AAE-08_ActivitySummary.csv", index_col=0)
MasterReport_DF_Web_out = labelStand(cleanFalseSensor((MasterReport_DF_Web)))
MasterReport_DF_Web_out.to_excel("Data\\Master_Report\\output_finalxxx.xlsx")
# for i in MasterReport_DF_Web:
#     print(i)

In [1]:
import plotly.express as px
df = px.data.tips()
fig = px.sunburst(df, path=['day', 'time', 'sex'], values='total_bill')
fig.show()

In [6]:
df.dtypes

total_bill    float64
tip           float64
sex            object
smoker         object
day            object
time           object
size            int64
dtype: object

In [3]:
import pandas as pd
data_load = pd.read_csv("C:\\Users\\irsya\\Downloads\\KS ORKA_SMP AAE-08_ActivitySummary.csv")
data_load

,date,Time_start,Time_end,date_time,Duration(minutes),Hole Depth(max),Bit Depth(mean),Meterage(m)(Drilling),RotateDrilling,Slide Drilling,...,ConnectionTime,On Bottom Hours,Stand Duration,LABEL_SubActivity,LABEL_Activity,MERGE_SubActivity-Activity,Stand Meterage (m) (Drilling),Stand Stand Duration (hrs),Stand On Bottom Hours,Stand Group_Pred
0,2022-02-14 00:00:00,00:00:00,11:59:58,2022-02-14 00:00:00,719.97,718.02,640.80,0.00,0.00,0.00,...,0.0,0.0,0.0,FALSE/Check,NaN,nan--FALSE/Check,0.0,0.0,0.0,NaN
1,2022-02-14 00:00:00,12:00:03,14:59:56,2022-02-14 12:00:03,179.88,747.38,732.21,0.00,0.00,0.00,...,0.0,0.0,0.0,MAKE UP BHA,MAKE UP BHA,MAKE UP BHA--MAKE UP BHA,0.0,0.0,0.0,NaN
2,2022-02-14 00:00:00,15:00:01,15:09:06,2022-02-14 15:00:01,9.08,749.55,748.48,0.00,0.00,0.00,...,0.0,0.0,0.0,Wash Up/Down,TRIP IN,TRIP IN--Wash Up/Down,0.0,0.0,0.0,NaN
3,2022-02-14 00:00:00,15:09:11,15:09:16,2022-02-14 15:09:11,0.00,749.57,749.57,0.00,0.00,0.00,...,0.0,0.0,0.0,Circulation,TRIP IN,TRIP IN--Circulation,0.0,0.0,0.0,NaN
4,2022-02-14 00:00:00,15:09:21,15:09:31,2022-02-14 15:09:21,0.17,749.61,749.60,0.00,0.00,0.00,...,0.0,0.0,0.0,Wash Up/Down,TRIP IN,TRIP IN--Wash Up/Down,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,2022-02-15 00:00:00,23:27:27,23:30:57,2022-02-15 23:27:27,3.50,1080.00,1072.10,0.00,0.00,0.00,...,0.0,0.0,0.0,Wash Up/Down,DRILLING FORMATION,DRILLING FORMATION--Wash Up/Down,0.0,0.0,0.0,NaN
358,2022-02-15 00:00:00,23:31:02,23:45:42,2022-02-15 23:31:02,14.67,1082.00,1081.08,2.00,0.00,14.67,...,0.0,0.0,0.0,Slide Drilling,DRILLING FORMATION,DRILLING FORMATION--Slide Drilling,0.0,0.0,0.0,NaN
359,2022-02-15 00:00:00,23:45:47,23:46:47,2022-02-15 23:45:47,0.91,1082.00,1080.79,0.00,0.00,0.00,...,0.0,0.0,0.0,Wash Up/Down,DRILLING FORMATION,DRILLING FORMATION--Wash Up/Down,0.0,0.0,0.0,NaN
360,2022-02-15 00:00:00,23:46:52,23:48:17,2022-02-15 23:46:52,1.42,1082.00,1081.28,0.00,0.00,0.00,...,0.0,0.0,0.0,Reaming,DRILLING FORMATION,DRILLING FORMATION--Reaming,0.0,0.0,0.0,NaN
361,2022-02-15 00:00:00,23:48:22,23:59:57,2022-02-15 23:48:22,11.58,1084.19,1083.03,2.19,11.58,0.00,...,0.0,0.0,0.0,Rotary Drilling,DRILLING FORMATION,DRILLING FORMATION--Rotary Drilling,0.0,0.0,0.0,NaN

In [31]:
def build_hierarchical_dataframe(df, levels, value_column, color_columns=None):
    """
    Build a hierarchy of levels for Sunburst or Treemap charts.

    Levels are given starting from the bottom to the top of the hierarchy,
    ie the last level corresponds to the root.
    """
    df_all_trees = pd.DataFrame(columns=['id', 'parent', 'value', 'color'])
    for i, level in enumerate(levels):
        df_tree = pd.DataFrame(columns=['id', 'parent', 'value', 'color'])
        dfg = df.groupby(levels[i:]).sum()
        dfg = dfg.reset_index()
        df_tree['id'] = dfg[level].copy()
        if i < len(levels) - 1:
            df_tree['parent'] = dfg[levels[i+1]].copy()
        else:
            df_tree['parent'] = 'total'
        df_tree['value'] = dfg[value_column]
        df_tree['color'] = dfg[color_columns[0]] / dfg[color_columns[1]]
        df_all_trees = df_all_trees.append(df_tree, ignore_index=True)
    total = pd.Series(dict(id='total', parent='',
                              value=df[value_column].sum(),
                              color=df[color_columns[0]].sum() / df[color_columns[1]].sum()))
    ))
    df_all_trees = df_all_trees.append(total, ignore_index=True)
    return df_all_trees

# build_hierarchical_dataframe(df, levels, value_column)

In [41]:
import plotly.graph_objects as go
PieChart_DF = data_load.groupby(['LABEL_SubActivity', 'LABEL_Activity']).sum().reset_index()
PieChart_DF = PieChart_DF[['LABEL_SubActivity', 'LABEL_Activity', 'Duration(minutes)']]

fig = px.sunburst(PieChart_DF, path=['LABEL_SubActivity', 'LABEL_Activity'], values='Duration(minutes)')
# fig.update_layout(uniformtext=dict(minsize=10, mode='hide'))
fig.show()

In [81]:
data_load = pd.read_csv("C:\\Users\\irsya\\Downloads\\KS ORKA_SMP AAE-08_ActivitySummary.csv")

ConnectionTime_DF = data_load.groupby(['Stand Group_Pred']).agg({
    'date_time':'first', 
    'RotateDrilling':'sum', 
    'Slide Drilling':'sum',
    'ReamingTime':'sum',
    'ConnectionTime':'sum',
}).reset_index()

# ConnectionTime_DF_Plot = pd.DataFrame(columns=['date_time', 'Stand Group_Pred', 'Duration', 'Labels'])

# for i,j in enumerate(['RotateDrilling', 'Slide Drilling','ReamingTime','ConnectionTime']):
#     if i ==0:
#         ConnectionTime_DF_Plot_temp = pd.DataFrame(columns=['date_time', 'Stand Group_Pred', 'Duration', 'Labels'])
#         ConnectionTime_DF_Plot_temp['date_time'] = ConnectionTime_DF['date_time']
#         ConnectionTime_DF_Plot_temp['Stand Group_Pred'] = ConnectionTime_DF['Stand Group_Pred']
#         ConnectionTime_DF_Plot_temp['Duration'] = ConnectionTime_DF[j]
#         ConnectionTime_DF_Plot_temp['Labels'] = j
#         # ConnectionTime_DF_Plot = pd.concat(ConnectionTime_DF_Plot, ConnectionTime_DF_Plot_temp)
#         ConnectionTime_DF_Plot = pd.concat([ConnectionTime_DF_Plot, ConnectionTime_DF_Plot_temp])
#     else:
#         ConnectionTime_DF_Plot_temp = pd.DataFrame(columns=['date_time', 'Stand Group_Pred', 'Duration', 'Labels'])
#         ConnectionTime_DF_Plot_temp['date_time'] = ConnectionTime_DF['date_time']
#         ConnectionTime_DF_Plot_temp['Stand Group_Pred'] = ConnectionTime_DF['Stand Group_Pred']
#         ConnectionTime_DF_Plot_temp['Duration'] = ConnectionTime_DF[j]
#         ConnectionTime_DF_Plot_temp['Labels'] = j
#         ConnectionTime_DF_Plot = pd.concat([ConnectionTime_DF_Plot, ConnectionTime_DF_Plot_temp])

# ConnectionTime_DF_Plot = ConnectionTime_DF_Plot.sort_values('date_time')


        
ConnectionTime_DF = ConnectionTime_DF[ConnectionTime_DF['RotateDrilling'] != 0]
fig = px.bar(ConnectionTime_DF, x='date_time', y=['RotateDrilling', 'Slide Drilling','ReamingTime','ConnectionTime'], width=1000, height=1000
             )
fig.show()

In [105]:
data_load = pd.read_csv("C:\\Users\\irsya\\Downloads\\KS ORKA_SMP AAE-08_ActivitySummary.csv")


data_load['Stand Group_Pred_Shift'] = data_load['Stand Group_Pred'].shift(1)
data_load = data_load[data_load['LABEL_SubActivity']=='Connection']
data_load = data_load.dropna(subset=['Stand Group_Pred_Shift'])
data_load = data_load[data_load['Stand Meterage (m) (Drilling)']!=0]
data_load['ROP'] = data_load['Stand Meterage (m) (Drilling)'] / (data_load['Stand On Bottom Hours']/60)
data_load['OBH'] = (data_load['Stand On Bottom Hours']/60)


df = px.data.tips()
fig = px.bar(data_load, x="date_time", y=['ROP','OBH'] ,
              barmode='group',
             height=400)
fig.show()

In [92]:
data_load

,date,Time_start,Time_end,date_time,Duration(minutes),Hole Depth(max),Bit Depth(mean),Meterage(m)(Drilling),RotateDrilling,Slide Drilling,...,ConnectionTime,On Bottom Hours,Stand Duration,LABEL_SubActivity,LABEL_Activity,MERGE_SubActivity-Activity,Stand Meterage (m) (Drilling),Stand Stand Duration (hrs),Stand On Bottom Hours,Stand Group_Pred
0,2022-02-14 00:00:00,00:00:00,11:59:58,2022-02-14 00:00:00,719.97,718.02,640.80,0.00,0.00,0.00,...,0.0,0.0,0.0,FALSE/Check,NaN,nan--FALSE/Check,0.0,0.0,0.0,NaN
1,2022-02-14 00:00:00,12:00:03,14:59:56,2022-02-14 12:00:03,179.88,747.38,732.21,0.00,0.00,0.00,...,0.0,0.0,0.0,MAKE UP BHA,MAKE UP BHA,MAKE UP BHA--MAKE UP BHA,0.0,0.0,0.0,NaN
2,2022-02-14 00:00:00,15:00:01,15:09:06,2022-02-14 15:00:01,9.08,749.55,748.48,0.00,0.00,0.00,...,0.0,0.0,0.0,Wash Up/Down,TRIP IN,TRIP IN--Wash Up/Down,0.0,0.0,0.0,NaN
3,2022-02-14 00:00:00,15:09:11,15:09:16,2022-02-14 15:09:11,0.00,749.57,749.57,0.00,0.00,0.00,...,0.0,0.0,0.0,Circulation,TRIP IN,TRIP IN--Circulation,0.0,0.0,0.0,NaN
4,2022-02-14 00:00:00,15:09:21,15:09:31,2022-02-14 15:09:21,0.17,749.61,749.60,0.00,0.00,0.00,...,0.0,0.0,0.0,Wash Up/Down,TRIP IN,TRIP IN--Wash Up/Down,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,2022-02-15 00:00:00,23:27:27,23:30:57,2022-02-15 23:27:27,3.50,1080.00,1072.10,0.00,0.00,0.00,...,0.0,0.0,0.0,Wash Up/Down,DRILLING FORMATION,DRILLING FORMATION--Wash Up/Down,0.0,0.0,0.0,NaN
358,2022-02-15 00:00:00,23:31:02,23:45:42,2022-02-15 23:31:02,14.67,1082.00,1081.08,2.00,0.00,14.67,...,0.0,0.0,0.0,Slide Drilling,DRILLING FORMATION,DRILLING FORMATION--Slide Drilling,0.0,0.0,0.0,NaN
359,2022-02-15 00:00:00,23:45:47,23:46:47,2022-02-15 23:45:47,0.91,1082.00,1080.79,0.00,0.00,0.00,...,0.0,0.0,0.0,Wash Up/Down,DRILLING FORMATION,DRILLING FORMATION--Wash Up/Down,0.0,0.0,0.0,NaN
360,2022-02-15 00:00:00,23:46:52,23:48:17,2022-02-15 23:46:52,1.42,1082.00,1081.28,0.00,0.00,0.00,...,0.0,0.0,0.0,Reaming,DRILLING FORMATION,DRILLING FORMATION--Reaming,0.0,0.0,0.0,NaN
361,2022-02-15 00:00:00,23:48:22,23:59:57,2022-02-15 23:48:22,11.58,1084.19,1083.03,2.19,11.58,0.00,...,0.0,0.0,0.0,Rotary Drilling,DRILLING FORMATION,DRILLING FORMATION--Rotary Drilling,0.0,0.0,0.0,NaN

## redesign duration function to support recalculation feature after user override.

In [52]:
import pandas as pd 
import numpy as np 
from Streamlit_App import IO_Data, Activity
import datetime

def str2datetime(strdate):
    return tuple([int(x) for x in strdate[:10].split('-')])+tuple([int(x) for x in strdate[11:].split(':')])

def cache_RealTime_Data(well_id, StartDateTime_select, EndDateTime_select):
    Activity_DF = IO_Data.getActivityData(well_id, StartDateTime_select, EndDateTime_select)
    
    Activity_DF['dt'] = Activity_DF['dt'].astype('datetime64')
    Activity_DF['bitdepth'] = Activity_DF['bitdepth'].astype('float64')
    Activity_DF['blockpos'] = Activity_DF['blockpos'].astype('float64')
    Activity_DF['rop'] = Activity_DF['rop'].astype('float64')
    Activity_DF['hklda'] = Activity_DF['hklda'].astype('float64')
    Activity_DF['woba'] = Activity_DF['woba'].astype('float64')
    Activity_DF['torqa'] = Activity_DF['torqa'].astype('float64')
    Activity_DF['rpm'] = Activity_DF['rpm'].astype('float64')
    Activity_DF['stppress'] = Activity_DF['stppress'].astype('float64')
    Activity_DF['mudflowin'] = Activity_DF['mudflowin'].astype('float64')

    return Activity_DF

Well_ID = 170
StartDateTime_select = "2022-02-14 00:00:00"
StartDateTime_select = datetime.datetime(*(str2datetime(StartDateTime_select)))

# "2022-02-15 00:00:00"
EndDateTime_select = "2022-02-15 00:00:00"
EndDateTime_select = datetime.datetime(*(str2datetime(EndDateTime_select)))

out_Realtime_5s = cache_RealTime_Data(Well_ID, StartDateTime_select, EndDateTime_select)
# datetime(StartDateTime_select)
out_Realtime_5s

{'wid': 170, 'start': '2022-02-14 00:00:00', 'end': '2022-02-15 00:00:00'}

,dt,date,time,bitdepth,md,blockpos,rop,hklda,woba,torqa,rpm,stppress,mudflowin
0,2022-02-14 00:00:00,2022-02-14,00:00:00,573.99,573.99,23.62,15.52,104.63,14.44,4.81,45.0,2046.38,1099.33
1,2022-02-14 00:00:05,2022-02-14,00:00:05,574.01,574.01,23.60,14.88,103.20,15.87,4.95,45.0,2055.58,1099.33
2,2022-02-14 00:00:10,2022-02-14,00:00:10,574.03,574.03,23.58,14.88,103.76,15.31,4.89,45.0,2056.69,1099.33
3,2022-02-14 00:00:15,2022-02-14,00:00:15,574.05,574.05,23.56,14.88,103.81,15.26,4.89,45.0,2053.74,1099.33
4,2022-02-14 00:00:20,2022-02-14,00:00:20,574.06,574.06,23.55,14.88,103.05,16.02,4.94,45.0,2059.64,1099.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17175,2022-02-14 23:59:36,2022-02-14,23:59:36,852.94,852.94,10.94,16.98,113.43,25.18,9.31,52.0,2271.78,1086.82
17176,2022-02-14 23:59:41,2022-02-14,23:59:41,852.96,852.96,10.92,16.98,114.99,23.62,8.99,52.0,2263.19,1090.50
17177,2022-02-14 23:59:46,2022-02-14,23:59:46,852.98,852.98,10.90,16.98,116.94,21.67,8.74,52.0,2255.83,1089.77
17178,2022-02-14 23:59:51,2022-02-14,23:59:51,853.01,853.01,10.87,19.05,117.87,20.74,8.48,52.0,2251.84,1091.24
17179,2022-02-14 23:59:56,2022-02-14,23:59:56,853.04,853.04,10.84,19.46,118.56,20.05,8.33,52.0,2248.78,1090.50

In [51]:
InputActivityLog_date_start = "2022-01-26 00:00:00"
InputActivityLog_date_end = "2022-04-01 00:00:00"
Well_ID_API = Well_ID

InputActivity_DB = IO_Data.dict2DF(IO_Data.DomeGetData(Well_ID_API, InputActivityLog_date_start, InputActivityLog_date_end))
InputActivity_DB

,input_id,dt,date,time,activity,in_slip_threshold,remarks,pic,section
0,102,2022-02-14 12:00:00,2022-02-14,12:00:00,MAKE UP BHA,61,Test Data,BM,17 1/2
1,103,2022-02-14 15:00:00,2022-02-14,15:00:00,TRIP IN,61,Test Data,BM,17 1/2
2,104,2022-02-14 18:28:00,2022-02-14,18:28:12,DRILL OUT CEMENT,61,Test Data,BM,17 1/2
3,105,2022-02-14 23:03:00,2022-02-14,23:03:45,DRILLING FORMATION,61,Test Data,BM,17 1/2
4,106,2022-02-15 00:38:00,2022-02-15,00:38:51,CIRCULATE HOLE CLEANING,61,Test Data,BM,17 1/2
5,107,2022-02-15 02:13:00,2022-02-15,02:13:52,WIPER TRIP,61,Test Data,BM,17 1/2
6,108,2022-02-15 04:20:00,2022-02-15,04:20:12,DRILLING FORMATION,61,Test Data,BM,17 1/2
7,109,2022-02-16 05:36:00,2022-02-16,05:36:08,CIRCULATE HOLE CLEANING,61,Test Data,BM,17 1/2
8,110,2022-02-16 06:49:00,2022-02-16,06:49:34,WIPER TRIP,61,Test Data,BM,17 1/2
9,111,2022-02-16 08:55:00,2022-02-16,08:55:03,CIRCULATE HOLE CLEANING,61,Test Data,BM,17 1/2

In [53]:
from Streamlit_App import IO_Data, Activity

def InputTranslator(Input_DB):
    Input_DB['dt'] = (Input_DB['dt']).apply(lambda d: pd.to_datetime(str(d)))

    Input_DB.rename(columns = {'in_slip_threshold':'Hook Treshold', 'activity':'Activity'}, inplace = True)
    return Input_DB
 
 
Input_Temp = InputTranslator(InputActivity_DB)
Activity_DF_out = Activity.GetActivity_DF(out_Realtime_5s, Input_Temp)
Activity_DF_out = Activity.GetSubActivity_DF_v3(Activity_DF_out)
Activity_DF_out.columns
# Activity_DF_out

datetime64[ns]
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
2022-02-16 08:55:00

Index(['dt', 'date', 'time', 'bitdepth', 'md', 'blockpos', 'rop', 'hklda',
       'woba', 'torqa', 'rpm', 'stppress', 'mudflowin', 'Activity',
       'Hookload Treshold', 'SubActivity', 'logic_status', 'isBitDepthMoving'],
      dtype='object')

In [57]:
SummaryActivity_Out = Activity.labelStand(Activity.cleanFalseSensor((Activity.GenerateDuration_DF_v4(Activity_DF_out))))
SummaryActivity_Out

,date,Time_start,Time_end,date_time,Duration(minutes),Hole Depth(max),Bit Depth(mean),Meterage(m)(Drilling),RotateDrilling,Slide Drilling,...,ConnectionTime,On Bottom Hours,Stand Duration,LABEL_SubActivity,LABEL_Activity,MERGE_SubActivity-Activity,Stand Meterage (m) (Drilling),Stand Stand Duration (hrs),Stand On Bottom Hours,Stand Group_Pred
0,2022-02-14,00:00:00,12:00:03,2022-02-14 00:00:00,719.97,718.02,640.800000,0.00,0.00,0.0,...,0.0,0.0,0.0,FALSE/Check,nan,nan--FALSE/Check,0.0,0.0,0.0,NaN
1,2022-02-14,12:00:03,15:00:01,2022-02-14 12:00:03,179.88,747.38,732.210000,0.00,0.00,0.0,...,0.0,0.0,0.0,MAKE UP BHA,MAKE UP BHA,MAKE UP BHA--MAKE UP BHA,0.0,0.0,0.0,NaN
2,2022-02-14,15:00:01,15:09:11,2022-02-14 15:00:01,9.08,749.55,748.480000,0.00,0.00,0.0,...,0.0,0.0,0.0,Wash Up/Down,TRIP IN,TRIP IN--Wash Up/Down,0.0,0.0,0.0,NaN
3,2022-02-14,15:09:11,15:09:21,2022-02-14 15:09:11,0.00,749.57,749.570000,0.00,0.00,0.0,...,0.0,0.0,0.0,Circulation,TRIP IN,TRIP IN--Circulation,0.0,0.0,0.0,NaN
4,2022-02-14,15:09:21,15:09:36,2022-02-14 15:09:21,0.17,749.61,749.600000,0.00,0.00,0.0,...,0.0,0.0,0.0,Wash Up/Down,TRIP IN,TRIP IN--Wash Up/Down,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,2022-02-14,22:28:01,22:28:11,2022-02-14 22:28:01,0.08,833.44,833.040000,0.00,0.00,0.0,...,0.0,0.0,0.0,Reaming,DRILL OUT CEMENT,DRILL OUT CEMENT--Reaming,0.0,0.0,0.0,NaN
151,2022-02-14,22:28:11,23:03:01,2022-02-14 22:28:11,34.75,839.24,836.270000,5.80,34.75,0.0,...,0.0,0.0,0.0,Rotary Drilling,DRILL OUT CEMENT,DRILL OUT CEMENT--Rotary Drilling,0.0,0.0,0.0,NaN
152,2022-02-14,23:03:01,23:07:01,2022-02-14 23:03:01,3.92,839.77,839.530000,0.51,3.92,0.0,...,0.0,0.0,0.0,Rotary Drilling,DRILLING FORMATION,DRILLING FORMATION--Rotary Drilling,0.0,0.0,0.0,NaN
153,2022-02-14,23:07:01,23:12:31,2022-02-14 23:07:01,5.25,839.77,834.113333,0.00,0.00,0.0,...,0.0,0.0,0.0,Reaming,DRILLING FORMATION,DRILLING FORMATION--Reaming,0.0,0.0,0.0,NaN
154,2022-02-14,23:12:31,00:00:01,2022-02-14 23:12:31,47.42,853.04,846.130000,13.27,47.42,0.0,...,0.0,0.0,0.0,Rotary Drilling,DRILLING FORMATION,DRILLING FORMATION--Rotary Drilling,0.0,0.0,0.0,NaN

In [60]:
from Streamlit_App import IO_Data, Activity
from importlib import reload
# Change in mymodule
reload(Activity)


Activity.RecalculateActivity_DF(Activity_DF_out, SummaryActivity_Out)

KeyError: 'Hook Treshold'

In [75]:
import json
username = "Admin"
password = "Admin"

with open('Streamlit_App/UserPassList.json') as json_file:
    data = json.load(json_file)
Table_DF = pd.DataFrame(dict(data))
# print(not (Table_DF.loc[(Table_DF['1'] == username) & (Table_DF['2'] == password)]).empty)

True