In [1]:
import numpy as np 
import pandas as pd

In [2]:
realtimeraw_5s = pd.read_csv('MCG_IJN 2-1_RawREaltime5s.csv')
realtimeraw_5s['dt'] = pd.to_datetime(realtimeraw_5s['dt'], format='%Y-%m-%d %H:%M:%S')
realtimeraw_5s

,dt,date,time,bitdepth,md,blockpos,rop,hklda,woba,torqa,rpm,stppress,mudflowin
0,2023-04-09 00:00:05,2023-04-09,00:00:05,14.84,110.00,4.84,4.58,42.66,0.0,0.0,0.0,0.00,0.00
1,2023-04-09 00:00:10,2023-04-09,00:00:10,14.84,110.00,4.71,4.58,43.71,0.0,0.0,0.0,0.00,0.00
2,2023-04-09 00:00:15,2023-04-09,00:00:15,14.84,110.00,4.51,4.58,43.71,0.0,0.0,0.0,0.00,0.00
3,2023-04-09 00:00:20,2023-04-09,00:00:20,14.84,110.00,4.51,4.58,43.29,0.0,0.0,0.0,0.00,0.00
4,2023-04-09 00:00:25,2023-04-09,00:00:25,14.84,110.00,4.51,4.58,43.18,0.0,0.0,0.0,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33735,2023-04-10 23:58:36,2023-04-10,23:58:36,291.52,291.52,13.46,7.09,61.67,0.0,0.0,0.0,1835.67,944.24
33736,2023-04-10 23:58:41,2023-04-10,23:58:41,291.54,291.54,13.44,7.09,61.67,0.0,0.0,0.0,1832.52,944.24
33737,2023-04-10 23:58:46,2023-04-10,23:58:46,291.54,291.54,13.44,7.09,61.67,0.0,0.0,0.0,1829.14,944.24
33738,2023-04-10 23:58:51,2023-04-10,23:58:51,291.55,291.55,13.43,7.09,61.63,0.0,0.0,0.0,1824.23,944.24
33739,2023-04-10 23:58:56,2023-04-10,23:58:56,291.56,291.56,13.42,7.09,61.67,0.0,0.0,0.0,1821.47,944.24

In [3]:
realtimeraw_5s['dt_relative'] = (realtimeraw_5s['dt'] - realtimeraw_5s['dt'].min()).dt.total_seconds()
realtimeraw_5s

,dt,date,time,bitdepth,md,blockpos,rop,hklda,woba,torqa,rpm,stppress,mudflowin,dt_relative
0,2023-04-09 00:00:05,2023-04-09,00:00:05,14.84,110.00,4.84,4.58,42.66,0.0,0.0,0.0,0.00,0.00,0.0
1,2023-04-09 00:00:10,2023-04-09,00:00:10,14.84,110.00,4.71,4.58,43.71,0.0,0.0,0.0,0.00,0.00,5.0
2,2023-04-09 00:00:15,2023-04-09,00:00:15,14.84,110.00,4.51,4.58,43.71,0.0,0.0,0.0,0.00,0.00,10.0
3,2023-04-09 00:00:20,2023-04-09,00:00:20,14.84,110.00,4.51,4.58,43.29,0.0,0.0,0.0,0.00,0.00,15.0
4,2023-04-09 00:00:25,2023-04-09,00:00:25,14.84,110.00,4.51,4.58,43.18,0.0,0.0,0.0,0.00,0.00,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33735,2023-04-10 23:58:36,2023-04-10,23:58:36,291.52,291.52,13.46,7.09,61.67,0.0,0.0,0.0,1835.67,944.24,172711.0
33736,2023-04-10 23:58:41,2023-04-10,23:58:41,291.54,291.54,13.44,7.09,61.67,0.0,0.0,0.0,1832.52,944.24,172716.0
33737,2023-04-10 23:58:46,2023-04-10,23:58:46,291.54,291.54,13.44,7.09,61.67,0.0,0.0,0.0,1829.14,944.24,172721.0
33738,2023-04-10 23:58:51,2023-04-10,23:58:51,291.55,291.55,13.43,7.09,61.63,0.0,0.0,0.0,1824.23,944.24,172726.0
33739,2023-04-10 23:58:56,2023-04-10,23:58:56,291.56,291.56,13.42,7.09,61.67,0.0,0.0,0.0,1821.47,944.24,172731.0

In [4]:
finalRealtime = pd.DataFrame(
    {
        'dt':pd.date_range(start=realtimeraw_5s['dt'].min(), end=realtimeraw_5s['dt'].max(), freq='5S'),
    }
) 
finalRealtime['date'] = finalRealtime['dt'].dt.date
finalRealtime['time'] = finalRealtime['dt'].dt.time
finalRealtime['dt_relative'] = (finalRealtime['dt'] - finalRealtime['dt'].min()).dt.total_seconds()
finalRealtime

                       dt        date      time  dt_relative
0     2023-04-09 00:00:05  2023-04-09  00:00:05          0.0
1     2023-04-09 00:00:10  2023-04-09  00:00:10          5.0
2     2023-04-09 00:00:15  2023-04-09  00:00:15         10.0
3     2023-04-09 00:00:20  2023-04-09  00:00:20         15.0
4     2023-04-09 00:00:25  2023-04-09  00:00:25         20.0
...                   ...         ...       ...          ...
34542 2023-04-10 23:58:35  2023-04-10  23:58:35     172710.0
34543 2023-04-10 23:58:40  2023-04-10  23:58:40     172715.0
34544 2023-04-10 23:58:45  2023-04-10  23:58:45     172720.0
34545 2023-04-10 23:58:50  2023-04-10  23:58:50     172725.0
34546 2023-04-10 23:58:55  2023-04-10  23:58:55     172730.0

[34547 rows x 4 columns]

In [5]:
list_cols = ['bitdepth', 'md', 'blockpos', 'rop', 'hklda',
       'woba', 'torqa', 'rpm', 'stppress', 'mudflowin', 'dt_relative']
for cols in list_cols:
    finalRealtime[cols] = np.interp(finalRealtime['dt_relative'], realtimeraw_5s['dt_relative'].values, realtimeraw_5s[cols])

In [6]:
finalRealtime

,dt,date,time,dt_relative,bitdepth,md,blockpos,rop,hklda,woba,torqa,rpm,stppress,mudflowin
0,2023-04-09 00:00:05,2023-04-09,00:00:05,0.0,14.840,110.000,4.840,4.58,42.660,0.0,0.0,0.0,0.000,0.00
1,2023-04-09 00:00:10,2023-04-09,00:00:10,5.0,14.840,110.000,4.710,4.58,43.710,0.0,0.0,0.0,0.000,0.00
2,2023-04-09 00:00:15,2023-04-09,00:00:15,10.0,14.840,110.000,4.510,4.58,43.710,0.0,0.0,0.0,0.000,0.00
3,2023-04-09 00:00:20,2023-04-09,00:00:20,15.0,14.840,110.000,4.510,4.58,43.290,0.0,0.0,0.0,0.000,0.00
4,2023-04-09 00:00:25,2023-04-09,00:00:25,20.0,14.840,110.000,4.510,4.58,43.180,0.0,0.0,0.0,0.000,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34542,2023-04-10 23:58:35,2023-04-10,23:58:35,172710.0,291.520,291.520,13.460,7.09,61.670,0.0,0.0,0.0,1836.676,944.24
34543,2023-04-10 23:58:40,2023-04-10,23:58:40,172715.0,291.536,291.536,13.444,7.09,61.670,0.0,0.0,0.0,1833.150,944.24
34544,2023-04-10 23:58:45,2023-04-10,23:58:45,172720.0,291.540,291.540,13.440,7.09,61.670,0.0,0.0,0.0,1829.816,944.24
34545,2023-04-10 23:58:50,2023-04-10,23:58:50,172725.0,291.548,291.548,13.432,7.09,61.638,0.0,0.0,0.0,1825.212,944.24
34546,2023-04-10 23:58:55,2023-04-10,23:58:55,172730.0,291.558,291.558,13.422,7.09,61.662,0.0,0.0,0.0,1822.022,944.24

In [11]:
def interpolateRealtimeData(realtimeraw):
    realtimeraw['dt'] = pd.to_datetime(realtimeraw['dt'], format='%Y-%m-%d %H:%M:%S')
    realtimeraw['dt_relative'] = (realtimeraw['dt'] - realtimeraw['dt'].min()).dt.total_seconds()
    finalRealtime = pd.DataFrame(
    {
        'dt':pd.date_range(start=realtimeraw_5s['dt'].min(), end=realtimeraw_5s['dt'].max(), freq='5S'),
    }
    )
    finalRealtime['date'] = finalRealtime['dt'].dt.date
    finalRealtime['time'] = finalRealtime['dt'].dt.time
    finalRealtime['dt_relative'] = (finalRealtime['dt'] - finalRealtime['dt'].min()).dt.total_seconds()

    list_cols = ['bitdepth', 'md', 'blockpos', 'rop', 'hklda',
       'woba', 'torqa', 'rpm', 'stppress', 'mudflowin', 'dt_relative']

    for cols in list_cols:
        finalRealtime[cols] = np.interp(finalRealtime['dt_relative'], realtimeraw['dt_relative'].values, realtimeraw[cols])
    finalRealtime = finalRealtime.drop('dt_relative',axis=1)
    return finalRealtime

In [16]:
realtimeraw_test = pd.read_csv('MCG_IJN 2-1_RawREaltime5s.csv')
interpolateRealtimeData(realtimeraw_test)

,dt,date,time,bitdepth,md,blockpos,rop,hklda,woba,torqa,rpm,stppress,mudflowin
0,2023-04-09 00:00:05,2023-04-09,00:00:05,14.840,110.000,4.840,4.58,42.660,0.0,0.0,0.0,0.000,0.00
1,2023-04-09 00:00:10,2023-04-09,00:00:10,14.840,110.000,4.710,4.58,43.710,0.0,0.0,0.0,0.000,0.00
2,2023-04-09 00:00:15,2023-04-09,00:00:15,14.840,110.000,4.510,4.58,43.710,0.0,0.0,0.0,0.000,0.00
3,2023-04-09 00:00:20,2023-04-09,00:00:20,14.840,110.000,4.510,4.58,43.290,0.0,0.0,0.0,0.000,0.00
4,2023-04-09 00:00:25,2023-04-09,00:00:25,14.840,110.000,4.510,4.58,43.180,0.0,0.0,0.0,0.000,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34542,2023-04-10 23:58:35,2023-04-10,23:58:35,291.520,291.520,13.460,7.09,61.670,0.0,0.0,0.0,1836.676,944.24
34543,2023-04-10 23:58:40,2023-04-10,23:58:40,291.536,291.536,13.444,7.09,61.670,0.0,0.0,0.0,1833.150,944.24
34544,2023-04-10 23:58:45,2023-04-10,23:58:45,291.540,291.540,13.440,7.09,61.670,0.0,0.0,0.0,1829.816,944.24
34545,2023-04-10 23:58:50,2023-04-10,23:58:50,291.548,291.548,13.432,7.09,61.638,0.0,0.0,0.0,1825.212,944.24
34546,2023-04-10 23:58:55,2023-04-10,23:58:55,291.558,291.558,13.422,7.09,61.662,0.0,0.0,0.0,1822.022,944.24