In [1]:
import pandas as pd

In [2]:
import requests
CompName_JSON = requests.get(
        "https://pdumitradome.id/dome_api/rtdc/get_company/"
    ).json()
CompName_DF = pd.json_normalize(CompName_JSON, record_path = 'result')
selected_comp = "KS ORKA"

display(CompName_DF[CompName_DF['company_name']==selected_comp])

getWellAPI = "https://pdumitradome.id/dome_api/rtdc/get_well?cid=" + (CompName_DF.loc[CompName_DF['company_name']==selected_comp, 'cid'].values)
WellName_JSON = requests.get(
        getWellAPI[0]
    ).json()
WellName_DF = pd.json_normalize(WellName_JSON, record_path = 'result')
display(WellName_DF)

   cid company_name
19   9      KS ORKA

,wid,cid,well_name,rig_name,active_date,end_date,proposed_total_measured_depth,time_master
0,129,9,SMP T10,Kaishan-1,2020-11-13,2020-12-31,2500,"[{'time_date_start': '2021-01-04', 'time_date_..."
1,130,9,SMP - 119,PRA#1,2020-11-28,2021-01-30,2500,[]
2,135,9,SMP P-118 ST,PRA#1,2021-01-05,2021-04-30,3000,"[{'time_date_start': '2021-01-04', 'time_date_..."
3,136,9,SMP AA-01ST2,Kaishan 1,2021-01-14,2021-07-31,3000,"[{'time_date_start': '2021-01-11', 'time_date_..."
4,140,9,SMP AA-03,Kaishan 1,2021-04-15,2021-06-30,3000,"[{'time_date_start': '2021-04-12', 'time_date_..."
5,143,9,SMP AAE-03,PRA#1,2021-04-25,2021-06-30,3000,"[{'time_date_start': '2021-04-19', 'time_date_..."
6,144,9,SMP AAE-02,PRA#1,2021-06-03,2021-07-31,4000,"[{'time_date_start': '2021-05-31', 'time_date_..."
7,145,9,SMP AA-02ST,Kaishan 1,2021-06-17,2021-08-31,4000,"[{'time_date_start': '2021-06-14', 'time_date_..."
8,146,9,SMP AAE-05,PRA#1,2021-06-28,2021-08-31,4000,"[{'time_date_start': '2021-06-28', 'time_date_..."
9,150,9,SMP AAE-06ST3,PRA#1,2021-08-12,2022-02-05,3000,"[{'time_date_start': '2021-08-09', 'time_date_..."
10,156,9,SMP AAE-07,PRA#1,2021-09-25,2021-10-31,3000,"[{'time_date_start': '2021-09-20', 'time_date_..."
11,160,9,SMP AAE-07ST3,PRA#1,2021-10-25,2022-01-01,3000,"[{'time_date_start': '2021-10-25', 'time_date_..."
12,170,9,SMP AAE-08,PRA#1,2022-01-27,2022-03-31,2500,"[{'time_date_start': '2022-01-24', 'time_date_..."
13,175,9,SMP T-11,Kaishan 1,2022-02-25,2022-04-30,3000,"[{'time_date_start': '2022-02-21', 'time_date_..."
14,182,9,SMP T-12,Kaishan-1,2022-04-12,2022-05-31,3000,"[{'time_date_start': '2022-04-11', 'time_date_..."
15,186,9,SMP T-11 WO,Kaishan 1,2022-05-14,2022-06-11,3000,"[{'time_date_start': '2022-05-09', 'time_date_..."

In [3]:
Well_ID_API = 156

In [9]:
SummaryActivity_DF = pd.read_excel(
    "Data\\Master_Report\\ToBeUploadDB\\Master Report RTOC AAE-07_12.25in_Rev.1.3.xlsx",
    sheet_name = "Raw Data"
)
SummaryActivity_DF['Remarks'].fillna("", inplace=True)
SummaryActivity_DF = SummaryActivity_DF.dropna(subset=['Date'])
# SummaryActivity_DF['Date/Time_End'] = SummaryActivity_DF['Date/Time'].shift(periods=-1)
ActivityLogUnique = SummaryActivity_DF[SummaryActivity_DF['Activity'] != SummaryActivity_DF['Activity'].shift(periods=1)]
ActivityLogUnique['Activity'] = ActivityLogUnique['Activity'].str.upper()
# display(SummaryActivity_DF.head(5))
display(ActivityLogUnique)
print(ActivityLogUnique["Date/Time"].min())
print(ActivityLogUnique["Date/Time"].max())

c:\Users\irsya\Miniconda3\envs\python38\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
C:\Users\irsya\AppData\Local\Temp/ipykernel_25548/3031492371.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ActivityLogUnique['Activity'] = ActivityLogUnique['Activity'].str.upper()

,Date,Time,Date/Time,Duration,Hole Depth,Bit Depth,Meterage (m) (Drilling),Rotate Drilling Time (hrs),Slide Drilling Time (hrs),Reaming Time (hrs),Connection Time (hrs),On Bottom Hours,Stand Duration (hrs),Connection Activity,Sub Activity,Activity,Remarks,WELL NAME,SECTION SIZE
0,2021-10-17,02:29:49,2021-10-17 02:29:49,113.500000,340.47,0.09,,,,,,NaN,NaN,NaN,Make Up BHA,MAKE UP BHA,P/U & M/U 12-1/4 TCI BIT,NaN,NaN
1,2021-10-17,04:23:19,2021-10-17 04:23:19,0.666667,340.47,22.49,,,,,,NaN,NaN,NaN,Moving,TRIP IN,,NaN,NaN
150,2021-10-17,13:45:12,2021-10-17 13:45:12,11.916667,1141.55,1123.81,,,,,,NaN,NaN,NaN,Rotary Drilling,DRILL OUT CEMENT,,NaN,NaN
153,2021-10-17,17:14:11,2021-10-17 17:14:11,27.866667,1182.45,1171.20,,,,,,NaN,NaN,NaN,Pressure Test,OTHER,,NaN,NaN
154,2021-10-17,17:42:03,2021-10-17 17:42:03,0.500000,1182.45,1171.20,,,,,,NaN,NaN,NaN,Moving,DRILL OUT CEMENT,,NaN,NaN
166,2021-10-17,21:27:23,2021-10-17 21:27:23,38.416667,1203.01,1181.19,,,,,,NaN,NaN,NaN,Pressure Test,OTHER,Perform FIT,NaN,NaN
167,2021-10-17,22:05:48,2021-10-17 22:05:48,0.250000,1203.01,1181.19,,,,,,NaN,NaN,NaN,Moving,TRIP OUT,,NaN,NaN
255,2021-10-18,01:06:01,2021-10-18 01:06:01,123.983333,1203.01,49.83,,,,,,NaN,NaN,NaN,Lay Down BHA,LAY DOWN BHA,,NaN,NaN
256,2021-10-18,03:10:00,2021-10-18 03:10:00,39.000000,1203.01,0.00,,,,,,NaN,NaN,NaN,Other,OTHER,"Bit on surface, Prepare M/U BHA",NaN,NaN
257,2021-10-18,03:49:00,2021-10-18 03:49:00,39.000000,1203.01,77.80,,,,,,NaN,NaN,NaN,Make Up BHA,MAKE UP BHA,,NaN,NaN
258,2021-10-18,04:28:00,2021-10-18 04:28:00,2.433333,1203.01,77.80,,,,,00:02:26,NaN,NaN,NaN,Connection,TRIP IN,,NaN,NaN
340,2021-10-18,07:42:27,2021-10-18 07:42:27,6.416667,1211.66,1211.66,2.2,00:06:25,,,,NaN,NaN,NaN,Rotary Drilling,DRILLING FORMATION,,NaN,NaN
386,2021-10-19,05:37:30,2021-10-19 05:37:30,8.750000,1507.39,1476.75,,,,,00:08:45,NaN,NaN,NaN,Connection,WIPER TRIP,,NaN,NaN
432,2021-10-19,07:59:05,2021-10-19 07:59:05,110.250000,1536.98,1536.98,29.59,01:50:15,,,,NaN,NaN,NaN,Rotary Drilling,DRILLING FORMATION,,NaN,NaN
490,2021-10-20,11:01:29,2021-10-20 11:01:29,68.516667,1753.67,1753.59,,,,,,NaN,NaN,Post Connection,Circulation,CIRCULATE HOLE CLEANING,Circulation hole cleaning due to erratic torque,NaN,NaN
491,2021-10-20,12:10:00,2021-10-20 12:10:00,10.000000,1753.67,1753.59,,,,,,NaN,NaN,NaN,Other,STUCK PIPE,Stuck pipe incident,NaN,NaN
492,2021-10-20,12:20:00,2021-10-20 12:20:00,107.000000,1753.67,1753.59,,,,,,NaN,NaN,NaN,Circulation,CIRCULATION,Circulation hole cleaning post stuck pipe,NaN,NaN
493,2021-10-20,14:07:00,2021-10-20 14:07:00,593.000000,1753.67,1753.59,,,,,,NaN,NaN,NaN,Other,STUCK PIPE,,NaN,NaN
498,2021-10-25,00:00:00,2021-10-25 00:00:00,NaN,NaN,NaN,,,,,,NaN,NaN,NaN,NaN,NaN,,NaN,NaN

2021-10-17 02:29:49
2021-10-25 00:00:00

In [10]:
from Streamlit_App import IO_Data
import time

if IO_Data.DomeCekTable(Well_ID_API)['table']==0:
                IO_Data.DomeCreateTable(Well_ID_API)
                print('yes')


for i,row in ActivityLogUnique.iterrows():
    input_dict_temp = {
        'wid':Well_ID_API,
        'dt':str(row['Date/Time']),
        'date':str(row['Date'].date()),
        'time':str(row['Time']),
        'activity':row['Activity'],
        'in_slip_threshold':63,
        'remarks' : row['Remarks'],
        'pic' : 'Admin',
        'section':'12-1/4""'
        
    }

    print(IO_Data.DomeAddData(input_dict_temp))
    # time.sleep(3)
    print(input_dict_temp)

{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-17 02:29:49', 'date': '2021-10-17', 'time': '02:29:49', 'activity': 'MAKE UP BHA', 'in_slip_threshold': 63, 'remarks': 'P/U & M/U 12-1/4 TCI BIT', 'pic': 'Admin', 'section': '12-1/4""'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-17 04:23:19', 'date': '2021-10-17', 'time': '04:23:19', 'activity': 'TRIP IN', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12-1/4""'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-17 13:45:12', 'date': '2021-10-17', 'time': '13:45:12', 'activity': 'DRILL OUT CEMENT', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12-1/4""'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-17 17:14:11', 'date': '2021-10-17', 'time': '17:14:11', 'activity': 'OTHER', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12-1/4""'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-17 17:42:03', 'date': '2021-10-17', 'time': '17:42:03', 'activity': 'DRILL OUT CEMENT', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12-1/4""'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-17 21:27:23', 'date': '2021-10-17', 'time': '21:27:23', 'activity': 'OTHER', 'in_slip_threshold': 63, 'remarks': 'Perform FIT', 'pic': 'Admin', 'section': '12-1/4""'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-17 22:05:48', 'date': '2021-10-17', 'time': '22:05:48', 'activity': 'TRIP OUT', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12-1/4""'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-18 01:06:01', 'date': '2021-10-18', 'time': '01:06:01', 'activity': 'LAY DOWN BHA', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12-1/4""'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-18 03:10:00', 'date': '2021-10-18', 'time': '03:10:00', 'activity': 'OTHER', 'in_slip_threshold': 63, 'remarks': 'Bit on surface, Prepare M/U BHA', 'pic': 'Admin', 'section': '12-1/4""'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-18 03:49:00', 'date': '2021-10-18', 'time': '03:49:00', 'activity': 'MAKE UP BHA', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12-1/4""'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-18 04:28:00', 'date': '2021-10-18', 'time': '04:28:00', 'activity': 'TRIP IN', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12-1/4""'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-18 07:42:27', 'date': '2021-10-18', 'time': '07:42:27', 'activity': 'DRILLING FORMATION', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12-1/4""'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-19 05:37:30', 'date': '2021-10-19', 'time': '05:37:30', 'activity': 'WIPER TRIP', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12-1/4""'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-19 07:59:05', 'date': '2021-10-19', 'time': '07:59:05', 'activity': 'DRILLING FORMATION', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12-1/4""'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-20 11:01:29', 'date': '2021-10-20', 'time': '11:01:29', 'activity': 'CIRCULATE HOLE CLEANING', 'in_slip_threshold': 63, 'remarks': 'Circulation hole cleaning due to erratic torque', 'pic': 'Admin', 'section': '12-1/4""'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-20 12:10:00', 'date': '2021-10-20', 'time': '12:10:00', 'activity': 'STUCK PIPE', 'in_slip_threshold': 63, 'remarks': 'Stuck pipe incident', 'pic': 'Admin', 'section': '12-1/4""'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-20 12:20:00', 'date': '2021-10-20', 'time': '12:20:00', 'activity': 'CIRCULATION', 'in_slip_threshold': 63, 'remarks': 'Circulation hole cleaning post stuck pipe', 'pic': 'Admin', 'section': '12-1/4""'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-20 14:07:00', 'date': '2021-10-20', 'time': '14:07:00', 'activity': 'STUCK PIPE', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12-1/4""'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 156, 'dt': '2021-10-25 00:00:00', 'date': '2021-10-25', 'time': '00:00:00', 'activity': nan, 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12-1/4""'}

In [26]:
timestart = ActivityLogUnique["Date/Time"].min()
timeend = ActivityLogUnique["Date/Time"].max()
InputActivity_DB = (IO_Data.DomeGetData(Well_ID_API, timestart, timeend))
InputActivity_DB

c:\Users\irsya\Documents\Jiunx_Files\PROJECT\2021-PDU\01_PDU_python\Streamlit_App\IO_Data.py:421: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  out_DF = out_DF.sort_values(by='date_time')

,input_id,dt,date,time,activity,in_slip_threshold,remarks,pic,section
0,258,2021-10-04 09:00:01,2021-10-04,09:00:01,MAKE UP BHA,0,,Admin,"26"""""
1,259,2021-10-04 13:28:31,2021-10-04,13:28:31,TRIP IN,0,,Admin,"26"""""
2,260,2021-10-04 14:09:36,2021-10-04,14:09:36,DRILL OUT CEMENT,0,Lost connection at 15:47,Admin,"26"""""
3,261,2021-10-04 17:40:01,2021-10-04,17:40:01,RIG REPAIR,0,Repair TDS,Admin,"26"""""
4,262,2021-10-04 18:27:26,2021-10-04,18:27:26,DRILLING FORMATION,0,,Admin,"26"""""
...,...,...,...,...,...,...,...,...,...
81,348,2021-10-19 07:59:05,2021-10-19,07:59:05,DRILLING FORMATION,0,,Admin,"12-1/4"""""
82,349,2021-10-20 11:01:29,2021-10-20,11:01:29,CIRCULATE HOLE CLEANING,0,Circulation hole cleaning due to erratic torque,Admin,"12-1/4"""""
83,350,2021-10-20 12:10:00,2021-10-20,12:10:00,STUCK PIPE,0,Stuck pipe incident,Admin,"12-1/4"""""
84,351,2021-10-20 12:20:00,2021-10-20,12:20:00,CIRCULATION,0,Circulation hole cleaning post stuck pipe,Admin,"12-1/4"""""
85,352,2021-10-20 14:07:00,2021-10-20,14:07:00,STUCK PIPE,0,,Admin,"12-1/4"""""