In [1]:
import numpy as np 
import json
import requests
import sys
from importlib import reload
import pandas as pd
# Add your library directory to the sys.path
sys.path.append('c:/Users/irsya/Documents/Jiunx_Files/PROJECT/2021-PDU/01_PDU_python/Streamlit_App_v3/')

In [2]:
from PDU_Func import IO_Data, Authentification

In [3]:
reload(Authentification)
reload(IO_Data)
UserDict = {'ID':['71unxv']}
UserAuthDict = Authentification.getUserID(UserDict)
# IO_Data.getAvailableCompanyDF(Authentification.getUserID(UserDict)) 
display(IO_Data.getAvailableWellDF('MCG',UserAuthDict))

WellInfoDict = IO_Data.getWellInfoDict(UserAuthDict, 'MCG', 'IJN 2-1')
WellInfoDict

,wid,cid,well_name,rig_name,active_date,end_date,proposed_total_measured_depth,time_master
0,148,74,IJEN 6-2,EPI-9,2022-12-07,2022-12-10,2800,"[{'time_date_start': '2022-12-05', 'time_date_..."
1,155,74,IJN 6-1 ST2,Harmand#01,2021-09-15,2021-11-30,2800,"[{'time_date_start': '2021-09-13', 'time_date_..."
2,240,74,IJN 5-1,IJN 5-1,2023-01-01,2023-05-17,0,[]
3,243,74,IJN 2-1,EPI-9,2023-04-05,2023-06-10,3500,"[{'time_date_start': '2023-04-03', 'time_date_..."
4,255,74,IJN 6-3,EPI-9,2023-06-14,2023-08-31,3000,"[{'time_date_start': '2023-06-12', 'time_date_..."
5,260,74,IJN 6-4,EPI-9,2023-08-01,2023-09-30,3500,"[{'time_date_start': '2023-07-31', 'time_date_..."
6,272,74,IJN 8-1,EPI-9,2023-10-05,2023-11-30,3000,"[{'time_date_start': '2023-10-02', 'time_date_..."
7,283,74,IJN 8-2,EPI-9,2023-11-26,2024-01-31,3500,"[{'time_date_start': '2023-11-20', 'time_date_..."

{'cid': 74,
 'wid': 243,
 'WellName': 'IJN 2-1',
 'RigName': 3    EPI-9
 Name: rig_name, dtype: string,
 'ActiveDate': '2023-04-05',
 'EndDate': '2023-06-10'}

In [20]:
RigAct_df = pd.DataFrame(
                            IO_Data.getRigActivity(WellInfoDict, 
                            start_date="2000-01-01 00:00:00", 
                            end_date="2100-01-01 00:00:00")['data']
                        )  
RigAct_df['dt'] = RigAct_df['dt'].astype('datetime64[ns]')
RigAct_df['activity'] = RigAct_df['activity'].astype('string')
RigAct_df['actcode'] = RigAct_df['actcode'].astype(int)
RigAct_df.sort_values(by=['dt'], inplace=True)
RigAct_df.reset_index(drop=True, inplace=True)


# RigAct_df = RigAct_df[RigAct_df['activity'].shift(1) != RigAct_df['activity']]
display(RigAct_df)
RigAct_df.to_excel('RigAct_df.xlsx', index=False)

                     dt  actcode                          activity
0   2023-04-07 08:38:46        2                          Drilling
1   2023-04-07 08:54:31        3             Connection (drilling)
2   2023-04-07 08:59:28        2                          Drilling
3   2023-04-07 09:51:59        3             Connection (drilling)
4   2023-04-07 12:06:02        8                       Tripping In
..                  ...      ...                               ...
480 2023-05-30 21:02:51        0                  Undefined Status
481 2023-05-30 23:36:06       14                     Wireline Logs
482 2023-05-31 17:20:27        7    Condition and/or Circulate mud
483 2023-05-31 19:31:59        0                  Undefined Status
484 2023-06-01 17:17:43       21  Nipple Up /Nipple Down BOP Stack

[485 rows x 3 columns]

In [81]:
IO_Data.DomeGetRealtimeRange(WellInfoDict)

        StartDateTime         EndDateTime    Y-Axis
0 2023-04-06 16:52:20 2023-06-15 10:43:25  Realtime

## 01. Create a single Pipeline

### a. get the realtime data for a certain range

In [ ]:
start_date = "2023-04-07 00:00:00"
end_date = "2021-04-08 23:59:00"

### b. label the realtime data with the rig activity

### c. generate Activity Summary Group

### d. relabelling the stand and others Summary calculation