In [1]:
import pandas as pd 
import numpy as np 
from importlib import reload
import datetime 
from PDU_Func import IO_Data, ActivitySummary,Authentification

2023-04-17 02:02:44.001 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

In [2]:
UserAuthDict = {
  "data": {
    "user_name": "Admin(TEST)",
    "user_id": "MIH",
    "user_email": "irsyadhbtlh96@gmail.com",
    "user_company_name": "PDU",
    "user_cid": "",
    "status": "Authorized"
  },
  "verification": "verified"
}
WellInfoDict = {
  "cid": 9,
  "wid": 146,
  "WellName": "SMP AAE-05",
  "RigName": "8    PRA#1\nName: rig_name, dtype: string",
  "ActiveDate": "Timestamp('2021-06-28 00:00:00')",
  "EndDate": "Timestamp('2021-08-31 00:00:00')"
}
UserDateRange={
  "StartDate": datetime.date(2021, 7, 31),
  "StartTime": datetime.time(0, 0),
  "EndDate": datetime.date(2021, 8, 1),
  "EndTime": datetime.time(23, 59)
}
print("Start Time")
print(str(UserDateRange['StartDate']) + " " + str(UserDateRange['StartTime']))
print(str(UserDateRange['EndDate']) + " " + str(UserDateRange['EndTime']))

Start Time
2021-07-31 00:00:00
2021-08-01 23:59:00

## get Activity Log

In [3]:

ActivityLog = IO_Data.DomeGetData(WellInfoDict, UserDateRange, table_type="ActivityLogTable")
ActivityLog

get ActivityLogTable data/table from DOME

,id,DateTime,Date,Time,Activity,In-Slip Threshold,Remarks,PIC,Section Size
0,515,2021-07-31 00:57:39,2021-07-31,00:57:39,TRIP IN,63,,MIH,"12 1/4"""
1,516,2021-07-31 07:32:40,2021-07-31,07:32:40,DRILLING FORMATION,63,,MIH,"12 1/4"""
2,517,2021-08-01 08:56:23,2021-08-01,08:56:23,WIPER TRIP,63,Wiper Trip,MIH,"12 1/4"""
3,518,2021-08-01 11:32:03,2021-08-01,11:32:03,DRILLING FORMATION,63,,MIH,"12 1/4"""
4,519,2021-08-01 21:18:50,2021-08-01,21:18:50,WIPER TRIP,63,,MIH,"12 1/4"""
5,520,2021-08-01 23:32:46,2021-08-01,23:32:46,DRILLING FORMATION,63,,MIH,"12 1/4"""

## get Realtime Sensor

In [12]:
WellInfoDict = {
  "cid": 9, # KS ORKA
  "wid": 146, # SMP AAE-05
  "WellName": "SMP AAE-05",
  "RigName": "8    PRA#1\nName: rig_name, dtype: string",
  "ActiveDate": "Timestamp('2021-06-28 00:00:00')",
  "EndDate": "Timestamp('2021-08-31 00:00:00')"
}
DateTimeRange = {
  "StartDate": "2021-07-28",
  "StartTime": "00:00:00",
  "EndDate": "2021-07-29",
  "EndTime": "23:59:00"
}
reload(IO_Data)
Out = IO_Data.DomeGetRealtimeSensorData(WellInfoDict, DateTimeRange)
Out

c:\Users\irsya\Documents\Jiunx_Files\PROJECT\2021-PDU\01_PDU_python\Streamlit_App_v2\PDU_Func\IO_Data.py:371: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  start = datetime.strptime(Data_params['start'], '%Y-%m-%d %H:%M:%S')

,Date,Time,dt,md,bitdepth,blockpos,rop,woba,torqa,rpm,stppress,mudflowin,Hookload
0,2021-07-28,07:30:00,2021-07-28 07:30:00,489.24,476.35,24.97,0.00,0.00,2.14,32,683.76,621.63,88.96
1,2021-07-28,07:30:05,2021-07-28 07:30:05,489.24,476.35,24.97,0.00,0.00,2.17,32,684.50,620.75,88.48
2,2021-07-28,07:30:10,2021-07-28 07:30:10,489.24,476.35,24.97,0.00,0.00,2.18,32,683.03,594.26,88.64
3,2021-07-28,07:30:15,2021-07-28 07:30:15,489.24,476.35,24.97,0.00,0.00,2.13,32,682.66,622.51,88.32
4,2021-07-28,07:30:20,2021-07-28 07:30:20,489.24,476.36,24.96,0.00,0.00,2.15,32,683.40,622.51,87.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25442,2021-07-29,23:58:40,2021-07-29 23:58:40,1598.96,1598.96,24.75,9.33,45.75,10.72,60,1968.75,865.34,110.04
25443,2021-07-29,23:58:45,2021-07-29 23:58:45,1598.98,1598.98,24.73,9.33,45.54,11.09,59,1972.80,865.34,110.25
25444,2021-07-29,23:58:50,2021-07-29 23:58:50,1598.99,1598.99,24.72,9.33,45.61,10.55,60,1970.96,865.34,110.18
25445,2021-07-29,23:58:55,2021-07-29 23:58:55,1599.01,1599.01,24.71,8.13,45.61,10.99,59,1969.85,865.34,110.18
25446,2021-07-29,23:59:00,2021-07-29 23:59:00,1599.02,1599.02,24.69,7.83,45.75,10.85,59,1971.69,865.34,110.04

In [32]:
reload(ActivitySummary)
ActivitySummaryTable = ActivitySummary.ActivitySummaryTable(WellInfoDict, DateTimeRange)
ActivitySummaryTable.getActivitySummary(ActivityLog)

get Activity Summary data/table from DOME

c:\Users\irsya\Documents\Jiunx_Files\PROJECT\2021-PDU\01_PDU_python\Streamlit_App_v2\PDU_Func\IO_Data.py:371: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  Realtime_DF['dt'] = Realtime_DF['dt'].astype('datetime64')

KeyError: 'dt'

In [ ]:
ActivitySummaryTable.getActivitySummary(ActivityLog)