In [1]:
import pandas as pd 
import numpy as np 
from importlib import reload
import datetime 
from PDU_Func import IO_Data, ActivitySummary,Authentification

2023-04-26 20:13:51.033 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

In [2]:
UserAuthDict = {
  "data": {
    "user_name": "Admin(TEST)",
    "user_id": "MIH",
    "user_email": "irsyadhbtlh96@gmail.com",
    "user_company_name": "PDU",
    "user_cid": "",
    "status": "Authorized"
  },
  "verification": "verified"
}
WellInfoDict = {
  "cid": 9,
  "wid": 146,
  "WellName": "SMP AAE-05",
  "RigName": "8    PRA#1\nName: rig_name, dtype: string",
  "ActiveDate": "Timestamp('2021-06-28 00:00:00')",
  "EndDate": "Timestamp('2021-08-31 00:00:00')"
}
UserDateRange={
  "StartDate": datetime.date(2021, 7, 31),
  "StartTime": datetime.time(0, 0),
  "EndDate": datetime.date(2021, 8, 1),
  "EndTime": datetime.time(23, 59)
}
print("Start Time")
print(str(UserDateRange['StartDate']) + " " + str(UserDateRange['StartTime']))
print(str(UserDateRange['EndDate']) + " " + str(UserDateRange['EndTime']))

Start Time
2021-07-31 00:00:00
2021-08-01 23:59:00

## get Activity Log

In [3]:

ActivityLog = IO_Data.DomeGetData(WellInfoDict, UserDateRange, table_type="ActivityLogTable")
ActivityLog

get ActivityLogTable data/table from DOME

,id,DateTime,Date,Time,Activity,In-Slip Threshold,Remarks,PIC,Section Size
0,515,2021-07-31 00:57:39,2021-07-31,00:57:39,TRIP IN,63,,MIH,"12 1/4"""
1,516,2021-07-31 07:32:40,2021-07-31,07:32:40,DRILLING FORMATION,63,,MIH,"12 1/4"""
2,517,2021-08-01 08:56:23,2021-08-01,08:56:23,WIPER TRIP,63,Wiper Trip,MIH,"12 1/4"""
3,518,2021-08-01 11:32:03,2021-08-01,11:32:03,DRILLING FORMATION,63,,MIH,"12 1/4"""
4,519,2021-08-01 21:18:50,2021-08-01,21:18:50,WIPER TRIP,63,,MIH,"12 1/4"""
5,520,2021-08-01 23:32:46,2021-08-01,23:32:46,DRILLING FORMATION,63,,MIH,"12 1/4"""

## get Realtime Sensor

In [4]:
WellInfoDict = {
  "cid": 9, # KS ORKA
  "wid": 146, # SMP AAE-05
  "WellName": "SMP AAE-05",
  "RigName": "8    PRA#1\nName: rig_name, dtype: string",
  "ActiveDate": "Timestamp('2021-06-28 00:00:00')",
  "EndDate": "Timestamp('2021-08-31 00:00:00')"
}
DateTimeRange = {
  "StartDate": "2021-07-28",
  "StartTime": "00:00:00",
  "EndDate": "2021-07-29",
  "EndTime": "23:59:00"
}
reload(IO_Data)
Out = IO_Data.DomeGetRealtimeSensorData(WellInfoDict, DateTimeRange)
Out

,Date,Time,dt,md,bitdepth,blockpos,rop,woba,torqa,rpm,stppress,mudflowin,hklda
0,2021-07-28,07:30:00,2021-07-28 07:30:00,489.24,476.35,24.97,0.00,0.00,2.14,32,683.76,621.63,88.96
1,2021-07-28,07:30:05,2021-07-28 07:30:05,489.24,476.35,24.97,0.00,0.00,2.17,32,684.50,620.75,88.48
2,2021-07-28,07:30:10,2021-07-28 07:30:10,489.24,476.35,24.97,0.00,0.00,2.18,32,683.03,594.26,88.64
3,2021-07-28,07:30:15,2021-07-28 07:30:15,489.24,476.35,24.97,0.00,0.00,2.13,32,682.66,622.51,88.32
4,2021-07-28,07:30:20,2021-07-28 07:30:20,489.24,476.36,24.96,0.00,0.00,2.15,32,683.40,622.51,87.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25442,2021-07-29,23:58:40,2021-07-29 23:58:40,1598.96,1598.96,24.75,9.33,45.75,10.72,60,1968.75,865.34,110.04
25443,2021-07-29,23:58:45,2021-07-29 23:58:45,1598.98,1598.98,24.73,9.33,45.54,11.09,59,1972.80,865.34,110.25
25444,2021-07-29,23:58:50,2021-07-29 23:58:50,1598.99,1598.99,24.72,9.33,45.61,10.55,60,1970.96,865.34,110.18
25445,2021-07-29,23:58:55,2021-07-29 23:58:55,1599.01,1599.01,24.71,8.13,45.61,10.99,59,1969.85,865.34,110.18
25446,2021-07-29,23:59:00,2021-07-29 23:59:00,1599.02,1599.02,24.69,7.83,45.75,10.85,59,1971.69,865.34,110.04

In [13]:
reload(ActivitySummary)
ActivitySummaryTable = ActivitySummary.ActivitySummaryTable(WellInfoDict, UserDateRange)
OutTest = ActivitySummaryTable.getActivitySummary(ActivityLog, Out)
OutTest = ActivitySummary.SubActivityMapping(OutTest)
OutTest

get Activity Summary data/table from DOME

,Date,Time,dt,md,bitdepth,blockpos,rop,woba,torqa,rpm,...,mudflowin,hklda,Activity,PIC,Section Size,remarks,In-Slip Threshold,SubActivity,logic_status,isBitDepthMoving
0,2021-07-28,07:30:00,2021-07-28 07:30:00,489.24,476.35,24.97,0.00,0.00,2.14,32.0,...,621.63,88.96,NaN,nan,nan,nan,NaN,FALSE/Check,0,False
1,2021-07-28,07:30:05,2021-07-28 07:30:05,489.24,476.35,24.97,0.00,0.00,2.17,32.0,...,620.75,88.48,NaN,nan,nan,nan,NaN,FALSE/Check,0,False
2,2021-07-28,07:30:10,2021-07-28 07:30:10,489.24,476.35,24.97,0.00,0.00,2.18,32.0,...,594.26,88.64,NaN,nan,nan,nan,NaN,FALSE/Check,0,False
3,2021-07-28,07:30:15,2021-07-28 07:30:15,489.24,476.35,24.97,0.00,0.00,2.13,32.0,...,622.51,88.32,NaN,nan,nan,nan,NaN,FALSE/Check,0,True
4,2021-07-28,07:30:20,2021-07-28 07:30:20,489.24,476.36,24.96,0.00,0.00,2.15,32.0,...,622.51,87.92,NaN,nan,nan,nan,NaN,FALSE/Check,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25442,2021-07-29,23:58:40,2021-07-29 23:58:40,1598.96,1598.96,24.75,9.33,45.75,10.72,60.0,...,865.34,110.04,NaN,nan,nan,nan,NaN,FALSE/Check,0,True
25443,2021-07-29,23:58:45,2021-07-29 23:58:45,1598.98,1598.98,24.73,9.33,45.54,11.09,59.0,...,865.34,110.25,NaN,nan,nan,nan,NaN,FALSE/Check,0,True
25444,2021-07-29,23:58:50,2021-07-29 23:58:50,1598.99,1598.99,24.72,9.33,45.61,10.55,60.0,...,865.34,110.18,NaN,nan,nan,nan,NaN,FALSE/Check,0,True
25445,2021-07-29,23:58:55,2021-07-29 23:58:55,1599.01,1599.01,24.71,8.13,45.61,10.99,59.0,...,865.34,110.18,NaN,nan,nan,nan,NaN,FALSE/Check,0,True
25446,2021-07-29,23:59:00,2021-07-29 23:59:00,1599.02,1599.02,24.69,7.83,45.75,10.85,59.0,...,865.34,110.04,NaN,nan,nan,nan,NaN,FALSE/Check,0,True

In [ ]:


def GenerateDuration_DF_v4(RealTime_DB, DrillActivityList='default'):
    if DrillActivityList=='default':
        DrillActivityList = ["DRILLING FORMATION", 'CIRCULATE HOLE CLEANING','CONNECTION','DRILL OUT CEMENT',]


    RealTime_DB['dt'] = pd.to_datetime(RealTime_DB['dt'])
    RealTime_DB["LABEL_All"] =RealTime_DB['SubActivity'].astype(str)+'--'+RealTime_DB['Activity'].astype(str)

    # TODO , a funtion that check the latest hole depth
    Hole_Depth = 0
    list_dict_out = []
    for k,DF_Temp in RealTime_DB.groupby((RealTime_DB['LABEL_All'].shift() != RealTime_DB['LABEL_All']).cumsum()):

        # if not(("Hole_Depth" in locals()) or ("Hole_Depth" in globals())):
        #     Hole_Depth = 0

        list_temp = []

        # date = DF_Temp.head(1)['date'].values[0]

        # Time_start = pd.to_datetime(date + " " + DF_Temp.head(1)['time'].values[0])
        # Time_end_temp = DF_Temp.tail(1)['time'].values[0]
        # Time_end = pd.to_datetime(DF_Temp.tail(1)['date'].values[0] + " " + str((datetime.strptime(Time_end_temp, "%H:%M:%S") + timedelta(seconds=5)).time()))

        StartDateTime = DF_Temp['dt'].iloc[0]
        EndDateTime = DF_Temp['DateTime'].iloc[-1]
        # Time_start = DF_Temp.head(1)['time'].values[0]
        # Time_end_temp = DF_Temp.tail(1)['time'].values[0]
        # Time_end = str((datetime.strptime(Time_end_temp, "%H:%M:%S") + timedelta(seconds=5)).time())

        LABEL_Activity = DF_Temp['Activity'].iloc[0]
        LABEL_SubActivity = DF_Temp['SubActivity'].iloc[0]
        section_data = DF_Temp['Section Size'].iloc[0]
        pic_data = DF_Temp['PIC'].iloc[0]
        InSlip_Treshold_data = DF_Temp['In-Slip Threshold'].iloc[0]
        remarks_data = DF_Temp['remarks'].iloc[0]

        # Duration(minutes)
        Duration = (StartDateTime - EndDateTime).total_seconds() / 60.0 


        Hole_Depth_Temp = DF_Temp['md'].max()
        if float(Hole_Depth_Temp)>= float(Hole_Depth):
            Hole_Depth = Hole_Depth_Temp
        
        Bit_Depth = DF_Temp['bitdepth'].mean()

        MeterageDrilling = np.nan

        RotateDrilling = np.nan
        SlideDrilling = np.nan
        ReamingTime = np.nan
        ConnectionTime = np.nan

        OnBottomHours = np.nan
        StandDuration = np.nan

        if LABEL_Activity in DrillActivityList:
            MeterageDrilling = round((DF_Temp['md'].max()-DF_Temp['md'].min()),2)

        if LABEL_SubActivity == "Rotary Drilling":
            RotateDrilling = Duration

        if LABEL_SubActivity == "Slide Drilling":
            SlideDrilling = Duration

        if LABEL_SubActivity == "Reaming":
            ReamingTime = Duration
        if LABEL_SubActivity == "Connection":
            ConnectionTime = Duration


        list_dict_out.append(
            {
            'date':date,
            'Time_start':Time_start,
            'Time_end':Time_end,
            'date_time':date_time,
            'Duration(minutes)':Duration,
            'Hole Depth(max)':Hole_Depth,
            'Bit Depth(mean)':Bit_Depth,
            "Meterage(m)(Drilling)": MeterageDrilling,
            'RotateDrilling':RotateDrilling,
            'Slide Drilling':SlideDrilling,
            'ReamingTime':ReamingTime,
            'ConnectionTime':ConnectionTime,
            'On Bottom Hours':OnBottomHours,
            'Stand Duration': StandDuration,
            'LABEL_SubActivity': LABEL_SubActivity,
            "LABEL_Activity": LABEL_Activity,
            "PIC":pic_data,
            "Remarks":remarks_data,
            "Section":section_data,

            }
        )
    Duration_DB = pd.DataFrame.from_dict(list_dict_out, orient='columns')
    Duration_DB = Duration_DB.astype(
        {
            'date':'datetime64',
            'Duration(minutes)':'float',
            'Hole Depth(max)':'float',
            'Bit Depth(mean)':'float',
            "Meterage(m)(Drilling)":'float',
            'RotateDrilling':'float',
            'Slide Drilling':'float',
            'ReamingTime':'float',
            'ConnectionTime':'float',
            'On Bottom Hours':'float',
            'Stand Duration':'float',
            "LABEL_SubActivity":'str', 
            "LABEL_Activity":'str',
            "PIC":'str',
            "Remarks":'str',
            "Section":'str',
        }
    )

    listSetDecimals = [
            'Duration(minutes)',
            'Hole Depth(max)',
            'Bit Depth(mean)',
            "Meterage(m)(Drilling)",
            'RotateDrilling',
            'Slide Drilling',
            'ReamingTime',
            'ConnectionTime',
            'On Bottom Hours',
            'Stand Duration',
    ]
    for ColumnName in listSetDecimals:
        # print(ColumnName)
        Duration_DB[ColumnName] = Duration_DB[ColumnName].round(decimals=2)

    # rounded_df = df.round(decimals=2)
    return Duration_DB

GenerateDuration_DF_v4(OutTest)

In [ ]:
# GenerateDuration
## Aggregate 1

# as it is
# datetime start 
# datetime end 
# date 
# well name
# activity
# sub-activity
# section size
# PIC
# in-slip threshold
# remarks

# 
# calculate on the fly
# Duration 
# Hole Depth 
# Bit Depth 
# Drilling Meterage
# Rotate Drilling Time 
# Slide Drilling Time
# Reaming Time
# Connection Time


# LabelStand
## Aggregate 2
# Connection Activity
# On Bottom Duration 
# Stand Duration

In [15]:
OutTest.columns

Index(['Date', 'Time', 'dt', 'md', 'bitdepth', 'blockpos', 'rop', 'woba',
       'torqa', 'rpm', 'stppress', 'mudflowin', 'hklda', 'Activity', 'PIC',
       'Section Size', 'remarks', 'In-Slip Threshold', 'SubActivity',
       'logic_status', 'isBitDepthMoving'],
      dtype='object')

In [19]:
test = pd.DataFrame(
    {
    "a":[1,2,np.nan,4],
    "b":[1,2,3,4],
    }
)
test.mean()

a    2.333333
b    2.500000
dtype: float64

In [21]:
7/4

1.75

## Realtime Sensor Download parallel

In [3]:
from datetime import datetime
import requests
import json
import time
from Page import Welcome
from datetime import datetime
import pandas as pd
def DomeGetRealtimeSensorData(WellInfoDict, UserDateRange):
    # UserDateRange = {
    #         "StartDate": UserDateRange['StartDate'].strftime('%Y-%m-%d'),
    #         "StartTime": UserDateRange['StartTime'].strftime('%H:%M:%S'),
    #         "EndDate": UserDateRange['EndDate'].strftime('%Y-%m-%d'),
    #         "EndTime": UserDateRange['EndTime'].strftime('%H:%M:%S'),
    #         }

    # TODO: uncomment the code below if Realtime Data is ready
    Data_params ={
        "wid" : int(WellInfoDict['wid']),
        "start" : str(UserDateRange['StartDate']) + " " + str(UserDateRange['StartTime']),
        "end" : str(UserDateRange['EndDate']) + " " + str(UserDateRange['EndTime']),
    }
    

    column_list = ["dt", "date", "time", "bitdepth", "md", "blockpos", "rop", "hklda", "woba", "torqa", "rpm", "stppress", "mudflowin",]

    WellData = (
        (
            # requests.get("https://pdumitradome.id/dome_api/rtdc/rtdc/get_data", data=json.dumps(Data_params))
            requests.get("http://khansadev.xyz/dome_api/rtdc/get_data", data=json.dumps(Data_params))
        ).text
    )
    Realtime_DF = pd.json_normalize(json.loads(WellData), record_path='result')
    Realtime_DF['dt'] = Realtime_DF['dt'].astype('datetime64[ns]')
    start = datetime.strptime(Data_params['start'], '%Y-%m-%d %H:%M:%S')
    end = datetime.strptime(Data_params['end'], '%Y-%m-%d %H:%M:%S')
    mask = (Realtime_DF['dt'] > start) & (Realtime_DF['dt'] <= end)
    filtered_DF = Realtime_DF[mask]
    return filtered_DF[column_list]


UserDateRange = {
  "StartDate": "2023-04-28",
  "StartTime": "01:10:00",
  "EndDate": "2023-04-29",
  "EndTime": "23:10:00"
}
WellInfoDict = {
  "cid": 74,
  "wid": 243,
  "WellName": "IJN 2-1",
  "RigName": "2    EPI-9\nName: rig_name, dtype: string",
  "ActiveDate": "Timestamp('2023-04-05 00:00:00')",
  "EndDate": "Timestamp('2023-05-31 00:00:00')"
}

# DomeGetRealtimeSensorData(WellInfoDict, UserDateRange)

In [2]:
def splitDateTime(UserDateRange, hours=0.5):
    startDateTimeStr = UserDateRange['StartDate'] + ' ' + UserDateRange['StartTime']
    endDateTimeStr = UserDateRange['EndDate'] + ' ' + UserDateRange['EndTime']


    startDateTime = pd.Timestamp(startDateTimeStr)
    endDateTime = pd.Timestamp(endDateTimeStr)
    deltaTime = pd.Timedelta(hours=hours)

    date_ranges = pd.date_range(start=startDateTime, end=endDateTime.floor("H"), freq=deltaTime)

    date_list = date_ranges.tolist() + [endDateTime]
    StartDateTimeList,EndDateTimeList = date_list[:-1],date_list[1:]
    return StartDateTimeList,EndDateTimeList
StartDateTimeList,EndDateTimeList = splitDateTime(UserDateRange, hours=0.5)
for i,j in zip(StartDateTimeList,EndDateTimeList):
    print(str(i) + " - " + str(j))
    # for i,j in zip(date_list[:-1],date_list[1:]):
    #     print(str(i) + " - " +str(j))

2023-04-28 01:10:00 - 2023-04-28 01:40:00
2023-04-28 01:40:00 - 2023-04-28 02:10:00
2023-04-28 02:10:00 - 2023-04-28 02:40:00
2023-04-28 02:40:00 - 2023-04-28 03:10:00
2023-04-28 03:10:00 - 2023-04-28 03:40:00
2023-04-28 03:40:00 - 2023-04-28 04:10:00
2023-04-28 04:10:00 - 2023-04-28 04:40:00
2023-04-28 04:40:00 - 2023-04-28 05:10:00
2023-04-28 05:10:00 - 2023-04-28 05:40:00
2023-04-28 05:40:00 - 2023-04-28 06:10:00
2023-04-28 06:10:00 - 2023-04-28 06:40:00
2023-04-28 06:40:00 - 2023-04-28 07:10:00
2023-04-28 07:10:00 - 2023-04-28 07:40:00
2023-04-28 07:40:00 - 2023-04-28 08:10:00
2023-04-28 08:10:00 - 2023-04-28 08:40:00
2023-04-28 08:40:00 - 2023-04-28 09:10:00
2023-04-28 09:10:00 - 2023-04-28 09:40:00
2023-04-28 09:40:00 - 2023-04-28 10:10:00
2023-04-28 10:10:00 - 2023-04-28 10:40:00
2023-04-28 10:40:00 - 2023-04-28 11:10:00
2023-04-28 11:10:00 - 2023-04-28 11:40:00
2023-04-28 11:40:00 - 2023-04-28 12:10:00
2023-04-28 12:10:00 - 2023-04-28 12:40:00
2023-04-28 12:40:00 - 2023-04-28 13:10:00
2023-04-28 13:10:00 - 2023-04-28 13:40:00
2023-04-28 13:40:00 - 2023-04-28 14:10:00
2023-04-28 14:10:00 - 2023-04-28 14:40:00
2023-04-28 14:40:00 - 2023-04-28 15:10:00
2023-04-28 15:10:00 - 2023-04-28 15:40:00
2023-04-28 15:40:00 - 2023-04-28 16:10:00
2023-04-28 16:10:00 - 2023-04-28 16:40:00
2023-04-28 16:40:00 - 2023-04-28 17:10:00
2023-04-28 17:10:00 - 2023-04-28 17:40:00
2023-04-28 17:40:00 - 2023-04-28 18:10:00
2023-04-28 18:10:00 - 2023-04-28 18:40:00
2023-04-28 18:40:00 - 2023-04-28 19:10:00
2023-04-28 19:10:00 - 2023-04-28 19:40:00
2023-04-28 19:40:00 - 2023-04-28 20:10:00
2023-04-28 20:10:00 - 2023-04-28 20:40:00
2023-04-28 20:40:00 - 2023-04-28 21:10:00
2023-04-28 21:10:00 - 2023-04-28 21:40:00
2023-04-28 21:40:00 - 2023-04-28 22:10:00
2023-04-28 22:10:00 - 2023-04-28 22:40:00
2023-04-28 22:40:00 - 2023-04-28 23:10:00
2023-04-28 23:10:00 - 2023-04-28 23:40:00
2023-04-28 23:40:00 - 2023-04-29 00:10:00
2023-04-29 00:10:00 - 2023-04-29 00:40:00
2023-04-29 00:40:00 - 2023-04-29 01:10:00
2023-04-29 01:10:00 - 2023-04-29 01:40:00
2023-04-29 01:40:00 - 2023-04-29 02:10:00
2023-04-29 02:10:00 - 2023-04-29 02:40:00
2023-04-29 02:40:00 - 2023-04-29 03:10:00
2023-04-29 03:10:00 - 2023-04-29 03:40:00
2023-04-29 03:40:00 - 2023-04-29 04:10:00
2023-04-29 04:10:00 - 2023-04-29 04:40:00
2023-04-29 04:40:00 - 2023-04-29 05:10:00
2023-04-29 05:10:00 - 2023-04-29 05:40:00
2023-04-29 05:40:00 - 2023-04-29 06:10:00
2023-04-29 06:10:00 - 2023-04-29 06:40:00
2023-04-29 06:40:00 - 2023-04-29 07:10:00
2023-04-29 07:10:00 - 2023-04-29 07:40:00
2023-04-29 07:40:00 - 2023-04-29 08:10:00
2023-04-29 08:10:00 - 2023-04-29 08:40:00
2023-04-29 08:40:00 - 2023-04-29 09:10:00
2023-04-29 09:10:00 - 2023-04-29 09:40:00
2023-04-29 09:40:00 - 2023-04-29 10:10:00
2023-04-29 10:10:00 - 2023-04-29 10:40:00
2023-04-29 10:40:00 - 2023-04-29 11:10:00
2023-04-29 11:10:00 - 2023-04-29 11:40:00
2023-04-29 11:40:00 - 2023-04-29 12:10:00
2023-04-29 12:10:00 - 2023-04-29 12:40:00
2023-04-29 12:40:00 - 2023-04-29 13:10:00
2023-04-29 13:10:00 - 2023-04-29 13:40:00
2023-04-29 13:40:00 - 2023-04-29 14:10:00
2023-04-29 14:10:00 - 2023-04-29 14:40:00
2023-04-29 14:40:00 - 2023-04-29 15:10:00
2023-04-29 15:10:00 - 2023-04-29 15:40:00
2023-04-29 15:40:00 - 2023-04-29 16:10:00
2023-04-29 16:10:00 - 2023-04-29 16:40:00
2023-04-29 16:40:00 - 2023-04-29 17:10:00
2023-04-29 17:10:00 - 2023-04-29 17:40:00
2023-04-29 17:40:00 - 2023-04-29 18:10:00
2023-04-29 18:10:00 - 2023-04-29 18:40:00
2023-04-29 18:40:00 - 2023-04-29 19:10:00
2023-04-29 19:10:00 - 2023-04-29 19:40:00
2023-04-29 19:40:00 - 2023-04-29 20:10:00
2023-04-29 20:10:00 - 2023-04-29 20:40:00
2023-04-29 20:40:00 - 2023-04-29 21:10:00
2023-04-29 21:10:00 - 2023-04-29 21:40:00
2023-04-29 21:40:00 - 2023-04-29 22:10:00
2023-04-29 22:10:00 - 2023-04-29 22:40:00
2023-04-29 22:40:00 - 2023-04-29 23:10:00

In [7]:
import time
import numpy as np
from tqdm import tqdm
def DomeGetRealtimeSensorData_v2(WellInfoDict, UserDateRange, hours=0.5):
    # UserDateRange = {
    #         "StartDate": UserDateRange['StartDate'].strftime('%Y-%m-%d'),
    #         "StartTime": UserDateRange['StartTime'].strftime('%H:%M:%S'),
    #         "EndDate": UserDateRange['EndDate'].strftime('%Y-%m-%d'),
    #         "EndTime": UserDateRange['EndTime'].strftime('%H:%M:%S'),
    #         }
    StartDateTimeList,EndDateTimeList = splitDateTime(UserDateRange, hours=hours)
    # TODO: uncomment the code below if Realtime Data is ready
    column_list = ["dt", "date", "time", "bitdepth", "md", "blockpos", "rop", "hklda", "woba", "torqa", "rpm", "stppress", "mudflowin",]
    Realtime_List = []
    time_elapsed = []
    i = 0
    StartEndList=list(zip(StartDateTimeList,EndDateTimeList))

    for StartEnd in tqdm(((StartEndList))):
        StartDateTime,EndDateTime = StartEnd
        loopStartTime = time.time()
        Data_params ={
            "wid" : int(WellInfoDict['wid']),
            "start" : str(StartDateTime),
            "end" : str(EndDateTime),
        }
        # print(Data_params)

        WellData = json.loads((
            (
                # requests.get("https://pdumitradome.id/dome_api/rtdc/rtdc/get_data", data=json.dumps(Data_params))
                requests.get("http://khansadev.xyz/dome_api/rtdc/get_data", data=json.dumps(Data_params))
            ).text
        ))
        if WellData['status'] != 200:
            raise KeyError (WellData['message'])
        
        Realtime_DF_temp = pd.json_normalize((WellData), record_path='result')
        Realtime_DF_temp['dt'] = Realtime_DF_temp['dt'].astype('datetime64[ns]')
        Realtime_List.append(Realtime_DF_temp)
        loopEndTime = time.time()
        i=i+1
        time_elapsed.append(loopEndTime-loopStartTime)
        # print(f"Iteration {i}: {(loopEndTime-loopStartTime):.4f} seconds")
    Realtime_DF = pd.concat(Realtime_List, axis=0, ignore_index=True)

    start = str(UserDateRange['StartDate']) + " " + str(UserDateRange['StartTime'])
    end = str(UserDateRange['EndDate']) + " " + str(UserDateRange['EndTime'])
    mask = (Realtime_DF['dt'] > start) & (Realtime_DF['dt'] <= end)
    filtered_DF = Realtime_DF[mask]
    print( np.mean(time_elapsed))
    return filtered_DF[column_list]
starttime = time.time()
DomeGetRealtimeSensorData_v2(WellInfoDict, UserDateRange, hours=0.5)
print(time.time() - starttime)

100%|██████████| 92/92 [01:43<00:00,  1.12s/it]

1.121764600276947
104.67624258995056

In [49]:
from multiprocessing.pool import ThreadPool
from functools import partial

def DomeGetRealtimeSensorDataSingleDate(WellInfoDict, StartDateTime, EndDateTime):
    # UserDateRange = {
    #         "StartDate": UserDateRange['StartDate'].strftime('%Y-%m-%d'),
    #         "StartTime": UserDateRange['StartTime'].strftime('%H:%M:%S'),
    #         "EndDate": UserDateRange['EndDate'].strftime('%Y-%m-%d'),
    #         "EndTime": UserDateRange['EndTime'].strftime('%H:%M:%S'),
    #         }

    # TODO: uncomment the code below if Realtime Data is ready
    column_list = ["dt", "date", "time", "bitdepth", "md", "blockpos", "rop", "hklda", "woba", "torqa", "rpm", "stppress", "mudflowin",]

    # for StartDateTime,EndDateTime in zip(StartDateTimeList,EndDateTimeList):
    Data_params ={
        "wid" : int(WellInfoDict['wid']),
        "start" : str(StartDateTime),
        "end" : str(EndDateTime),
    }

    WellData = json.loads((
        (
            # requests.get("https://pdumitradome.id/dome_api/rtdc/rtdc/get_data", data=json.dumps(Data_params))
            requests.get("http://khansadev.xyz/dome_api/rtdc/get_data", data=json.dumps(Data_params))
        ).text
    ))
    if WellData['status'] != 200:
        raise KeyError (WellData['message'])
    
    Realtime_DF = pd.json_normalize((WellData), record_path='result')
    Realtime_DF['dt'] = Realtime_DF['dt'].astype('datetime64[ns]')

        # print(f"Iteration {i}: {(loopEndTime-loopStartTime):.4f} seconds")


    # start = str(UserDateRange['StartDate']) + " " + str(UserDateRange['StartTime'])
    # end = str(UserDateRange['EndDate']) + " " + str(UserDateRange['EndTime'])
    # start = datetime.strptime(Data_params['start'], '%Y-%m-%d %H:%M:%S')
    # end = datetime.strptime(Data_params['end'], '%Y-%m-%d %H:%M:%S')
    # mask = (Realtime_DF['dt'] > start) & (Realtime_DF['dt'] <= end)
    # filtered_DF = Realtime_DF[mask]

    return Realtime_DF[column_list]

def DomeGetRealtimeSensorData_MultiCPU(WellInfoDict, UserDateRange,hours=0.5)

    StartDateTimeList,EndDateTimeList = splitDateTime(UserDateRange, hours=0.5)
    partial_get_data = partial(DomeGetRealtimeSensorDataSingleDate, WellInfoDict)

    with ThreadPool(processes=8) as pool:
        Realtime_List = pool.starmap(partial_get_data, zip(StartDateTimeList,EndDateTimeList))
    Realtime_DF = pd.concat(Realtime_List, axis=0, ignore_index=True)
    start = str(UserDateRange['StartDate']) + " " + str(UserDateRange['StartTime'])
    end = str(UserDateRange['EndDate']) + " " + str(UserDateRange['EndTime'])
    mask = (Realtime_DF['dt'] > start) & (Realtime_DF['dt'] <= end)
    filtered_DF = Realtime_DF[mask]
    return filtered_DF

[                     dt        date      time bitdepth      md blockpos  \
 0   2023-04-28 01:10:03  2023-04-28  01:10:03   657.59  657.59     6.87
 1   2023-04-28 01:10:08  2023-04-28  01:10:08   657.61  657.61     6.84
 2   2023-04-28 01:10:13  2023-04-28  01:10:13   657.64  657.64     6.81
 3   2023-04-28 01:10:18  2023-04-28  01:10:18   657.68  657.68     6.78
 4   2023-04-28 01:10:23  2023-04-28  01:10:23   657.68  657.68     6.78
 ..                  ...         ...       ...      ...     ...      ...
 355 2023-04-28 01:39:38  2023-04-28  01:39:38   662.73  662.73     1.72
 356 2023-04-28 01:39:43  2023-04-28  01:39:43   662.74  662.74     1.71
 357 2023-04-28 01:39:48  2023-04-28  01:39:48   662.77  662.77     1.69
 358 2023-04-28 01:39:53  2023-04-28  01:39:53   662.79  662.79     1.66
 359 2023-04-28 01:39:58  2023-04-28  01:39:58   662.81  662.81     1.65

        rop   hklda   woba torqa    rpm stppress mudflowin
 0    11.96  136.39  30.99  0.00   0.00  1689.83    890.67
 1    11.96  136.17  31.21  0.00   0.00  1706.62    889.67
 2    11.96  134.52  32.86  0.00   0.00  1716.56    888.68
 3    11.96  135.03  32.35  0.00   0.00  1713.99    888.68
 4    11.96  135.24  32.14  0.00   0.00  1712.51    888.68
 ..     ...     ...    ...   ...    ...      ...       ...
 355  17.22  144.12  23.26  5.94  41.00  1542.42    894.64
 356  17.22  143.26  24.12  6.17  41.00  1550.00    894.64
 357  17.22  144.69  22.69  5.93  41.00  1543.64    896.62
 358  17.22  144.12  23.26  5.87  41.00  1543.94    895.63
 359  17.22  143.33  24.05  5.75  41.00  1545.75    894.64

 [360 rows x 13 columns],
                      dt        date      time bitdepth      md blockpos  \
 0   2023-04-28 01:40:03  2023-04-28  01:40:03   662.82  662.82     1.63
 1   2023-04-28 01:40:08  2023-04-28  01:40:08   662.82  662.82     1.63
 2   2023-04-28 01:40:13  2023-04-28  01:40:13   662.83  662.83     1.63
 3   2023-04-28 01:40:18  2023-04-28  01:40:18   662.83  662.83     1.62
 4   2023-04-28 01:40:23  2023-04-28  01:40:23   662.85  662.85     1.60
 ..                  ...         ...       ...      ...     ...      ...
 355 2023-04-28 02:09:38  2023-04-28  02:09:38   663.30  663.30    30.19
 356 2023-04-28 02:09:43  2023-04-28  02:09:43   663.31  663.31    30.19
 357 2023-04-28 02:09:48  2023-04-28  02:09:48   663.31  663.31    30.19
 358 2023-04-28 02:09:53  2023-04-28  02:09:53   663.31  663.31    30.19
 359 2023-04-28 02:09:58  2023-04-28  02:09:58   663.31  663.31    30.19

        rop   hklda   woba torqa    rpm stppress mudflowin
 0    17.22  143.19  24.19  5.75  41.00  1541.51    896.62
 1    17.22  145.19  22.19  5.34  41.00  1536.06    896.62
 2    17.22  148.77  18.61  4.62  41.00  1515.15    897.62
 3    17.22  150.99  16.39  4.41  41.00  1497.54    896.62
 4    17.22  151.35  16.03  4.41  41.00  1493.93    897.62
 ..     ...     ...    ...   ...    ...      ...       ...
 355   6.78  145.77  21.69  5.29  43.00  1577.58    889.67
 356   6.78  146.12  21.34  5.28  43.00  1587.58    888.68
 357   6.78  148.62  18.85  4.62  43.00  1589.14    901.09
 358   6.78  151.15  16.31  4.20  43.00  1578.03    901.09
 359   6.78  153.63  18.15  3.75  43.00  1563.13    899.44

 [360 rows x 13 columns],
                      dt        date      time bitdepth      md blockpos  \
 0   2023-04-28 02:10:03  2023-04-28  02:10:03   663.31  663.31    30.19
 1   2023-04-28 02:10:08  2023-04-28  02:10:08   663.34  663.34    30.15
 2   2023-04-28 02:10:13  2023-04-28  02:10:13   663.37  663.37    30.12
 3   2023-04-28 02:10:18  2023-04-28  02:10:18   663.40  663.40    30.10
 4   2023-04-28 02:10:23  2023-04-28  02:10:23   663.41  663.41    30.08
 ..                  ...         ...       ...      ...     ...      ...
 355 2023-04-28 02:39:38  2023-04-28  02:39:38   667.96  667.96    25.54
 356 2023-04-28 02:39:43  2023-04-28  02:39:43   668.00  668.00    25.49
 357 2023-04-28 02:39:48  2023-04-28  02:39:48   668.05  668.05    25.44
 358 2023-04-28 02:39:53  2023-04-28  02:39:53   668.09  668.09    25.40
 359 2023-04-28 02:39:58  2023-04-28  02:39:58   668.12  668.12    25.38

        rop   hklda   woba torqa    rpm stppress mudflowin
 0     6.78  156.16  15.62  3.44  43.00  1551.52    899.60
 1     6.78  156.54  15.24  3.65  43.00  1546.67    899.60
 2     6.78  149.99  21.79  4.67  43.00  1572.23    898.61
 3     6.78  147.34  24.44  5.36  43.00  1606.67    898.61
 4     6.78  146.05  25.73  5.55  43.00  1619.70    898.61
 ..     ...     ...    ...   ...    ...      ...       ...
 355  16.14  148.49  23.29  0.00   0.00  1565.46    898.61
 356  17.05  145.05  26.73  0.00   0.00  1631.82    898.61
 357  20.69  146.12  25.66  0.00   0.00  1628.18    898.61
 358  20.69  147.13  24.65  0.00   0.00  1612.12    898.61
 359  20.69  150.71  21.07  0.00   0.00  1587.88    898.61

 [360 rows x 13 columns],
                      dt        date      time bitdepth      md blockpos  \
 0   2023-04-28 02:40:03  2023-04-28  02:40:03   668.15  668.15    25.34
 1   2023-04-28 02:40:08  2023-04-28  02:40:08   668.20  668.20    25.29
 2   2023-04-28 02:40:13  2023-04-28  02:40:13   668.26  668.26    25.24
 3   2023-04-28 02:40:18  2023-04-28  02:40:18   668.30  668.30    25.20
 4   2023-04-28 02:40:23  2023-04-28  02:40:23   668.32  668.32    25.18
 ..                  ...         ...       ...      ...     ...      ...
 354 2023-04-28 03:09:38  2023-04-28  03:09:38   671.94  677.02    21.55
 355 2023-04-28 03:09:43  2023-04-28  03:09:43   672.25  677.02    21.25
 356 2023-04-28 03:09:48  2023-04-28  03:09:48   672.54  677.02    20.95
 357 2023-04-28 03:09:53  2023-04-28  03:09:53   672.83  677.02    20.67
 358 2023-04-28 03:09:58  2023-04-28  03:09:58   673.12  677.02    20.38

        rop   hklda   woba torqa    rpm stppress mudflowin
 0    20.69  151.71  20.07  0.00   0.00  1563.64    898.61
 1    20.69  151.21  20.57  0.00   0.00  1561.21    898.61
 2    20.69  148.70  23.08  0.00   0.00  1581.51    898.61
 3    20.69  148.34  23.44  0.00   0.00  1595.15    898.61
 4    20.69  151.06  20.72  0.00   0.00  1580.61    898.61
 ..     ...     ...    ...   ...    ...      ...       ...
 354  16.90  170.79   0.00  2.62  33.00  1513.03    898.61
 355  16.90  170.73   0.00  2.63  33.00  1519.09    899.60
 356  16.90  171.05   0.00  2.52  33.00  1517.88    898.61
 357  16.90  170.98   0.00  2.54  33.00  1515.76    899.60
 358  16.90  171.00   0.00  2.89  33.00  1520.45    898.61

 [359 rows x 13 columns],
                      dt        date      time bitdepth      md blockpos  \
 0   2023-04-28 03:10:03  2023-04-28  03:10:03   673.41  677.02    20.08
 1   2023-04-28 03:10:08  2023-04-28  03:10:08   673.71  677.02    19.78
 2   2023-04-28 03:10:13  2023-04-28  03:10:13   674.01  677.02    19.49
 3   2023-04-28 03:10:18  2023-04-28  03:10:18   674.30  677.02    19.19
 4   2023-04-28 03:10:23  2023-04-28  03:10:23   674.59  677.02    18.90
 ..                  ...         ...       ...      ...     ...      ...
 355 2023-04-28 03:39:38  2023-04-28  03:39:38   683.33  683.33    10.16
 356 2023-04-28 03:39:43  2023-04-28  03:39:43   683.35  683.35    10.14
 357 2023-04-28 03:39:48  2023-04-28  03:39:48   683.36  683.36    10.13
 358 2023-04-28 03:39:53  2023-04-28  03:39:53   683.37  683.37    10.12
 359 2023-04-28 03:39:58  2023-04-28  03:39:58   683.40  683.40    10.09

        rop   hklda   woba torqa    rpm stppress mudflowin
 0    16.90  170.85   0.00  2.63  33.00  1520.30    899.60
 1    16.90  170.60   0.00  2.50  33.00  1515.46    898.61
 2    16.90  170.40   0.00  2.64  33.00  1514.55    899.60
 3    16.90  170.66   0.00  2.67  33.00  1516.06    900.60
 4    16.90  170.47   0.00  3.01  33.00  1517.57    899.60
 ..     ...     ...    ...   ...    ...      ...       ...
 355   9.42  146.34  25.44  4.89  43.00  1590.60    898.61
 356   9.42  145.05  26.73  5.08  43.00  1596.06    898.61
 357   9.42  145.34  26.44  5.13  43.00  1600.30    898.61
 358   9.42  145.76  26.02  5.05  43.00  1599.39    898.61
 359   9.42  145.93  25.85  5.06  43.00  1597.22    898.61

 [360 rows x 13 columns],
                      dt        date      time bitdepth      md blockpos   rop  \
 0   2023-04-28 03:40:03  2023-04-28  03:40:03   683.42  683.42    10.08  9.42
 1   2023-04-28 03:40:08  2023-04-28  03:40:08   683.42  683.42    10.07  9.42
 2   2023-04-28 03:40:13  2023-04-28  03:40:13   683.42  683.42    10.07  9.42
 3   2023-04-28 03:40:18  2023-04-28  03:40:18   683.42  683.42    10.07  9.42
 4   2023-04-28 03:40:23  2023-04-28  03:40:23   683.42  683.42    10.07  9.42
 ..                  ...         ...       ...      ...     ...      ...   ...
 354 2023-04-28 04:09:33  2023-04-28  04:09:33   685.93  685.93     7.57  7.42
 355 2023-04-28 04:09:43  2023-04-28  04:09:43   685.94  685.94     7.55  7.42
 356 2023-04-28 04:09:48  2023-04-28  04:09:48   685.96  685.96     7.54  7.42
 357 2023-04-28 04:09:53  2023-04-28  04:09:53   685.97  685.97     7.53  7.42
 358 2023-04-28 04:09:58  2023-04-28  04:09:58   685.98  685.98     7.52  7.42

       hklda   woba torqa    rpm stppress mudflowin
 0    143.05  28.73  5.43  43.00  1606.97    898.61
 1    143.26  28.52  5.37  43.00  1611.82    898.61
 2    145.48  26.30  5.09  43.00  1603.64    898.61
 3    148.13  23.65  4.59  43.00  1588.79    898.61
 4    150.58  21.20  4.01  43.00  1572.22    898.61
 ..      ...    ...   ...    ...      ...       ...
 354  134.95  36.83  0.00   0.00  1562.73    898.61
 355  133.95  37.83  0.00   0.00  1566.67    898.61
 356  133.95  37.83  0.00   0.00  1575.45    898.61
 357  133.74  38.04  0.00   0.00  1580.30    898.61
 358  132.59  39.19  0.00   0.00  1582.73    898.61

 [359 rows x 13 columns],
                      dt        date      time bitdepth      md blockpos   rop  \
 0   2023-04-28 04:10:03  2023-04-28  04:10:03   685.99  685.99     7.51  7.42
 1   2023-04-28 04:10:08  2023-04-28  04:10:08   685.99  685.99     7.50  7.42
 2   2023-04-28 04:10:13  2023-04-28  04:10:13   686.00  686.00     7.50  5.86
 3   2023-04-28 04:10:18  2023-04-28  04:10:18   686.01  686.01     7.49  4.81
 4   2023-04-28 04:10:23  2023-04-28  04:10:23   686.01  686.01     7.48  4.81
 ..                  ...         ...       ...      ...     ...      ...   ...
 355 2023-04-28 04:39:38  2023-04-28  04:39:38   688.96  688.96     4.54  5.76
 356 2023-04-28 04:39:43  2023-04-28  04:39:43   688.96  688.96     4.53  5.76
 357 2023-04-28 04:39:48  2023-04-28  04:39:48   688.97  688.97     4.52  5.76
 358 2023-04-28 04:39:53  2023-04-28  04:39:53   688.98  688.98     4.52  5.76
 359 2023-04-28 04:39:58  2023-04-28  04:39:58   688.98  688.98     4.51  5.76

       hklda   woba torqa   rpm stppress mudflowin
 0    132.95  38.83  0.00  0.00  1581.82    898.61
 1    133.30  38.48  0.00  0.00  1581.82    898.61
 2    133.88  37.90  0.00  0.00  1577.58    898.61
 3    133.95  37.83  0.00  0.00  1573.94    899.60
 4    133.46  38.32  0.00  0.00  1572.73    898.61
 ..      ...    ...   ...   ...      ...       ...
 355  132.52  39.26  0.00  0.00  1573.64    898.61
 356  132.81  38.97  0.00  0.00  1572.73    898.61
 357  132.52  39.26  0.00  0.00  1572.73    898.61
 358  132.38  39.40  0.00  0.00  1573.94    899.60
 359  132.52  39.26  0.00  0.00  1573.64    898.61

 [360 rows x 13 columns],
                      dt        date      time bitdepth      md blockpos   rop  \
 0   2023-04-28 04:40:03  2023-04-28  04:40:03   688.99  688.99     4.51  5.76
 1   2023-04-28 04:40:08  2023-04-28  04:40:08   689.00  689.00     4.50  5.82
 2   2023-04-28 04:40:13  2023-04-28  04:40:13   689.00  689.00     4.49  6.05
 3   2023-04-28 04:40:18  2023-04-28  04:40:18   689.01  689.01     4.48  6.05
 4   2023-04-28 04:40:23  2023-04-28  04:40:23   689.02  689.02     4.47  6.05
 ..                  ...         ...       ...      ...     ...      ...   ...
 355 2023-04-28 05:09:38  2023-04-28  05:09:38   691.56  691.56     1.27  6.42
 356 2023-04-28 05:09:43  2023-04-28  05:09:43   691.56  691.56     1.27  6.42
 357 2023-04-28 05:09:48  2023-04-28  05:09:48   691.56  691.56     1.27  6.42
 358 2023-04-28 05:09:53  2023-04-28  05:09:53   691.56  691.56     1.27  6.42
 359 2023-04-28 05:09:58  2023-04-28  05:09:58   691.56  691.56     1.27  6.42

       hklda   woba torqa    rpm stppress mudflowin
 0    133.23  38.55  0.00   0.00  1574.24    898.61
 1    133.45  38.33  0.00   0.00  1572.42    898.61
 2    133.58  38.20  0.00   0.00  1568.44    898.61
 3    133.52  38.26  0.00   0.00  1570.30    898.61
 4    133.09  38.69  0.00   0.00  1572.73    898.61
 ..      ...    ...   ...    ...      ...       ...
 355  160.79  10.99  2.91  41.00  1492.82    898.61
 356  161.74  10.04  2.82  41.00  1487.86    898.61
 357  162.68   9.10  2.71  41.00  1485.38    898.61
 358  163.74   8.04  2.69  41.00  1483.45    899.60
 359  164.58   7.20  2.57  40.00  1479.86    899.60

 [360 rows x 13 columns],
                      dt        date      time bitdepth      md blockpos   rop  \
 0   2023-04-28 05:10:03  2023-04-28  05:10:03   691.56  691.56     1.27  6.42
 1   2023-04-28 05:10:08  2023-04-28  05:10:08   691.56  691.56     1.27  6.42
 2   2023-04-28 05:10:13  2023-04-28  05:10:13   691.56  691.56     1.27  6.42
 3   2023-04-28 05:10:18  2023-04-28  05:10:18   691.56  691.56     1.27  6.42
 4   2023-04-28 05:10:23  2023-04-28  05:10:23   691.56  691.56     1.27  6.42
 ..                  ...         ...       ...      ...     ...      ...   ...
 355 2023-04-28 05:39:38  2023-04-28  05:39:38   674.37  691.56    18.46  6.42
 356 2023-04-28 05:39:43  2023-04-28  05:39:43   674.07  691.56    18.76  6.42
 357 2023-04-28 05:39:48  2023-04-28  05:39:48   673.78  691.56    19.05  6.42
 358 2023-04-28 05:39:53  2023-04-28  05:39:53   673.49  691.56    19.35  6.42
 359 2023-04-28 05:39:58  2023-04-28  05:39:58   673.19  691.56    19.64  6.42

       hklda  woba torqa    rpm stppress mudflowin
 0    165.00  6.78  2.39  33.00  1477.93    901.59
 1    165.45  6.33  2.38  31.00  1476.55    898.61
 2    165.70  6.08  2.40  31.00  1476.00    899.60
 3    166.03  5.75  2.37  31.00  1474.07    900.60
 4    166.35  5.43  2.35  31.00  1472.13    899.60
 ..      ...   ...   ...    ...      ...       ...
 355  167.12  0.00  2.01  28.00  1464.42    907.55
 356  167.31  0.00  2.22  28.00  1462.76    906.55
 357  167.57  0.00  2.15  28.00  1464.97    907.55
 358  167.38  0.00  2.17  28.00  1466.07    907.55
 359  167.06  0.00  1.92  28.00  1462.48    908.54

 [360 rows x 13 columns],
                      dt        date      time bitdepth      md blockpos   rop  \
 0   2023-04-28 05:40:03  2023-04-28  05:40:03   672.90  691.56    19.93  6.42
 1   2023-04-28 05:40:08  2023-04-28  05:40:08   672.60  691.56    20.23  6.42
 2   2023-04-28 05:40:13  2023-04-28  05:40:13   672.31  691.56    20.52  6.42
 3   2023-04-28 05:40:18  2023-04-28  05:40:18   672.02  691.56    20.81  6.42
 4   2023-04-28 05:40:23  2023-04-28  05:40:23   671.72  691.56    21.11  6.42
 ..                  ...         ...       ...      ...     ...      ...   ...
 311 2023-04-28 06:09:38  2023-04-28  06:09:38   688.24  691.56     4.59  6.42
 312 2023-04-28 06:09:43  2023-04-28  06:09:43   688.48  691.56     4.35  6.42
 313 2023-04-28 06:09:48  2023-04-28  06:09:48   688.70  691.56     4.13  6.42
 314 2023-04-28 06:09:53  2023-04-28  06:09:53   688.93  691.56     3.90  6.42
 315 2023-04-28 06:09:58  2023-04-28  06:09:58   689.16  691.56     3.67  6.42

       hklda  woba torqa    rpm stppress mudflowin
 0    166.99  0.00  1.97  28.00  1460.55    908.54
 1    166.97  0.00  1.79  28.00  1458.97    908.54
 2    167.04  0.00  2.07  28.00  1460.69    908.54
 3    167.06  0.00  2.04  28.00  1464.97    908.54
 4    166.80  0.00  1.87  28.00  1461.93    908.54
 ..      ...   ...   ...    ...      ...       ...
 311  171.75  0.00  2.28  28.00  1399.31    908.54
 312  171.62  0.00  2.62  28.00  1398.21    908.54
 313  171.88  0.00  2.33  28.00  1395.72    908.54
 314  172.07  0.00  2.14  28.00  1391.86    908.54
 315  172.65  0.00  2.11  28.00  1388.28    908.54

 [316 rows x 13 columns],
                      dt        date      time bitdepth      md blockpos   rop  \
 0   2023-04-28 06:10:03  2023-04-28  06:10:03   689.38  691.56     3.45  6.42
 1   2023-04-28 06:10:08  2023-04-28  06:10:08   689.59  691.56     3.24  6.42
 2   2023-04-28 06:10:13  2023-04-28  06:10:13   689.81  691.56     3.02  6.42
 3   2023-04-28 06:10:18  2023-04-28  06:10:18   690.03  691.56     2.80  6.42
 4   2023-04-28 06:10:23  2023-04-28  06:10:23   690.25  691.56     2.58  6.42
 ..                  ...         ...       ...      ...     ...      ...   ...
 335 2023-04-28 06:39:38  2023-04-28  06:39:38   681.49  691.56    11.34  0.00
 336 2023-04-28 06:39:43  2023-04-28  06:39:43   681.09  691.56    11.74  0.00
 337 2023-04-28 06:39:48  2023-04-28  06:39:48   680.84  691.56    11.99  0.00
 338 2023-04-28 06:39:53  2023-04-28  06:39:53   680.59  691.56    12.24  0.00
 339 2023-04-28 06:39:58  2023-04-28  06:39:58   680.34  691.56    12.49  0.00

       hklda  woba torqa    rpm stppress mudflowin
 0    172.59  0.00  1.90  28.00  1386.90    908.54
 1    172.39  0.00  1.90  28.00  1385.52    908.54
 2    172.33  0.00  1.96  28.00  1385.24    908.54
 3    172.39  0.00  2.03  28.00  1385.24    908.54
 4    172.39  0.00  1.93  28.00  1384.42    908.54
 ..      ...   ...   ...    ...      ...       ...
 335  167.57  0.00  1.98  28.00  1444.83    904.40
 336  167.63  0.00  1.72  28.00  1449.24    907.55
 337  167.57  0.00  1.85  28.00  1450.89    907.55
 338  167.38  0.00  1.76  28.00  1452.82    907.55
 339  167.51  0.00  1.89  28.00  1453.65    908.54

 [340 rows x 13 columns],
                      dt        date      time bitdepth      md blockpos   rop  \
 0   2023-04-28 06:40:03  2023-04-28  06:40:03   680.09  691.56    12.74  0.00
 1   2023-04-28 06:40:08  2023-04-28  06:40:08   679.85  691.56    12.98  0.00
 2   2023-04-28 06:40:13  2023-04-28  06:40:13   679.60  691.56    13.23  0.00
 3   2023-04-28 06:40:18  2023-04-28  06:40:18   679.36  691.56    13.47  0.00
 4   2023-04-28 06:40:23  2023-04-28  06:40:23   679.11  691.56    13.72  0.00
 ..                  ...         ...       ...      ...     ...      ...   ...
 353 2023-04-28 07:09:38  2023-04-28  07:09:38   632.16  691.56    32.15  0.00
 354 2023-04-28 07:09:43  2023-04-28  07:09:43   632.16  691.56    32.15  0.00
 355 2023-04-28 07:09:48  2023-04-28  07:09:48   632.16  691.56    32.15  0.00
 356 2023-04-28 07:09:53  2023-04-28  07:09:53   632.16  691.56    32.15  0.00
 357 2023-04-28 07:09:58  2023-04-28  07:09:58   632.16  691.56    32.15  0.00

       hklda  woba torqa    rpm stppress mudflowin
 0    167.25  0.00  1.79  28.00  1455.58    906.55
 1    167.25  0.00  1.98  28.00  1456.41    907.55
 2    167.25  0.00  1.82  28.00  1456.41    908.54
 3    167.38  0.00  2.05  28.00  1456.14    906.55
 4    167.19  0.00  1.93  28.00  1456.96    908.54
 ..      ...   ...   ...    ...      ...       ...
 353   70.92  0.00  0.00   0.00     0.00      0.00
 354   51.44  0.00  0.00   0.00     0.00      0.00
 355   51.39  0.00  0.00   0.00     0.00      0.00
 356   51.39  0.00  0.00   0.00     0.00      0.00
 357   51.41  0.00  0.00   0.00     0.00      0.00

 [358 rows x 13 columns],
                      dt        date      time bitdepth      md blockpos   rop  \
 0   2023-04-28 07:10:03  2023-04-28  07:10:03   632.16  691.56    32.15  0.00
 1   2023-04-28 07:10:08  2023-04-28  07:10:08   632.16  691.56    32.15  0.00
 2   2023-04-28 07:10:13  2023-04-28  07:10:13   632.16  691.56    32.15  0.00
 3   2023-04-28 07:10:18  2023-04-28  07:10:18   632.16  691.56    32.15  0.00
 4   2023-04-28 07:10:23  2023-04-28  07:10:23   632.16  691.56    32.14  0.00
 ..                  ...         ...       ...      ...     ...      ...   ...
 355 2023-04-28 07:39:38  2023-04-28  07:39:38   575.52  691.56    31.89  0.00
 356 2023-04-28 07:39:43  2023-04-28  07:39:43   575.52  691.56    31.89  0.00

In [48]:
import multiprocessing
from multiprocessing.pool import ThreadPool

# Get the number of available CPU cores
num_cores = multiprocessing.cpu_count()
num_cores

8

In [56]:
a= [1,2,3]
b=[4,3,2]
out = list(zip(a,b))
out

[(1, 4), (2, 3), (3, 2)]

In [58]:
StartEnd,EndStart = out[0]

In [60]:
EndStart

4