In [1]:
import pandas as pd

In [2]:
import requests
CompName_JSON = requests.get(
        "https://pdumitradome.id/dome_api/rtdc/get_company/"
    ).json()
CompName_DF = pd.json_normalize(CompName_JSON, record_path = 'result')
selected_comp = "KS ORKA"

display(CompName_DF[CompName_DF['company_name']==selected_comp])

getWellAPI = "https://pdumitradome.id/dome_api/rtdc/get_well?cid=" + (CompName_DF.loc[CompName_DF['company_name']==selected_comp, 'cid'].values)
WellName_JSON = requests.get(
        getWellAPI[0]
    ).json()
WellName_DF = pd.json_normalize(WellName_JSON, record_path = 'result')
display(WellName_DF)

   cid company_name
22   9      KS ORKA

,wid,cid,well_name,rig_name,active_date,end_date,proposed_total_measured_depth,time_master
0,129,9,SMP T10,Kaishan-1,2020-11-13,2020-12-31,2500,"[{'time_date_start': '2021-01-04', 'time_date_..."
1,130,9,SMP - 119,PRA#1,2020-11-28,2021-01-30,2500,[]
2,135,9,SMP P-118 ST,PRA#1,2021-01-05,2021-04-30,3000,"[{'time_date_start': '2021-01-04', 'time_date_..."
3,136,9,SMP AA-01ST2,Kaishan 1,2021-01-14,2021-07-31,3000,"[{'time_date_start': '2021-01-11', 'time_date_..."
4,140,9,SMP AA-03,Kaishan 1,2021-04-15,2021-06-30,3000,"[{'time_date_start': '2021-04-12', 'time_date_..."
5,143,9,SMP AAE-03,PRA#1,2021-04-25,2021-06-30,3000,"[{'time_date_start': '2021-04-19', 'time_date_..."
6,144,9,SMP AAE-02,PRA#1,2021-06-03,2021-07-31,4000,"[{'time_date_start': '2021-05-31', 'time_date_..."
7,145,9,SMP AA-02ST,Kaishan 1,2021-06-17,2021-08-31,4000,"[{'time_date_start': '2021-06-14', 'time_date_..."
8,146,9,SMP AAE-05,PRA#1,2021-06-28,2021-08-31,4000,"[{'time_date_start': '2021-06-28', 'time_date_..."
9,150,9,SMP AAE-06ST3,PRA#1,2021-08-12,2022-02-05,3000,"[{'time_date_start': '2021-08-09', 'time_date_..."
10,156,9,SMP AAE-07,PRA#1,2021-09-25,2021-10-31,3000,"[{'time_date_start': '2021-09-20', 'time_date_..."
11,160,9,SMP AAE-07ST3,PRA#1,2021-10-25,2022-01-01,3000,"[{'time_date_start': '2021-10-25', 'time_date_..."
12,170,9,SMP AAE-08,PRA#1,2022-01-27,2022-03-31,2500,"[{'time_date_start': '2022-01-24', 'time_date_..."
13,175,9,SMP T-11,Kaishan 1,2022-02-25,2022-04-30,3000,"[{'time_date_start': '2022-02-21', 'time_date_..."
14,182,9,SMP T-12,Kaishan-1,2022-04-12,2022-05-31,3000,"[{'time_date_start': '2022-04-11', 'time_date_..."
15,186,9,SMP T-11 WO,Kaishan 1,2022-07-22,2022-08-31,3000,"[{'time_date_start': '2022-07-18', 'time_date_..."
16,215,9,SMP P-117L2,Kaishan 1,2023-01-01,2023-04-30,3000,"[{'time_date_start': '2022-12-26', 'time_date_..."

In [3]:
Well_ID_API = 146

In [4]:
SummaryActivity_DF = pd.read_excel(
    "..\\Data\\Master_Report\\KS_ORKA\\AAE-05\\Upload_AAE-05_12.25in_Rev.1.3.xlsx",
    sheet_name = "Raw Data"
)
SummaryActivity_DF['Remarks'].fillna("", inplace=True)
SummaryActivity_DF = SummaryActivity_DF.dropna(subset=['Date'])
# SummaryActivity_DF['Date/Time_End'] = SummaryActivity_DF['Date/Time'].shift(periods=-1)
ActivityLogUnique = SummaryActivity_DF[SummaryActivity_DF['Activity'] != SummaryActivity_DF['Activity'].shift(periods=1)]
ActivityLogUnique['Activity'] = ActivityLogUnique['Activity'].str.upper()
# display(SummaryActivity_DF.head(5))
display(ActivityLogUnique)
print(ActivityLogUnique["Date/Time"].min())
print(ActivityLogUnique["Date/Time"].max())

C:\Users\irsya\AppData\Local\Temp\ipykernel_18960\687291086.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ActivityLogUnique['Activity'] = ActivityLogUnique['Activity'].str.upper()

,Date,Time,Date/Time,Duration,Hole Depth,Bit Depth,Meterage (m) (Drilling),Rotate Drilling Time (hrs),Slide Drilling Time (hrs),Reaming Time (hrs),Connection Time (hrs),On Bottom Hours,Stand Duration (hrs),Connection Activity,Sub Activity,Activity,Remarks,WELL NAME,SECTION SIZE
0,2021-07-28,00:30:00,2021-07-28 00:30:00,165.083333,489.24,31.29,,,,,,NaN,NaN,NaN,Make Up BHA,MAKE UP BHA,,NaN,"12 1/4"""
2,2021-07-28,03:18:05,2021-07-28 03:18:05,5.833333,489.24,31.46,,,,,,NaN,NaN,NaN,Moving,TRIP IN,,NaN,"12 1/4"""
49,2021-07-28,07:25:40,2021-07-28 07:25:40,7.000000,489.24,476.00,,,,00:07:00,,NaN,NaN,NaN,Reaming,DRILL OUT CEMENT,Tag @ 476 mMD,NaN,"12 1/4"""
172,2021-07-28,17:15:20,2021-07-28 17:15:20,45.083333,1370.03,1370.03,,,,,,NaN,NaN,NaN,Pressure Test,OTHER,Pressure Test casing at 1370 mMD,NaN,"12 1/4"""
173,2021-07-28,18:00:25,2021-07-28 18:00:25,62.000000,1373.30,1373.30,3.27,01:02:00,,,,NaN,NaN,NaN,Rotary Drilling,DRILL OUT CEMENT,,NaN,"12 1/4"""
183,2021-07-28,21:41:55,2021-07-28 21:41:55,37.500000,1403.00,1403.00,2.99,00:37:30,,,,NaN,NaN,NaN,Rotary Drilling,DRILLING FORMATION,,NaN,"12 1/4"""
186,2021-07-28,23:25:55,2021-07-28 23:25:55,47.083333,1403.00,1403.00,,,,,,NaN,NaN,NaN,Pressure Test,OTHER,"FIT, EMW 14.2 ppg",NaN,"12 1/4"""
187,2021-07-29,00:13:00,2021-07-29 00:13:00,8.000000,1403.00,1403.00,,,,,00:08:00,NaN,NaN,NaN,Connection,DRILLING FORMATION,,NaN,"12 1/4"""
266,2021-07-30,13:04:02,2021-07-30 13:04:02,2.333333,1710.88,1678.93,,,,,,NaN,NaN,NaN,Moving,TRIP OUT,POOH,NaN,"12 1/4"""
395,2021-07-30,22:06:59,2021-07-30 22:06:59,51.083333,1710.88,0.00,,,,,,NaN,NaN,NaN,Stationary,STATIONARY,Bit on surface,NaN,"12 1/4"""
396,2021-07-30,22:58:04,2021-07-30 22:58:04,27.333333,1710.88,0.00,,,,,,NaN,NaN,NaN,Other,OTHER,Prepare make up BHA,NaN,"12 1/4"""
397,2021-07-30,23:25:24,2021-07-30 23:25:24,32.916667,1710.88,0.47,,,,,,NaN,NaN,NaN,Make Up BHA,MAKE UP BHA,Make Up BHA,NaN,"12 1/4"""
400,2021-07-31,00:57:39,2021-07-31 00:57:39,1.833333,1710.88,19.03,,,,,,NaN,NaN,NaN,Moving,TRIP IN,,NaN,"12 1/4"""
529,2021-07-31,07:32:40,2021-07-31 07:32:40,19.666667,1716.63,1716.63,5.75,00:19:40,,,,NaN,NaN,NaN,Rotary Drilling,DRILLING FORMATION,,NaN,"12 1/4"""
602,2021-08-01,08:56:23,2021-08-01 08:56:23,2.666667,2041.22,2010.88,,,,,,NaN,NaN,Post Connection,Moving,WIPER TRIP,Wiper Trip,NaN,"12 1/4"""
650,2021-08-01,11:32:03,2021-08-01 11:32:03,4.000000,2041.22,2041.03,,,,,00:04:00,NaN,NaN,NaN,Connection,DRILLING FORMATION,,NaN,"12 1/4"""
674,2021-08-01,21:18:50,2021-08-01 21:18:50,3.916667,2159.01,2130.00,,,,,,NaN,NaN,NaN,Wash Down,WIPER TRIP,,NaN,"12 1/4"""
700,2021-08-01,23:32:46,2021-08-01 23:32:46,4.416667,2159.01,2156.87,,,,,00:04:25,NaN,NaN,NaN,Connection,DRILLING FORMATION,,NaN,"12 1/4"""
706,2021-08-02,03:00:03,2021-08-02 03:00:03,7.000000,2178.58,2176.81,,,,,,NaN,NaN,NaN,Wash Down,TRIP OUT,,NaN,"12 1/4"""
861,2021-08-02,12:20:00,2021-08-02 12:20:00,160.500000,2178.58,56.23,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,Lay Down BHA,LAY DOWN BHA,,NaN,"12 1/4"""
862,2021-08-02,15:00:30,2021-08-02 15:00:30,71.433333,2178.58,0.00,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,Other,OTHER,Bit on surface,NaN,"12 1/4"""
863,2021-08-02,16:11:56,2021-08-02 16:11:56,5.250000,2178.58,0.11,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,Moving,RUNNING CASING IN,RIH Casing #1,NaN,"12 1/4"""
1110,2021-08-03,02:30:17,2021-08-03 02:30:17,6.916667,2178.58,2176.13,NaN,NaN,NaN,NaN,00:06:55,NaN,NaN,NaN,Connection,TRIP OUT,,NaN,"12 1/4"""
1204,2021-08-03,06:02:02,2021-08-03 06:02:02,99.366667,2178.58,0.00,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,Other,OTHER,L/D Running Tools,NaN,"12 1/4"""

2021-07-28 00:30:00
2021-08-03 06:02:02

In [7]:
help(IO_Data)

Help on module PDU_Func.IO_Data in PDU_Func:

NAME
    PDU_Func.IO_Data

FUNCTIONS
    DomeCheckTable(wid: int, table_type: str = 'ActivityLogTable')

    DomeCreateTable(wid: int, table_type: str = 'ActivityLogTable')

    DomeInsertData(dict_row, table_type='ActivityLogTable')

    getAvailableCompanyDF(UserAuthDict)
        # @st.cache_resource

    getAvailableWellDF(SelectComp, UserAuthDict)
        # @st.cache_resource

    getWellInfoDict(UserAuthDict, SelectComp, SelectWell)
        # @st.cache_data

FILE
    c:\users\irsya\documents\jiunx_files\project\2021-pdu\01_pdu_python\streamlit_app_v2\pdu_func\io_data.py

In [6]:
from PDU_Func import IO_Data
import time

if IO_Data.DomeCheckTable(Well_ID_API, table_type="ActivityLogTable")['table']==0:
    IO_Data.DomeCreateTable(Well_ID_API, table_type="ActivityLogTable")



for i,row in ActivityLogUnique.iterrows():
    input_dict_temp = {
        'wid':Well_ID_API,
        'dt':str(row['Date/Time']),
        'date':str(row['Date'].date()),
        'time':str(row['Time']),
        'activity':row['Activity'],
        'in_slip_threshold':63,
        'remarks' : row['Remarks'],
        'pic' : 'Admin',
        'section':'12 1/4"'
        
    }

    print(IO_Data.DomeInsertData(input_dict_temp))
    # time.sleep(3)
    print(input_dict_temp)

check ActivityLogTable
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-07-28 00:30:00', 'date': '2021-07-28', 'time': '00:30:00', 'activity': 'MAKE UP BHA', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-07-28 03:18:05', 'date': '2021-07-28', 'time': '03:18:05', 'activity': 'TRIP IN', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-07-28 07:25:40', 'date': '2021-07-28', 'time': '07:25:40', 'activity': 'DRILL OUT CEMENT', 'in_slip_threshold': 63, 'remarks': 'Tag @ 476 mMD', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-07-28 17:15:20', 'date': '2021-07-28', 'time': '17:15:20', 'activity': 'OTHER', 'in_slip_threshold': 63, 'remarks': 'Pressure Test casing at 1370 mMD', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-07-28 18:00:25', 'date': '2021-07-28', 'time': '18:00:25', 'activity': 'DRILL OUT CEMENT', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-07-28 21:41:55', 'date': '2021-07-28', 'time': '21:41:55', 'activity': 'DRILLING FORMATION', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-07-28 23:25:55', 'date': '2021-07-28', 'time': '23:25:55', 'activity': 'OTHER', 'in_slip_threshold': 63, 'remarks': 'FIT, EMW 14.2 ppg', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-07-29 00:13:00', 'date': '2021-07-29', 'time': '00:13:00', 'activity': 'DRILLING FORMATION', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-07-30 13:04:02', 'date': '2021-07-30', 'time': '13:04:02', 'activity': 'TRIP OUT', 'in_slip_threshold': 63, 'remarks': 'POOH', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-07-30 22:06:59', 'date': '2021-07-30', 'time': '22:06:59', 'activity': 'STATIONARY', 'in_slip_threshold': 63, 'remarks': 'Bit on surface', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-07-30 22:58:04', 'date': '2021-07-30', 'time': '22:58:04', 'activity': 'OTHER', 'in_slip_threshold': 63, 'remarks': 'Prepare make up BHA', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-07-30 23:25:24', 'date': '2021-07-30', 'time': '23:25:24', 'activity': 'MAKE UP BHA', 'in_slip_threshold': 63, 'remarks': 'Make Up BHA', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-07-31 00:57:39', 'date': '2021-07-31', 'time': '00:57:39', 'activity': 'TRIP IN', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-07-31 07:32:40', 'date': '2021-07-31', 'time': '07:32:40', 'activity': 'DRILLING FORMATION', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-08-01 08:56:23', 'date': '2021-08-01', 'time': '08:56:23', 'activity': 'WIPER TRIP', 'in_slip_threshold': 63, 'remarks': 'Wiper Trip', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-08-01 11:32:03', 'date': '2021-08-01', 'time': '11:32:03', 'activity': 'DRILLING FORMATION', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-08-01 21:18:50', 'date': '2021-08-01', 'time': '21:18:50', 'activity': 'WIPER TRIP', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-08-01 23:32:46', 'date': '2021-08-01', 'time': '23:32:46', 'activity': 'DRILLING FORMATION', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-08-02 03:00:03', 'date': '2021-08-02', 'time': '03:00:03', 'activity': 'TRIP OUT', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-08-02 12:20:00', 'date': '2021-08-02', 'time': '12:20:00', 'activity': 'LAY DOWN BHA', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-08-02 15:00:30', 'date': '2021-08-02', 'time': '15:00:30', 'activity': 'OTHER', 'in_slip_threshold': 63, 'remarks': 'Bit on surface', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-08-02 16:11:56', 'date': '2021-08-02', 'time': '16:11:56', 'activity': 'RUNNING CASING IN', 'in_slip_threshold': 63, 'remarks': 'RIH Casing #1', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-08-03 02:30:17', 'date': '2021-08-03', 'time': '02:30:17', 'activity': 'TRIP OUT', 'in_slip_threshold': 63, 'remarks': '', 'pic': 'Admin', 'section': '12 1/4"'}
add new data to ActivityLogTable
{'message': 'Insert Data Success', 'status': 200}
{'wid': 146, 'dt': '2021-08-03 06:02:02', 'date': '2021-08-03', 'time': '06:02:02', 'activity': 'OTHER', 'in_slip_threshold': 63, 'remarks': 'L/D Running Tools', 'pic': 'Admin', 'section': '12 1/4"'}

In [15]:
print('12 1/4"')

12 1/4"

In [26]:
timestart = ActivityLogUnique["Date/Time"].min()
timeend = ActivityLogUnique["Date/Time"].max()
InputActivity_DB = (IO_Data.DomeGetData(Well_ID_API, timestart, timeend))
InputActivity_DB

c:\Users\irsya\Documents\Jiunx_Files\PROJECT\2021-PDU\01_PDU_python\Streamlit_App\IO_Data.py:421: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  out_DF = out_DF.sort_values(by='date_time')

,input_id,dt,date,time,activity,in_slip_threshold,remarks,pic,section
0,258,2021-10-04 09:00:01,2021-10-04,09:00:01,MAKE UP BHA,0,,Admin,"26"""""
1,259,2021-10-04 13:28:31,2021-10-04,13:28:31,TRIP IN,0,,Admin,"26"""""
2,260,2021-10-04 14:09:36,2021-10-04,14:09:36,DRILL OUT CEMENT,0,Lost connection at 15:47,Admin,"26"""""
3,261,2021-10-04 17:40:01,2021-10-04,17:40:01,RIG REPAIR,0,Repair TDS,Admin,"26"""""
4,262,2021-10-04 18:27:26,2021-10-04,18:27:26,DRILLING FORMATION,0,,Admin,"26"""""
...,...,...,...,...,...,...,...,...,...
81,348,2021-10-19 07:59:05,2021-10-19,07:59:05,DRILLING FORMATION,0,,Admin,"12-1/4"""""
82,349,2021-10-20 11:01:29,2021-10-20,11:01:29,CIRCULATE HOLE CLEANING,0,Circulation hole cleaning due to erratic torque,Admin,"12-1/4"""""
83,350,2021-10-20 12:10:00,2021-10-20,12:10:00,STUCK PIPE,0,Stuck pipe incident,Admin,"12-1/4"""""
84,351,2021-10-20 12:20:00,2021-10-20,12:20:00,CIRCULATION,0,Circulation hole cleaning post stuck pipe,Admin,"12-1/4"""""
85,352,2021-10-20 14:07:00,2021-10-20,14:07:00,STUCK PIPE,0,,Admin,"12-1/4"""""